// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package zitadel

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/truvity/pulumi-zitadel/sdk/go/zitadel/internal"
)

// Resource representing a public key for an action target, used for payload encryption.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi-std/sdk/v2/go/std"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/truvity/pulumi-zitadel/sdk/go/zitadel"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			invokeFile, err := std.File(ctx, &std.FileArgs{
//				Input: "path/to/public_key.pem",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			_, err = zitadel.NewActionTargetPublicKey(ctx, "default", &zitadel.ActionTargetPublicKeyArgs{
//				TargetId:  pulumi.Any(defaultZitadelActionTarget.Id),
//				PublicKey: pulumi.String(invokeFile.Result),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Import
//
// The resource can be imported using the ID format `<key_id>:<target_id>`, e.g.
//
// ```sh
// $ pulumi import zitadel:index/actionTargetPublicKey:ActionTargetPublicKey imported '123456789012345678:123456789012345678'
// ```
type ActionTargetPublicKey struct {
	pulumi.CustomResourceState

	// Whether the public key is active and used for payload encryption.
	Active pulumi.BoolOutput `pulumi:"active"`
	// The date the public key was added.
	CreationDate pulumi.StringOutput `pulumi:"creationDate"`
	// The expiration date of the public key in RFC3339 format.
	ExpirationDate pulumi.StringPtrOutput `pulumi:"expirationDate"`
	// The fingerprint of the public key.
	Fingerprint pulumi.StringOutput `pulumi:"fingerprint"`
	// The ID of the public key, used as 'kid' in the JWE header.
	KeyId pulumi.StringOutput `pulumi:"keyId"`
	// The public key in PEM format (RSA or EC).
	PublicKey pulumi.StringOutput `pulumi:"publicKey"`
	// The ID of the action target to add the public key to.
	TargetId pulumi.StringOutput `pulumi:"targetId"`
}

// NewActionTargetPublicKey registers a new resource with the given unique name, arguments, and options.
func NewActionTargetPublicKey(ctx *pulumi.Context,
	name string, args *ActionTargetPublicKeyArgs, opts ...pulumi.ResourceOption) (*ActionTargetPublicKey, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.PublicKey == nil {
		return nil, errors.New("invalid value for required argument 'PublicKey'")
	}
	if args.TargetId == nil {
		return nil, errors.New("invalid value for required argument 'TargetId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource ActionTargetPublicKey
	err := ctx.RegisterResource("zitadel:index/actionTargetPublicKey:ActionTargetPublicKey", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetActionTargetPublicKey gets an existing ActionTargetPublicKey resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetActionTargetPublicKey(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ActionTargetPublicKeyState, opts ...pulumi.ResourceOption) (*ActionTargetPublicKey, error) {
	var resource ActionTargetPublicKey
	err := ctx.ReadResource("zitadel:index/actionTargetPublicKey:ActionTargetPublicKey", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ActionTargetPublicKey resources.
type actionTargetPublicKeyState struct {
	// Whether the public key is active and used for payload encryption.
	Active *bool `pulumi:"active"`
	// The date the public key was added.
	CreationDate *string `pulumi:"creationDate"`
	// The expiration date of the public key in RFC3339 format.
	ExpirationDate *string `pulumi:"expirationDate"`
	// The fingerprint of the public key.
	Fingerprint *string `pulumi:"fingerprint"`
	// The ID of the public key, used as 'kid' in the JWE header.
	KeyId *string `pulumi:"keyId"`
	// The public key in PEM format (RSA or EC).
	PublicKey *string `pulumi:"publicKey"`
	// The ID of the action target to add the public key to.
	TargetId *string `pulumi:"targetId"`
}

type ActionTargetPublicKeyState struct {
	// Whether the public key is active and used for payload encryption.
	Active pulumi.BoolPtrInput
	// The date the public key was added.
	CreationDate pulumi.StringPtrInput
	// The expiration date of the public key in RFC3339 format.
	ExpirationDate pulumi.StringPtrInput
	// The fingerprint of the public key.
	Fingerprint pulumi.StringPtrInput
	// The ID of the public key, used as 'kid' in the JWE header.
	KeyId pulumi.StringPtrInput
	// The public key in PEM format (RSA or EC).
	PublicKey pulumi.StringPtrInput
	// The ID of the action target to add the public key to.
	TargetId pulumi.StringPtrInput
}

func (ActionTargetPublicKeyState) ElementType() reflect.Type {
	return reflect.TypeOf((*actionTargetPublicKeyState)(nil)).Elem()
}

type actionTargetPublicKeyArgs struct {
	// The expiration date of the public key in RFC3339 format.
	ExpirationDate *string `pulumi:"expirationDate"`
	// The public key in PEM format (RSA or EC).
	PublicKey string `pulumi:"publicKey"`
	// The ID of the action target to add the public key to.
	TargetId string `pulumi:"targetId"`
}

// The set of arguments for constructing a ActionTargetPublicKey resource.
type ActionTargetPublicKeyArgs struct {
	// The expiration date of the public key in RFC3339 format.
	ExpirationDate pulumi.StringPtrInput
	// The public key in PEM format (RSA or EC).
	PublicKey pulumi.StringInput
	// The ID of the action target to add the public key to.
	TargetId pulumi.StringInput
}

func (ActionTargetPublicKeyArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*actionTargetPublicKeyArgs)(nil)).Elem()
}

type ActionTargetPublicKeyInput interface {
	pulumi.Input

	ToActionTargetPublicKeyOutput() ActionTargetPublicKeyOutput
	ToActionTargetPublicKeyOutputWithContext(ctx context.Context) ActionTargetPublicKeyOutput
}

func (*ActionTargetPublicKey) ElementType() reflect.Type {
	return reflect.TypeOf((**ActionTargetPublicKey)(nil)).Elem()
}

func (i *ActionTargetPublicKey) ToActionTargetPublicKeyOutput() ActionTargetPublicKeyOutput {
	return i.ToActionTargetPublicKeyOutputWithContext(context.Background())
}

func (i *ActionTargetPublicKey) ToActionTargetPublicKeyOutputWithContext(ctx context.Context) ActionTargetPublicKeyOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ActionTargetPublicKeyOutput)
}

type ActionTargetPublicKeyOutput struct{ *pulumi.OutputState }

func (ActionTargetPublicKeyOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ActionTargetPublicKey)(nil)).Elem()
}

func (o ActionTargetPublicKeyOutput) ToActionTargetPublicKeyOutput() ActionTargetPublicKeyOutput {
	return o
}

func (o ActionTargetPublicKeyOutput) ToActionTargetPublicKeyOutputWithContext(ctx context.Context) ActionTargetPublicKeyOutput {
	return o
}

// Whether the public key is active and used for payload encryption.
func (o ActionTargetPublicKeyOutput) Active() pulumi.BoolOutput {
	return o.ApplyT(func(v *ActionTargetPublicKey) pulumi.BoolOutput { return v.Active }).(pulumi.BoolOutput)
}

// The date the public key was added.
func (o ActionTargetPublicKeyOutput) CreationDate() pulumi.StringOutput {
	return o.ApplyT(func(v *ActionTargetPublicKey) pulumi.StringOutput { return v.CreationDate }).(pulumi.StringOutput)
}

// The expiration date of the public key in RFC3339 format.
func (o ActionTargetPublicKeyOutput) ExpirationDate() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ActionTargetPublicKey) pulumi.StringPtrOutput { return v.ExpirationDate }).(pulumi.StringPtrOutput)
}

// The fingerprint of the public key.
func (o ActionTargetPublicKeyOutput) Fingerprint() pulumi.StringOutput {
	return o.ApplyT(func(v *ActionTargetPublicKey) pulumi.StringOutput { return v.Fingerprint }).(pulumi.StringOutput)
}

// The ID of the public key, used as 'kid' in the JWE header.
func (o ActionTargetPublicKeyOutput) KeyId() pulumi.StringOutput {
	return o.ApplyT(func(v *ActionTargetPublicKey) pulumi.StringOutput { return v.KeyId }).(pulumi.StringOutput)
}

// The public key in PEM format (RSA or EC).
func (o ActionTargetPublicKeyOutput) PublicKey() pulumi.StringOutput {
	return o.ApplyT(func(v *ActionTargetPublicKey) pulumi.StringOutput { return v.PublicKey }).(pulumi.StringOutput)
}

// The ID of the action target to add the public key to.
func (o ActionTargetPublicKeyOutput) TargetId() pulumi.StringOutput {
	return o.ApplyT(func(v *ActionTargetPublicKey) pulumi.StringOutput { return v.TargetId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ActionTargetPublicKeyInput)(nil)).Elem(), &ActionTargetPublicKey{})
	pulumi.RegisterOutputType(ActionTargetPublicKeyOutput{})
}
