// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package zitadel

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/truvity/pulumi-zitadel/sdk/go/zitadel/internal"
)

// Resource representing the active web key.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/truvity/pulumi-zitadel/sdk/go/zitadel"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			keyV1, err := zitadel.NewWebkey(ctx, "key_v1", &zitadel.WebkeyArgs{
//				OrgId: pulumi.Any(defaultZitadelOrg.Id),
//				Rsa:   &zitadel.WebkeyRsaArgs{},
//			})
//			if err != nil {
//				return err
//			}
//			_, err = zitadel.NewWebkey(ctx, "key_v2", &zitadel.WebkeyArgs{
//				OrgId: pulumi.Any(defaultZitadelOrg.Id),
//				Ecdsa: &zitadel.WebkeyEcdsaArgs{},
//			})
//			if err != nil {
//				return err
//			}
//			_, err = zitadel.NewActiveWebkey(ctx, "default", &zitadel.ActiveWebkeyArgs{
//				OrgId: pulumi.Any(defaultZitadelOrg.Id),
//				KeyId: keyV1.ID(),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Import
//
// The resource can be imported using the ID format `<org_id>:<key_id>`, e.g.
//
// ```sh
// $ pulumi import zitadel:index/activeWebkey:ActiveWebkey imported '123456789012345678:123456789012345678'
// ```
type ActiveWebkey struct {
	pulumi.CustomResourceState

	// The ID of the webkey to be active.
	KeyId pulumi.StringOutput `pulumi:"keyId"`
	// ID of the organization. If not provided, the organization of the authenticated user/service account is used.
	OrgId pulumi.StringPtrOutput `pulumi:"orgId"`
}

// NewActiveWebkey registers a new resource with the given unique name, arguments, and options.
func NewActiveWebkey(ctx *pulumi.Context,
	name string, args *ActiveWebkeyArgs, opts ...pulumi.ResourceOption) (*ActiveWebkey, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.KeyId == nil {
		return nil, errors.New("invalid value for required argument 'KeyId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource ActiveWebkey
	err := ctx.RegisterResource("zitadel:index/activeWebkey:ActiveWebkey", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetActiveWebkey gets an existing ActiveWebkey resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetActiveWebkey(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ActiveWebkeyState, opts ...pulumi.ResourceOption) (*ActiveWebkey, error) {
	var resource ActiveWebkey
	err := ctx.ReadResource("zitadel:index/activeWebkey:ActiveWebkey", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ActiveWebkey resources.
type activeWebkeyState struct {
	// The ID of the webkey to be active.
	KeyId *string `pulumi:"keyId"`
	// ID of the organization. If not provided, the organization of the authenticated user/service account is used.
	OrgId *string `pulumi:"orgId"`
}

type ActiveWebkeyState struct {
	// The ID of the webkey to be active.
	KeyId pulumi.StringPtrInput
	// ID of the organization. If not provided, the organization of the authenticated user/service account is used.
	OrgId pulumi.StringPtrInput
}

func (ActiveWebkeyState) ElementType() reflect.Type {
	return reflect.TypeOf((*activeWebkeyState)(nil)).Elem()
}

type activeWebkeyArgs struct {
	// The ID of the webkey to be active.
	KeyId string `pulumi:"keyId"`
	// ID of the organization. If not provided, the organization of the authenticated user/service account is used.
	OrgId *string `pulumi:"orgId"`
}

// The set of arguments for constructing a ActiveWebkey resource.
type ActiveWebkeyArgs struct {
	// The ID of the webkey to be active.
	KeyId pulumi.StringInput
	// ID of the organization. If not provided, the organization of the authenticated user/service account is used.
	OrgId pulumi.StringPtrInput
}

func (ActiveWebkeyArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*activeWebkeyArgs)(nil)).Elem()
}

type ActiveWebkeyInput interface {
	pulumi.Input

	ToActiveWebkeyOutput() ActiveWebkeyOutput
	ToActiveWebkeyOutputWithContext(ctx context.Context) ActiveWebkeyOutput
}

func (*ActiveWebkey) ElementType() reflect.Type {
	return reflect.TypeOf((**ActiveWebkey)(nil)).Elem()
}

func (i *ActiveWebkey) ToActiveWebkeyOutput() ActiveWebkeyOutput {
	return i.ToActiveWebkeyOutputWithContext(context.Background())
}

func (i *ActiveWebkey) ToActiveWebkeyOutputWithContext(ctx context.Context) ActiveWebkeyOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ActiveWebkeyOutput)
}

type ActiveWebkeyOutput struct{ *pulumi.OutputState }

func (ActiveWebkeyOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ActiveWebkey)(nil)).Elem()
}

func (o ActiveWebkeyOutput) ToActiveWebkeyOutput() ActiveWebkeyOutput {
	return o
}

func (o ActiveWebkeyOutput) ToActiveWebkeyOutputWithContext(ctx context.Context) ActiveWebkeyOutput {
	return o
}

// The ID of the webkey to be active.
func (o ActiveWebkeyOutput) KeyId() pulumi.StringOutput {
	return o.ApplyT(func(v *ActiveWebkey) pulumi.StringOutput { return v.KeyId }).(pulumi.StringOutput)
}

// ID of the organization. If not provided, the organization of the authenticated user/service account is used.
func (o ActiveWebkeyOutput) OrgId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ActiveWebkey) pulumi.StringPtrOutput { return v.OrgId }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ActiveWebkeyInput)(nil)).Elem(), &ActiveWebkey{})
	pulumi.RegisterOutputType(ActiveWebkeyOutput{})
}
