// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package zitadel

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/truvity/pulumi-zitadel/sdk/go/zitadel/internal"
)

// Resource representing an action execution triggered by a function.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/truvity/pulumi-zitadel/sdk/go/zitadel"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_default, err := zitadel.NewActionTarget(ctx, "default", &zitadel.ActionTargetArgs{
//				Name:             pulumi.String("token-enricher"),
//				Endpoint:         pulumi.String("https://example.com/oidc/enrich"),
//				TargetType:       pulumi.String("REST_CALL"),
//				Timeout:          pulumi.String("10s"),
//				InterruptOnError: pulumi.Bool(true),
//			})
//			if err != nil {
//				return err
//			}
//			_, err = zitadel.NewActionExecutionFunction(ctx, "default", &zitadel.ActionExecutionFunctionArgs{
//				Name: pulumi.String("preaccesstoken"),
//				TargetIds: pulumi.StringArray{
//					_default.ID(),
//				},
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Import
//
// function name: preuserinfo, preaccesstoken, or presamlresponse
//
// ```sh
// $ pulumi import zitadel:index/actionExecutionFunction:ActionExecutionFunction imported 'preaccesstoken'
// ```
type ActionExecutionFunction struct {
	pulumi.CustomResourceState

	// The name of the function. Valid values: `preuserinfo`, `preaccesstoken`, `presamlresponse`
	Name pulumi.StringOutput `pulumi:"name"`
	// The list of target IDs to call.
	TargetIds pulumi.StringArrayOutput `pulumi:"targetIds"`
}

// NewActionExecutionFunction registers a new resource with the given unique name, arguments, and options.
func NewActionExecutionFunction(ctx *pulumi.Context,
	name string, args *ActionExecutionFunctionArgs, opts ...pulumi.ResourceOption) (*ActionExecutionFunction, error) {
	if args == nil {
		args = &ActionExecutionFunctionArgs{}
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	var resource ActionExecutionFunction
	err := ctx.RegisterResource("zitadel:index/actionExecutionFunction:ActionExecutionFunction", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetActionExecutionFunction gets an existing ActionExecutionFunction resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetActionExecutionFunction(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ActionExecutionFunctionState, opts ...pulumi.ResourceOption) (*ActionExecutionFunction, error) {
	var resource ActionExecutionFunction
	err := ctx.ReadResource("zitadel:index/actionExecutionFunction:ActionExecutionFunction", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ActionExecutionFunction resources.
type actionExecutionFunctionState struct {
	// The name of the function. Valid values: `preuserinfo`, `preaccesstoken`, `presamlresponse`
	Name *string `pulumi:"name"`
	// The list of target IDs to call.
	TargetIds []string `pulumi:"targetIds"`
}

type ActionExecutionFunctionState struct {
	// The name of the function. Valid values: `preuserinfo`, `preaccesstoken`, `presamlresponse`
	Name pulumi.StringPtrInput
	// The list of target IDs to call.
	TargetIds pulumi.StringArrayInput
}

func (ActionExecutionFunctionState) ElementType() reflect.Type {
	return reflect.TypeOf((*actionExecutionFunctionState)(nil)).Elem()
}

type actionExecutionFunctionArgs struct {
	// The name of the function. Valid values: `preuserinfo`, `preaccesstoken`, `presamlresponse`
	Name *string `pulumi:"name"`
	// The list of target IDs to call.
	TargetIds []string `pulumi:"targetIds"`
}

// The set of arguments for constructing a ActionExecutionFunction resource.
type ActionExecutionFunctionArgs struct {
	// The name of the function. Valid values: `preuserinfo`, `preaccesstoken`, `presamlresponse`
	Name pulumi.StringPtrInput
	// The list of target IDs to call.
	TargetIds pulumi.StringArrayInput
}

func (ActionExecutionFunctionArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*actionExecutionFunctionArgs)(nil)).Elem()
}

type ActionExecutionFunctionInput interface {
	pulumi.Input

	ToActionExecutionFunctionOutput() ActionExecutionFunctionOutput
	ToActionExecutionFunctionOutputWithContext(ctx context.Context) ActionExecutionFunctionOutput
}

func (*ActionExecutionFunction) ElementType() reflect.Type {
	return reflect.TypeOf((**ActionExecutionFunction)(nil)).Elem()
}

func (i *ActionExecutionFunction) ToActionExecutionFunctionOutput() ActionExecutionFunctionOutput {
	return i.ToActionExecutionFunctionOutputWithContext(context.Background())
}

func (i *ActionExecutionFunction) ToActionExecutionFunctionOutputWithContext(ctx context.Context) ActionExecutionFunctionOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ActionExecutionFunctionOutput)
}

type ActionExecutionFunctionOutput struct{ *pulumi.OutputState }

func (ActionExecutionFunctionOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ActionExecutionFunction)(nil)).Elem()
}

func (o ActionExecutionFunctionOutput) ToActionExecutionFunctionOutput() ActionExecutionFunctionOutput {
	return o
}

func (o ActionExecutionFunctionOutput) ToActionExecutionFunctionOutputWithContext(ctx context.Context) ActionExecutionFunctionOutput {
	return o
}

// The name of the function. Valid values: `preuserinfo`, `preaccesstoken`, `presamlresponse`
func (o ActionExecutionFunctionOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *ActionExecutionFunction) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// The list of target IDs to call.
func (o ActionExecutionFunctionOutput) TargetIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *ActionExecutionFunction) pulumi.StringArrayOutput { return v.TargetIds }).(pulumi.StringArrayOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ActionExecutionFunctionInput)(nil)).Elem(), &ActionExecutionFunction{})
	pulumi.RegisterOutputType(ActionExecutionFunctionOutput{})
}
