// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package zitadel

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/truvity/pulumi-zitadel/sdk/go/zitadel/internal"
)

// Instance-level default template for the phone number verification SMS. Org-level overrides are managed by `VerifyPhoneMessageText`.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/truvity/pulumi-zitadel/sdk/go/zitadel"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := zitadel.NewDefaultVerifyPhoneMessageText(ctx, "default", &zitadel.DefaultVerifyPhoneMessageTextArgs{
//				Language: pulumi.String("en"),
//				Text:     pulumi.String("text example"),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
type DefaultVerifyPhoneMessageText struct {
	pulumi.CustomResourceState

	ButtonText pulumi.StringPtrOutput `pulumi:"buttonText"`
	FooterText pulumi.StringPtrOutput `pulumi:"footerText"`
	Greeting   pulumi.StringPtrOutput `pulumi:"greeting"`
	Language   pulumi.StringOutput    `pulumi:"language"`
	PreHeader  pulumi.StringPtrOutput `pulumi:"preHeader"`
	Subject    pulumi.StringPtrOutput `pulumi:"subject"`
	Text       pulumi.StringPtrOutput `pulumi:"text"`
	Title      pulumi.StringPtrOutput `pulumi:"title"`
}

// NewDefaultVerifyPhoneMessageText registers a new resource with the given unique name, arguments, and options.
func NewDefaultVerifyPhoneMessageText(ctx *pulumi.Context,
	name string, args *DefaultVerifyPhoneMessageTextArgs, opts ...pulumi.ResourceOption) (*DefaultVerifyPhoneMessageText, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Language == nil {
		return nil, errors.New("invalid value for required argument 'Language'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource DefaultVerifyPhoneMessageText
	err := ctx.RegisterResource("zitadel:index/defaultVerifyPhoneMessageText:DefaultVerifyPhoneMessageText", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetDefaultVerifyPhoneMessageText gets an existing DefaultVerifyPhoneMessageText resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetDefaultVerifyPhoneMessageText(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *DefaultVerifyPhoneMessageTextState, opts ...pulumi.ResourceOption) (*DefaultVerifyPhoneMessageText, error) {
	var resource DefaultVerifyPhoneMessageText
	err := ctx.ReadResource("zitadel:index/defaultVerifyPhoneMessageText:DefaultVerifyPhoneMessageText", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering DefaultVerifyPhoneMessageText resources.
type defaultVerifyPhoneMessageTextState struct {
	ButtonText *string `pulumi:"buttonText"`
	FooterText *string `pulumi:"footerText"`
	Greeting   *string `pulumi:"greeting"`
	Language   *string `pulumi:"language"`
	PreHeader  *string `pulumi:"preHeader"`
	Subject    *string `pulumi:"subject"`
	Text       *string `pulumi:"text"`
	Title      *string `pulumi:"title"`
}

type DefaultVerifyPhoneMessageTextState struct {
	ButtonText pulumi.StringPtrInput
	FooterText pulumi.StringPtrInput
	Greeting   pulumi.StringPtrInput
	Language   pulumi.StringPtrInput
	PreHeader  pulumi.StringPtrInput
	Subject    pulumi.StringPtrInput
	Text       pulumi.StringPtrInput
	Title      pulumi.StringPtrInput
}

func (DefaultVerifyPhoneMessageTextState) ElementType() reflect.Type {
	return reflect.TypeOf((*defaultVerifyPhoneMessageTextState)(nil)).Elem()
}

type defaultVerifyPhoneMessageTextArgs struct {
	ButtonText *string `pulumi:"buttonText"`
	FooterText *string `pulumi:"footerText"`
	Greeting   *string `pulumi:"greeting"`
	Language   string  `pulumi:"language"`
	PreHeader  *string `pulumi:"preHeader"`
	Subject    *string `pulumi:"subject"`
	Text       *string `pulumi:"text"`
	Title      *string `pulumi:"title"`
}

// The set of arguments for constructing a DefaultVerifyPhoneMessageText resource.
type DefaultVerifyPhoneMessageTextArgs struct {
	ButtonText pulumi.StringPtrInput
	FooterText pulumi.StringPtrInput
	Greeting   pulumi.StringPtrInput
	Language   pulumi.StringInput
	PreHeader  pulumi.StringPtrInput
	Subject    pulumi.StringPtrInput
	Text       pulumi.StringPtrInput
	Title      pulumi.StringPtrInput
}

func (DefaultVerifyPhoneMessageTextArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*defaultVerifyPhoneMessageTextArgs)(nil)).Elem()
}

type DefaultVerifyPhoneMessageTextInput interface {
	pulumi.Input

	ToDefaultVerifyPhoneMessageTextOutput() DefaultVerifyPhoneMessageTextOutput
	ToDefaultVerifyPhoneMessageTextOutputWithContext(ctx context.Context) DefaultVerifyPhoneMessageTextOutput
}

func (*DefaultVerifyPhoneMessageText) ElementType() reflect.Type {
	return reflect.TypeOf((**DefaultVerifyPhoneMessageText)(nil)).Elem()
}

func (i *DefaultVerifyPhoneMessageText) ToDefaultVerifyPhoneMessageTextOutput() DefaultVerifyPhoneMessageTextOutput {
	return i.ToDefaultVerifyPhoneMessageTextOutputWithContext(context.Background())
}

func (i *DefaultVerifyPhoneMessageText) ToDefaultVerifyPhoneMessageTextOutputWithContext(ctx context.Context) DefaultVerifyPhoneMessageTextOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DefaultVerifyPhoneMessageTextOutput)
}

type DefaultVerifyPhoneMessageTextOutput struct{ *pulumi.OutputState }

func (DefaultVerifyPhoneMessageTextOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**DefaultVerifyPhoneMessageText)(nil)).Elem()
}

func (o DefaultVerifyPhoneMessageTextOutput) ToDefaultVerifyPhoneMessageTextOutput() DefaultVerifyPhoneMessageTextOutput {
	return o
}

func (o DefaultVerifyPhoneMessageTextOutput) ToDefaultVerifyPhoneMessageTextOutputWithContext(ctx context.Context) DefaultVerifyPhoneMessageTextOutput {
	return o
}

func (o DefaultVerifyPhoneMessageTextOutput) ButtonText() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DefaultVerifyPhoneMessageText) pulumi.StringPtrOutput { return v.ButtonText }).(pulumi.StringPtrOutput)
}

func (o DefaultVerifyPhoneMessageTextOutput) FooterText() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DefaultVerifyPhoneMessageText) pulumi.StringPtrOutput { return v.FooterText }).(pulumi.StringPtrOutput)
}

func (o DefaultVerifyPhoneMessageTextOutput) Greeting() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DefaultVerifyPhoneMessageText) pulumi.StringPtrOutput { return v.Greeting }).(pulumi.StringPtrOutput)
}

func (o DefaultVerifyPhoneMessageTextOutput) Language() pulumi.StringOutput {
	return o.ApplyT(func(v *DefaultVerifyPhoneMessageText) pulumi.StringOutput { return v.Language }).(pulumi.StringOutput)
}

func (o DefaultVerifyPhoneMessageTextOutput) PreHeader() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DefaultVerifyPhoneMessageText) pulumi.StringPtrOutput { return v.PreHeader }).(pulumi.StringPtrOutput)
}

func (o DefaultVerifyPhoneMessageTextOutput) Subject() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DefaultVerifyPhoneMessageText) pulumi.StringPtrOutput { return v.Subject }).(pulumi.StringPtrOutput)
}

func (o DefaultVerifyPhoneMessageTextOutput) Text() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DefaultVerifyPhoneMessageText) pulumi.StringPtrOutput { return v.Text }).(pulumi.StringPtrOutput)
}

func (o DefaultVerifyPhoneMessageTextOutput) Title() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DefaultVerifyPhoneMessageText) pulumi.StringPtrOutput { return v.Title }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*DefaultVerifyPhoneMessageTextInput)(nil)).Elem(), &DefaultVerifyPhoneMessageText{})
	pulumi.RegisterOutputType(DefaultVerifyPhoneMessageTextOutput{})
}
