// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package zitadel

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/truvity/pulumi-zitadel/sdk/go/zitadel/internal"
)

// Resource representing the default privacy policy.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/truvity/pulumi-zitadel/sdk/go/zitadel"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := zitadel.NewDefaultPrivacyPolicy(ctx, "default", &zitadel.DefaultPrivacyPolicyArgs{
//				TosLink:      pulumi.String("https://example.com/tos"),
//				PrivacyLink:  pulumi.String("https://example.com/privacy"),
//				HelpLink:     pulumi.String("https://example.com/help"),
//				SupportEmail: pulumi.String("support@example.com"),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Import
//
// The resource can be imported using the ID format `<>`, e.g.
//
// ```sh
// $ pulumi import zitadel:index/defaultPrivacyPolicy:DefaultPrivacyPolicy imported ”
// ```
type DefaultPrivacyPolicy struct {
	pulumi.CustomResourceState

	// Link to an external resource that will be available to users in the console.
	CustomLink pulumi.StringOutput `pulumi:"customLink"`
	// The button text that would be shown in console pointing to custom link.
	CustomLinkText pulumi.StringOutput `pulumi:"customLinkText"`
	// Link to documentation to be shown in the console.
	DocsLink pulumi.StringOutput `pulumi:"docsLink"`
	// Link to the Help/Manual page.
	HelpLink pulumi.StringPtrOutput `pulumi:"helpLink"`
	// Link to the Privacy Policy.
	PrivacyLink pulumi.StringPtrOutput `pulumi:"privacyLink"`
	// Help / support email address.
	SupportEmail pulumi.StringPtrOutput `pulumi:"supportEmail"`
	// Link to the Terms of Service.
	TosLink pulumi.StringPtrOutput `pulumi:"tosLink"`
}

// NewDefaultPrivacyPolicy registers a new resource with the given unique name, arguments, and options.
func NewDefaultPrivacyPolicy(ctx *pulumi.Context,
	name string, args *DefaultPrivacyPolicyArgs, opts ...pulumi.ResourceOption) (*DefaultPrivacyPolicy, error) {
	if args == nil {
		args = &DefaultPrivacyPolicyArgs{}
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	var resource DefaultPrivacyPolicy
	err := ctx.RegisterResource("zitadel:index/defaultPrivacyPolicy:DefaultPrivacyPolicy", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetDefaultPrivacyPolicy gets an existing DefaultPrivacyPolicy resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetDefaultPrivacyPolicy(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *DefaultPrivacyPolicyState, opts ...pulumi.ResourceOption) (*DefaultPrivacyPolicy, error) {
	var resource DefaultPrivacyPolicy
	err := ctx.ReadResource("zitadel:index/defaultPrivacyPolicy:DefaultPrivacyPolicy", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering DefaultPrivacyPolicy resources.
type defaultPrivacyPolicyState struct {
	// Link to an external resource that will be available to users in the console.
	CustomLink *string `pulumi:"customLink"`
	// The button text that would be shown in console pointing to custom link.
	CustomLinkText *string `pulumi:"customLinkText"`
	// Link to documentation to be shown in the console.
	DocsLink *string `pulumi:"docsLink"`
	// Link to the Help/Manual page.
	HelpLink *string `pulumi:"helpLink"`
	// Link to the Privacy Policy.
	PrivacyLink *string `pulumi:"privacyLink"`
	// Help / support email address.
	SupportEmail *string `pulumi:"supportEmail"`
	// Link to the Terms of Service.
	TosLink *string `pulumi:"tosLink"`
}

type DefaultPrivacyPolicyState struct {
	// Link to an external resource that will be available to users in the console.
	CustomLink pulumi.StringPtrInput
	// The button text that would be shown in console pointing to custom link.
	CustomLinkText pulumi.StringPtrInput
	// Link to documentation to be shown in the console.
	DocsLink pulumi.StringPtrInput
	// Link to the Help/Manual page.
	HelpLink pulumi.StringPtrInput
	// Link to the Privacy Policy.
	PrivacyLink pulumi.StringPtrInput
	// Help / support email address.
	SupportEmail pulumi.StringPtrInput
	// Link to the Terms of Service.
	TosLink pulumi.StringPtrInput
}

func (DefaultPrivacyPolicyState) ElementType() reflect.Type {
	return reflect.TypeOf((*defaultPrivacyPolicyState)(nil)).Elem()
}

type defaultPrivacyPolicyArgs struct {
	// Link to an external resource that will be available to users in the console.
	CustomLink *string `pulumi:"customLink"`
	// The button text that would be shown in console pointing to custom link.
	CustomLinkText *string `pulumi:"customLinkText"`
	// Link to documentation to be shown in the console.
	DocsLink *string `pulumi:"docsLink"`
	// Link to the Help/Manual page.
	HelpLink *string `pulumi:"helpLink"`
	// Link to the Privacy Policy.
	PrivacyLink *string `pulumi:"privacyLink"`
	// Help / support email address.
	SupportEmail *string `pulumi:"supportEmail"`
	// Link to the Terms of Service.
	TosLink *string `pulumi:"tosLink"`
}

// The set of arguments for constructing a DefaultPrivacyPolicy resource.
type DefaultPrivacyPolicyArgs struct {
	// Link to an external resource that will be available to users in the console.
	CustomLink pulumi.StringPtrInput
	// The button text that would be shown in console pointing to custom link.
	CustomLinkText pulumi.StringPtrInput
	// Link to documentation to be shown in the console.
	DocsLink pulumi.StringPtrInput
	// Link to the Help/Manual page.
	HelpLink pulumi.StringPtrInput
	// Link to the Privacy Policy.
	PrivacyLink pulumi.StringPtrInput
	// Help / support email address.
	SupportEmail pulumi.StringPtrInput
	// Link to the Terms of Service.
	TosLink pulumi.StringPtrInput
}

func (DefaultPrivacyPolicyArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*defaultPrivacyPolicyArgs)(nil)).Elem()
}

type DefaultPrivacyPolicyInput interface {
	pulumi.Input

	ToDefaultPrivacyPolicyOutput() DefaultPrivacyPolicyOutput
	ToDefaultPrivacyPolicyOutputWithContext(ctx context.Context) DefaultPrivacyPolicyOutput
}

func (*DefaultPrivacyPolicy) ElementType() reflect.Type {
	return reflect.TypeOf((**DefaultPrivacyPolicy)(nil)).Elem()
}

func (i *DefaultPrivacyPolicy) ToDefaultPrivacyPolicyOutput() DefaultPrivacyPolicyOutput {
	return i.ToDefaultPrivacyPolicyOutputWithContext(context.Background())
}

func (i *DefaultPrivacyPolicy) ToDefaultPrivacyPolicyOutputWithContext(ctx context.Context) DefaultPrivacyPolicyOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DefaultPrivacyPolicyOutput)
}

type DefaultPrivacyPolicyOutput struct{ *pulumi.OutputState }

func (DefaultPrivacyPolicyOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**DefaultPrivacyPolicy)(nil)).Elem()
}

func (o DefaultPrivacyPolicyOutput) ToDefaultPrivacyPolicyOutput() DefaultPrivacyPolicyOutput {
	return o
}

func (o DefaultPrivacyPolicyOutput) ToDefaultPrivacyPolicyOutputWithContext(ctx context.Context) DefaultPrivacyPolicyOutput {
	return o
}

// Link to an external resource that will be available to users in the console.
func (o DefaultPrivacyPolicyOutput) CustomLink() pulumi.StringOutput {
	return o.ApplyT(func(v *DefaultPrivacyPolicy) pulumi.StringOutput { return v.CustomLink }).(pulumi.StringOutput)
}

// The button text that would be shown in console pointing to custom link.
func (o DefaultPrivacyPolicyOutput) CustomLinkText() pulumi.StringOutput {
	return o.ApplyT(func(v *DefaultPrivacyPolicy) pulumi.StringOutput { return v.CustomLinkText }).(pulumi.StringOutput)
}

// Link to documentation to be shown in the console.
func (o DefaultPrivacyPolicyOutput) DocsLink() pulumi.StringOutput {
	return o.ApplyT(func(v *DefaultPrivacyPolicy) pulumi.StringOutput { return v.DocsLink }).(pulumi.StringOutput)
}

// Link to the Help/Manual page.
func (o DefaultPrivacyPolicyOutput) HelpLink() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DefaultPrivacyPolicy) pulumi.StringPtrOutput { return v.HelpLink }).(pulumi.StringPtrOutput)
}

// Link to the Privacy Policy.
func (o DefaultPrivacyPolicyOutput) PrivacyLink() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DefaultPrivacyPolicy) pulumi.StringPtrOutput { return v.PrivacyLink }).(pulumi.StringPtrOutput)
}

// Help / support email address.
func (o DefaultPrivacyPolicyOutput) SupportEmail() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DefaultPrivacyPolicy) pulumi.StringPtrOutput { return v.SupportEmail }).(pulumi.StringPtrOutput)
}

// Link to the Terms of Service.
func (o DefaultPrivacyPolicyOutput) TosLink() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DefaultPrivacyPolicy) pulumi.StringPtrOutput { return v.TosLink }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*DefaultPrivacyPolicyInput)(nil)).Elem(), &DefaultPrivacyPolicy{})
	pulumi.RegisterOutputType(DefaultPrivacyPolicyOutput{})
}
