// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package zitadel

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/truvity/pulumi-zitadel/sdk/go/zitadel/internal"
)

// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/truvity/pulumi-zitadel/sdk/go/zitadel"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := zitadel.NewDefaultVerifySmsOtpMessageText(ctx, "default", &zitadel.DefaultVerifySmsOtpMessageTextArgs{
//				Language: pulumi.String("en"),
//				Text:     pulumi.String("text example"),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
type DefaultVerifySmsOtpMessageText struct {
	pulumi.CustomResourceState

	ButtonText pulumi.StringPtrOutput `pulumi:"buttonText"`
	FooterText pulumi.StringPtrOutput `pulumi:"footerText"`
	Greeting   pulumi.StringPtrOutput `pulumi:"greeting"`
	Language   pulumi.StringOutput    `pulumi:"language"`
	PreHeader  pulumi.StringPtrOutput `pulumi:"preHeader"`
	Subject    pulumi.StringPtrOutput `pulumi:"subject"`
	Text       pulumi.StringPtrOutput `pulumi:"text"`
	Title      pulumi.StringPtrOutput `pulumi:"title"`
}

// NewDefaultVerifySmsOtpMessageText registers a new resource with the given unique name, arguments, and options.
func NewDefaultVerifySmsOtpMessageText(ctx *pulumi.Context,
	name string, args *DefaultVerifySmsOtpMessageTextArgs, opts ...pulumi.ResourceOption) (*DefaultVerifySmsOtpMessageText, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Language == nil {
		return nil, errors.New("invalid value for required argument 'Language'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource DefaultVerifySmsOtpMessageText
	err := ctx.RegisterResource("zitadel:index/defaultVerifySmsOtpMessageText:DefaultVerifySmsOtpMessageText", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetDefaultVerifySmsOtpMessageText gets an existing DefaultVerifySmsOtpMessageText resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetDefaultVerifySmsOtpMessageText(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *DefaultVerifySmsOtpMessageTextState, opts ...pulumi.ResourceOption) (*DefaultVerifySmsOtpMessageText, error) {
	var resource DefaultVerifySmsOtpMessageText
	err := ctx.ReadResource("zitadel:index/defaultVerifySmsOtpMessageText:DefaultVerifySmsOtpMessageText", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering DefaultVerifySmsOtpMessageText resources.
type defaultVerifySmsOtpMessageTextState struct {
	ButtonText *string `pulumi:"buttonText"`
	FooterText *string `pulumi:"footerText"`
	Greeting   *string `pulumi:"greeting"`
	Language   *string `pulumi:"language"`
	PreHeader  *string `pulumi:"preHeader"`
	Subject    *string `pulumi:"subject"`
	Text       *string `pulumi:"text"`
	Title      *string `pulumi:"title"`
}

type DefaultVerifySmsOtpMessageTextState struct {
	ButtonText pulumi.StringPtrInput
	FooterText pulumi.StringPtrInput
	Greeting   pulumi.StringPtrInput
	Language   pulumi.StringPtrInput
	PreHeader  pulumi.StringPtrInput
	Subject    pulumi.StringPtrInput
	Text       pulumi.StringPtrInput
	Title      pulumi.StringPtrInput
}

func (DefaultVerifySmsOtpMessageTextState) ElementType() reflect.Type {
	return reflect.TypeOf((*defaultVerifySmsOtpMessageTextState)(nil)).Elem()
}

type defaultVerifySmsOtpMessageTextArgs struct {
	ButtonText *string `pulumi:"buttonText"`
	FooterText *string `pulumi:"footerText"`
	Greeting   *string `pulumi:"greeting"`
	Language   string  `pulumi:"language"`
	PreHeader  *string `pulumi:"preHeader"`
	Subject    *string `pulumi:"subject"`
	Text       *string `pulumi:"text"`
	Title      *string `pulumi:"title"`
}

// The set of arguments for constructing a DefaultVerifySmsOtpMessageText resource.
type DefaultVerifySmsOtpMessageTextArgs struct {
	ButtonText pulumi.StringPtrInput
	FooterText pulumi.StringPtrInput
	Greeting   pulumi.StringPtrInput
	Language   pulumi.StringInput
	PreHeader  pulumi.StringPtrInput
	Subject    pulumi.StringPtrInput
	Text       pulumi.StringPtrInput
	Title      pulumi.StringPtrInput
}

func (DefaultVerifySmsOtpMessageTextArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*defaultVerifySmsOtpMessageTextArgs)(nil)).Elem()
}

type DefaultVerifySmsOtpMessageTextInput interface {
	pulumi.Input

	ToDefaultVerifySmsOtpMessageTextOutput() DefaultVerifySmsOtpMessageTextOutput
	ToDefaultVerifySmsOtpMessageTextOutputWithContext(ctx context.Context) DefaultVerifySmsOtpMessageTextOutput
}

func (*DefaultVerifySmsOtpMessageText) ElementType() reflect.Type {
	return reflect.TypeOf((**DefaultVerifySmsOtpMessageText)(nil)).Elem()
}

func (i *DefaultVerifySmsOtpMessageText) ToDefaultVerifySmsOtpMessageTextOutput() DefaultVerifySmsOtpMessageTextOutput {
	return i.ToDefaultVerifySmsOtpMessageTextOutputWithContext(context.Background())
}

func (i *DefaultVerifySmsOtpMessageText) ToDefaultVerifySmsOtpMessageTextOutputWithContext(ctx context.Context) DefaultVerifySmsOtpMessageTextOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DefaultVerifySmsOtpMessageTextOutput)
}

type DefaultVerifySmsOtpMessageTextOutput struct{ *pulumi.OutputState }

func (DefaultVerifySmsOtpMessageTextOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**DefaultVerifySmsOtpMessageText)(nil)).Elem()
}

func (o DefaultVerifySmsOtpMessageTextOutput) ToDefaultVerifySmsOtpMessageTextOutput() DefaultVerifySmsOtpMessageTextOutput {
	return o
}

func (o DefaultVerifySmsOtpMessageTextOutput) ToDefaultVerifySmsOtpMessageTextOutputWithContext(ctx context.Context) DefaultVerifySmsOtpMessageTextOutput {
	return o
}

func (o DefaultVerifySmsOtpMessageTextOutput) ButtonText() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DefaultVerifySmsOtpMessageText) pulumi.StringPtrOutput { return v.ButtonText }).(pulumi.StringPtrOutput)
}

func (o DefaultVerifySmsOtpMessageTextOutput) FooterText() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DefaultVerifySmsOtpMessageText) pulumi.StringPtrOutput { return v.FooterText }).(pulumi.StringPtrOutput)
}

func (o DefaultVerifySmsOtpMessageTextOutput) Greeting() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DefaultVerifySmsOtpMessageText) pulumi.StringPtrOutput { return v.Greeting }).(pulumi.StringPtrOutput)
}

func (o DefaultVerifySmsOtpMessageTextOutput) Language() pulumi.StringOutput {
	return o.ApplyT(func(v *DefaultVerifySmsOtpMessageText) pulumi.StringOutput { return v.Language }).(pulumi.StringOutput)
}

func (o DefaultVerifySmsOtpMessageTextOutput) PreHeader() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DefaultVerifySmsOtpMessageText) pulumi.StringPtrOutput { return v.PreHeader }).(pulumi.StringPtrOutput)
}

func (o DefaultVerifySmsOtpMessageTextOutput) Subject() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DefaultVerifySmsOtpMessageText) pulumi.StringPtrOutput { return v.Subject }).(pulumi.StringPtrOutput)
}

func (o DefaultVerifySmsOtpMessageTextOutput) Text() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DefaultVerifySmsOtpMessageText) pulumi.StringPtrOutput { return v.Text }).(pulumi.StringPtrOutput)
}

func (o DefaultVerifySmsOtpMessageTextOutput) Title() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DefaultVerifySmsOtpMessageText) pulumi.StringPtrOutput { return v.Title }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*DefaultVerifySmsOtpMessageTextInput)(nil)).Elem(), &DefaultVerifySmsOtpMessageText{})
	pulumi.RegisterOutputType(DefaultVerifySmsOtpMessageTextOutput{})
}
