// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package zitadel

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/truvity/pulumi-zitadel/sdk/go/zitadel/internal"
)

// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/truvity/pulumi-zitadel/sdk/go/zitadel"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := zitadel.NewDefaultPasswordChangeMessageText(ctx, "default", &zitadel.DefaultPasswordChangeMessageTextArgs{
//				Language:   pulumi.String("en"),
//				Title:      pulumi.String("title example"),
//				PreHeader:  pulumi.String("pre_header example"),
//				Subject:    pulumi.String("subject example"),
//				Greeting:   pulumi.String("greeting example"),
//				Text:       pulumi.String("text example"),
//				ButtonText: pulumi.String("button_text example"),
//				FooterText: pulumi.String("footer_text example"),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
type DefaultPasswordChangeMessageText struct {
	pulumi.CustomResourceState

	ButtonText pulumi.StringPtrOutput `pulumi:"buttonText"`
	FooterText pulumi.StringPtrOutput `pulumi:"footerText"`
	Greeting   pulumi.StringPtrOutput `pulumi:"greeting"`
	Language   pulumi.StringOutput    `pulumi:"language"`
	PreHeader  pulumi.StringPtrOutput `pulumi:"preHeader"`
	Subject    pulumi.StringPtrOutput `pulumi:"subject"`
	Text       pulumi.StringPtrOutput `pulumi:"text"`
	Title      pulumi.StringPtrOutput `pulumi:"title"`
}

// NewDefaultPasswordChangeMessageText registers a new resource with the given unique name, arguments, and options.
func NewDefaultPasswordChangeMessageText(ctx *pulumi.Context,
	name string, args *DefaultPasswordChangeMessageTextArgs, opts ...pulumi.ResourceOption) (*DefaultPasswordChangeMessageText, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Language == nil {
		return nil, errors.New("invalid value for required argument 'Language'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource DefaultPasswordChangeMessageText
	err := ctx.RegisterResource("zitadel:index/defaultPasswordChangeMessageText:DefaultPasswordChangeMessageText", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetDefaultPasswordChangeMessageText gets an existing DefaultPasswordChangeMessageText resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetDefaultPasswordChangeMessageText(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *DefaultPasswordChangeMessageTextState, opts ...pulumi.ResourceOption) (*DefaultPasswordChangeMessageText, error) {
	var resource DefaultPasswordChangeMessageText
	err := ctx.ReadResource("zitadel:index/defaultPasswordChangeMessageText:DefaultPasswordChangeMessageText", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering DefaultPasswordChangeMessageText resources.
type defaultPasswordChangeMessageTextState struct {
	ButtonText *string `pulumi:"buttonText"`
	FooterText *string `pulumi:"footerText"`
	Greeting   *string `pulumi:"greeting"`
	Language   *string `pulumi:"language"`
	PreHeader  *string `pulumi:"preHeader"`
	Subject    *string `pulumi:"subject"`
	Text       *string `pulumi:"text"`
	Title      *string `pulumi:"title"`
}

type DefaultPasswordChangeMessageTextState struct {
	ButtonText pulumi.StringPtrInput
	FooterText pulumi.StringPtrInput
	Greeting   pulumi.StringPtrInput
	Language   pulumi.StringPtrInput
	PreHeader  pulumi.StringPtrInput
	Subject    pulumi.StringPtrInput
	Text       pulumi.StringPtrInput
	Title      pulumi.StringPtrInput
}

func (DefaultPasswordChangeMessageTextState) ElementType() reflect.Type {
	return reflect.TypeOf((*defaultPasswordChangeMessageTextState)(nil)).Elem()
}

type defaultPasswordChangeMessageTextArgs struct {
	ButtonText *string `pulumi:"buttonText"`
	FooterText *string `pulumi:"footerText"`
	Greeting   *string `pulumi:"greeting"`
	Language   string  `pulumi:"language"`
	PreHeader  *string `pulumi:"preHeader"`
	Subject    *string `pulumi:"subject"`
	Text       *string `pulumi:"text"`
	Title      *string `pulumi:"title"`
}

// The set of arguments for constructing a DefaultPasswordChangeMessageText resource.
type DefaultPasswordChangeMessageTextArgs struct {
	ButtonText pulumi.StringPtrInput
	FooterText pulumi.StringPtrInput
	Greeting   pulumi.StringPtrInput
	Language   pulumi.StringInput
	PreHeader  pulumi.StringPtrInput
	Subject    pulumi.StringPtrInput
	Text       pulumi.StringPtrInput
	Title      pulumi.StringPtrInput
}

func (DefaultPasswordChangeMessageTextArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*defaultPasswordChangeMessageTextArgs)(nil)).Elem()
}

type DefaultPasswordChangeMessageTextInput interface {
	pulumi.Input

	ToDefaultPasswordChangeMessageTextOutput() DefaultPasswordChangeMessageTextOutput
	ToDefaultPasswordChangeMessageTextOutputWithContext(ctx context.Context) DefaultPasswordChangeMessageTextOutput
}

func (*DefaultPasswordChangeMessageText) ElementType() reflect.Type {
	return reflect.TypeOf((**DefaultPasswordChangeMessageText)(nil)).Elem()
}

func (i *DefaultPasswordChangeMessageText) ToDefaultPasswordChangeMessageTextOutput() DefaultPasswordChangeMessageTextOutput {
	return i.ToDefaultPasswordChangeMessageTextOutputWithContext(context.Background())
}

func (i *DefaultPasswordChangeMessageText) ToDefaultPasswordChangeMessageTextOutputWithContext(ctx context.Context) DefaultPasswordChangeMessageTextOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DefaultPasswordChangeMessageTextOutput)
}

type DefaultPasswordChangeMessageTextOutput struct{ *pulumi.OutputState }

func (DefaultPasswordChangeMessageTextOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**DefaultPasswordChangeMessageText)(nil)).Elem()
}

func (o DefaultPasswordChangeMessageTextOutput) ToDefaultPasswordChangeMessageTextOutput() DefaultPasswordChangeMessageTextOutput {
	return o
}

func (o DefaultPasswordChangeMessageTextOutput) ToDefaultPasswordChangeMessageTextOutputWithContext(ctx context.Context) DefaultPasswordChangeMessageTextOutput {
	return o
}

func (o DefaultPasswordChangeMessageTextOutput) ButtonText() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DefaultPasswordChangeMessageText) pulumi.StringPtrOutput { return v.ButtonText }).(pulumi.StringPtrOutput)
}

func (o DefaultPasswordChangeMessageTextOutput) FooterText() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DefaultPasswordChangeMessageText) pulumi.StringPtrOutput { return v.FooterText }).(pulumi.StringPtrOutput)
}

func (o DefaultPasswordChangeMessageTextOutput) Greeting() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DefaultPasswordChangeMessageText) pulumi.StringPtrOutput { return v.Greeting }).(pulumi.StringPtrOutput)
}

func (o DefaultPasswordChangeMessageTextOutput) Language() pulumi.StringOutput {
	return o.ApplyT(func(v *DefaultPasswordChangeMessageText) pulumi.StringOutput { return v.Language }).(pulumi.StringOutput)
}

func (o DefaultPasswordChangeMessageTextOutput) PreHeader() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DefaultPasswordChangeMessageText) pulumi.StringPtrOutput { return v.PreHeader }).(pulumi.StringPtrOutput)
}

func (o DefaultPasswordChangeMessageTextOutput) Subject() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DefaultPasswordChangeMessageText) pulumi.StringPtrOutput { return v.Subject }).(pulumi.StringPtrOutput)
}

func (o DefaultPasswordChangeMessageTextOutput) Text() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DefaultPasswordChangeMessageText) pulumi.StringPtrOutput { return v.Text }).(pulumi.StringPtrOutput)
}

func (o DefaultPasswordChangeMessageTextOutput) Title() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DefaultPasswordChangeMessageText) pulumi.StringPtrOutput { return v.Title }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*DefaultPasswordChangeMessageTextInput)(nil)).Elem(), &DefaultPasswordChangeMessageText{})
	pulumi.RegisterOutputType(DefaultPasswordChangeMessageTextOutput{})
}
