// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package zitadel

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/truvity/pulumi-zitadel/sdk/go/zitadel/internal"
)

// Instance-level default template for the email address verification email. Org-level overrides are managed by `VerifyEmailMessageText`.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/truvity/pulumi-zitadel/sdk/go/zitadel"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := zitadel.NewDefaultVerifyEmailMessageText(ctx, "default", &zitadel.DefaultVerifyEmailMessageTextArgs{
//				Language:   pulumi.String("en"),
//				Title:      pulumi.String("title example"),
//				PreHeader:  pulumi.String("pre_header example"),
//				Subject:    pulumi.String("subject example"),
//				Greeting:   pulumi.String("greeting example"),
//				Text:       pulumi.String("text example"),
//				ButtonText: pulumi.String("button_text example"),
//				FooterText: pulumi.String("footer_text example"),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
type DefaultVerifyEmailMessageText struct {
	pulumi.CustomResourceState

	ButtonText pulumi.StringPtrOutput `pulumi:"buttonText"`
	FooterText pulumi.StringPtrOutput `pulumi:"footerText"`
	Greeting   pulumi.StringPtrOutput `pulumi:"greeting"`
	Language   pulumi.StringOutput    `pulumi:"language"`
	PreHeader  pulumi.StringPtrOutput `pulumi:"preHeader"`
	Subject    pulumi.StringPtrOutput `pulumi:"subject"`
	Text       pulumi.StringPtrOutput `pulumi:"text"`
	Title      pulumi.StringPtrOutput `pulumi:"title"`
}

// NewDefaultVerifyEmailMessageText registers a new resource with the given unique name, arguments, and options.
func NewDefaultVerifyEmailMessageText(ctx *pulumi.Context,
	name string, args *DefaultVerifyEmailMessageTextArgs, opts ...pulumi.ResourceOption) (*DefaultVerifyEmailMessageText, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Language == nil {
		return nil, errors.New("invalid value for required argument 'Language'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource DefaultVerifyEmailMessageText
	err := ctx.RegisterResource("zitadel:index/defaultVerifyEmailMessageText:DefaultVerifyEmailMessageText", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetDefaultVerifyEmailMessageText gets an existing DefaultVerifyEmailMessageText resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetDefaultVerifyEmailMessageText(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *DefaultVerifyEmailMessageTextState, opts ...pulumi.ResourceOption) (*DefaultVerifyEmailMessageText, error) {
	var resource DefaultVerifyEmailMessageText
	err := ctx.ReadResource("zitadel:index/defaultVerifyEmailMessageText:DefaultVerifyEmailMessageText", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering DefaultVerifyEmailMessageText resources.
type defaultVerifyEmailMessageTextState struct {
	ButtonText *string `pulumi:"buttonText"`
	FooterText *string `pulumi:"footerText"`
	Greeting   *string `pulumi:"greeting"`
	Language   *string `pulumi:"language"`
	PreHeader  *string `pulumi:"preHeader"`
	Subject    *string `pulumi:"subject"`
	Text       *string `pulumi:"text"`
	Title      *string `pulumi:"title"`
}

type DefaultVerifyEmailMessageTextState struct {
	ButtonText pulumi.StringPtrInput
	FooterText pulumi.StringPtrInput
	Greeting   pulumi.StringPtrInput
	Language   pulumi.StringPtrInput
	PreHeader  pulumi.StringPtrInput
	Subject    pulumi.StringPtrInput
	Text       pulumi.StringPtrInput
	Title      pulumi.StringPtrInput
}

func (DefaultVerifyEmailMessageTextState) ElementType() reflect.Type {
	return reflect.TypeOf((*defaultVerifyEmailMessageTextState)(nil)).Elem()
}

type defaultVerifyEmailMessageTextArgs struct {
	ButtonText *string `pulumi:"buttonText"`
	FooterText *string `pulumi:"footerText"`
	Greeting   *string `pulumi:"greeting"`
	Language   string  `pulumi:"language"`
	PreHeader  *string `pulumi:"preHeader"`
	Subject    *string `pulumi:"subject"`
	Text       *string `pulumi:"text"`
	Title      *string `pulumi:"title"`
}

// The set of arguments for constructing a DefaultVerifyEmailMessageText resource.
type DefaultVerifyEmailMessageTextArgs struct {
	ButtonText pulumi.StringPtrInput
	FooterText pulumi.StringPtrInput
	Greeting   pulumi.StringPtrInput
	Language   pulumi.StringInput
	PreHeader  pulumi.StringPtrInput
	Subject    pulumi.StringPtrInput
	Text       pulumi.StringPtrInput
	Title      pulumi.StringPtrInput
}

func (DefaultVerifyEmailMessageTextArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*defaultVerifyEmailMessageTextArgs)(nil)).Elem()
}

type DefaultVerifyEmailMessageTextInput interface {
	pulumi.Input

	ToDefaultVerifyEmailMessageTextOutput() DefaultVerifyEmailMessageTextOutput
	ToDefaultVerifyEmailMessageTextOutputWithContext(ctx context.Context) DefaultVerifyEmailMessageTextOutput
}

func (*DefaultVerifyEmailMessageText) ElementType() reflect.Type {
	return reflect.TypeOf((**DefaultVerifyEmailMessageText)(nil)).Elem()
}

func (i *DefaultVerifyEmailMessageText) ToDefaultVerifyEmailMessageTextOutput() DefaultVerifyEmailMessageTextOutput {
	return i.ToDefaultVerifyEmailMessageTextOutputWithContext(context.Background())
}

func (i *DefaultVerifyEmailMessageText) ToDefaultVerifyEmailMessageTextOutputWithContext(ctx context.Context) DefaultVerifyEmailMessageTextOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DefaultVerifyEmailMessageTextOutput)
}

type DefaultVerifyEmailMessageTextOutput struct{ *pulumi.OutputState }

func (DefaultVerifyEmailMessageTextOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**DefaultVerifyEmailMessageText)(nil)).Elem()
}

func (o DefaultVerifyEmailMessageTextOutput) ToDefaultVerifyEmailMessageTextOutput() DefaultVerifyEmailMessageTextOutput {
	return o
}

func (o DefaultVerifyEmailMessageTextOutput) ToDefaultVerifyEmailMessageTextOutputWithContext(ctx context.Context) DefaultVerifyEmailMessageTextOutput {
	return o
}

func (o DefaultVerifyEmailMessageTextOutput) ButtonText() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DefaultVerifyEmailMessageText) pulumi.StringPtrOutput { return v.ButtonText }).(pulumi.StringPtrOutput)
}

func (o DefaultVerifyEmailMessageTextOutput) FooterText() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DefaultVerifyEmailMessageText) pulumi.StringPtrOutput { return v.FooterText }).(pulumi.StringPtrOutput)
}

func (o DefaultVerifyEmailMessageTextOutput) Greeting() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DefaultVerifyEmailMessageText) pulumi.StringPtrOutput { return v.Greeting }).(pulumi.StringPtrOutput)
}

func (o DefaultVerifyEmailMessageTextOutput) Language() pulumi.StringOutput {
	return o.ApplyT(func(v *DefaultVerifyEmailMessageText) pulumi.StringOutput { return v.Language }).(pulumi.StringOutput)
}

func (o DefaultVerifyEmailMessageTextOutput) PreHeader() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DefaultVerifyEmailMessageText) pulumi.StringPtrOutput { return v.PreHeader }).(pulumi.StringPtrOutput)
}

func (o DefaultVerifyEmailMessageTextOutput) Subject() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DefaultVerifyEmailMessageText) pulumi.StringPtrOutput { return v.Subject }).(pulumi.StringPtrOutput)
}

func (o DefaultVerifyEmailMessageTextOutput) Text() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DefaultVerifyEmailMessageText) pulumi.StringPtrOutput { return v.Text }).(pulumi.StringPtrOutput)
}

func (o DefaultVerifyEmailMessageTextOutput) Title() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DefaultVerifyEmailMessageText) pulumi.StringPtrOutput { return v.Title }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*DefaultVerifyEmailMessageTextInput)(nil)).Elem(), &DefaultVerifyEmailMessageText{})
	pulumi.RegisterOutputType(DefaultVerifyEmailMessageTextOutput{})
}
