// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package zitadel

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/truvity/pulumi-zitadel/sdk/go/zitadel/internal"
)

// Instance-level default template for the password reset notification email. Org-level overrides are managed by `PasswordResetMessageText`.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/truvity/pulumi-zitadel/sdk/go/zitadel"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := zitadel.NewDefaultPasswordResetMessageText(ctx, "default", &zitadel.DefaultPasswordResetMessageTextArgs{
//				Language:   pulumi.String("en"),
//				Title:      pulumi.String("title example"),
//				PreHeader:  pulumi.String("pre_header example"),
//				Subject:    pulumi.String("subject example"),
//				Greeting:   pulumi.String("greeting example"),
//				Text:       pulumi.String("text example"),
//				ButtonText: pulumi.String("button_text example"),
//				FooterText: pulumi.String("footer_text example"),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
type DefaultPasswordResetMessageText struct {
	pulumi.CustomResourceState

	ButtonText pulumi.StringPtrOutput `pulumi:"buttonText"`
	FooterText pulumi.StringPtrOutput `pulumi:"footerText"`
	Greeting   pulumi.StringPtrOutput `pulumi:"greeting"`
	Language   pulumi.StringOutput    `pulumi:"language"`
	PreHeader  pulumi.StringPtrOutput `pulumi:"preHeader"`
	Subject    pulumi.StringPtrOutput `pulumi:"subject"`
	Text       pulumi.StringPtrOutput `pulumi:"text"`
	Title      pulumi.StringPtrOutput `pulumi:"title"`
}

// NewDefaultPasswordResetMessageText registers a new resource with the given unique name, arguments, and options.
func NewDefaultPasswordResetMessageText(ctx *pulumi.Context,
	name string, args *DefaultPasswordResetMessageTextArgs, opts ...pulumi.ResourceOption) (*DefaultPasswordResetMessageText, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Language == nil {
		return nil, errors.New("invalid value for required argument 'Language'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource DefaultPasswordResetMessageText
	err := ctx.RegisterResource("zitadel:index/defaultPasswordResetMessageText:DefaultPasswordResetMessageText", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetDefaultPasswordResetMessageText gets an existing DefaultPasswordResetMessageText resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetDefaultPasswordResetMessageText(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *DefaultPasswordResetMessageTextState, opts ...pulumi.ResourceOption) (*DefaultPasswordResetMessageText, error) {
	var resource DefaultPasswordResetMessageText
	err := ctx.ReadResource("zitadel:index/defaultPasswordResetMessageText:DefaultPasswordResetMessageText", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering DefaultPasswordResetMessageText resources.
type defaultPasswordResetMessageTextState struct {
	ButtonText *string `pulumi:"buttonText"`
	FooterText *string `pulumi:"footerText"`
	Greeting   *string `pulumi:"greeting"`
	Language   *string `pulumi:"language"`
	PreHeader  *string `pulumi:"preHeader"`
	Subject    *string `pulumi:"subject"`
	Text       *string `pulumi:"text"`
	Title      *string `pulumi:"title"`
}

type DefaultPasswordResetMessageTextState struct {
	ButtonText pulumi.StringPtrInput
	FooterText pulumi.StringPtrInput
	Greeting   pulumi.StringPtrInput
	Language   pulumi.StringPtrInput
	PreHeader  pulumi.StringPtrInput
	Subject    pulumi.StringPtrInput
	Text       pulumi.StringPtrInput
	Title      pulumi.StringPtrInput
}

func (DefaultPasswordResetMessageTextState) ElementType() reflect.Type {
	return reflect.TypeOf((*defaultPasswordResetMessageTextState)(nil)).Elem()
}

type defaultPasswordResetMessageTextArgs struct {
	ButtonText *string `pulumi:"buttonText"`
	FooterText *string `pulumi:"footerText"`
	Greeting   *string `pulumi:"greeting"`
	Language   string  `pulumi:"language"`
	PreHeader  *string `pulumi:"preHeader"`
	Subject    *string `pulumi:"subject"`
	Text       *string `pulumi:"text"`
	Title      *string `pulumi:"title"`
}

// The set of arguments for constructing a DefaultPasswordResetMessageText resource.
type DefaultPasswordResetMessageTextArgs struct {
	ButtonText pulumi.StringPtrInput
	FooterText pulumi.StringPtrInput
	Greeting   pulumi.StringPtrInput
	Language   pulumi.StringInput
	PreHeader  pulumi.StringPtrInput
	Subject    pulumi.StringPtrInput
	Text       pulumi.StringPtrInput
	Title      pulumi.StringPtrInput
}

func (DefaultPasswordResetMessageTextArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*defaultPasswordResetMessageTextArgs)(nil)).Elem()
}

type DefaultPasswordResetMessageTextInput interface {
	pulumi.Input

	ToDefaultPasswordResetMessageTextOutput() DefaultPasswordResetMessageTextOutput
	ToDefaultPasswordResetMessageTextOutputWithContext(ctx context.Context) DefaultPasswordResetMessageTextOutput
}

func (*DefaultPasswordResetMessageText) ElementType() reflect.Type {
	return reflect.TypeOf((**DefaultPasswordResetMessageText)(nil)).Elem()
}

func (i *DefaultPasswordResetMessageText) ToDefaultPasswordResetMessageTextOutput() DefaultPasswordResetMessageTextOutput {
	return i.ToDefaultPasswordResetMessageTextOutputWithContext(context.Background())
}

func (i *DefaultPasswordResetMessageText) ToDefaultPasswordResetMessageTextOutputWithContext(ctx context.Context) DefaultPasswordResetMessageTextOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DefaultPasswordResetMessageTextOutput)
}

type DefaultPasswordResetMessageTextOutput struct{ *pulumi.OutputState }

func (DefaultPasswordResetMessageTextOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**DefaultPasswordResetMessageText)(nil)).Elem()
}

func (o DefaultPasswordResetMessageTextOutput) ToDefaultPasswordResetMessageTextOutput() DefaultPasswordResetMessageTextOutput {
	return o
}

func (o DefaultPasswordResetMessageTextOutput) ToDefaultPasswordResetMessageTextOutputWithContext(ctx context.Context) DefaultPasswordResetMessageTextOutput {
	return o
}

func (o DefaultPasswordResetMessageTextOutput) ButtonText() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DefaultPasswordResetMessageText) pulumi.StringPtrOutput { return v.ButtonText }).(pulumi.StringPtrOutput)
}

func (o DefaultPasswordResetMessageTextOutput) FooterText() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DefaultPasswordResetMessageText) pulumi.StringPtrOutput { return v.FooterText }).(pulumi.StringPtrOutput)
}

func (o DefaultPasswordResetMessageTextOutput) Greeting() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DefaultPasswordResetMessageText) pulumi.StringPtrOutput { return v.Greeting }).(pulumi.StringPtrOutput)
}

func (o DefaultPasswordResetMessageTextOutput) Language() pulumi.StringOutput {
	return o.ApplyT(func(v *DefaultPasswordResetMessageText) pulumi.StringOutput { return v.Language }).(pulumi.StringOutput)
}

func (o DefaultPasswordResetMessageTextOutput) PreHeader() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DefaultPasswordResetMessageText) pulumi.StringPtrOutput { return v.PreHeader }).(pulumi.StringPtrOutput)
}

func (o DefaultPasswordResetMessageTextOutput) Subject() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DefaultPasswordResetMessageText) pulumi.StringPtrOutput { return v.Subject }).(pulumi.StringPtrOutput)
}

func (o DefaultPasswordResetMessageTextOutput) Text() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DefaultPasswordResetMessageText) pulumi.StringPtrOutput { return v.Text }).(pulumi.StringPtrOutput)
}

func (o DefaultPasswordResetMessageTextOutput) Title() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DefaultPasswordResetMessageText) pulumi.StringPtrOutput { return v.Title }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*DefaultPasswordResetMessageTextInput)(nil)).Elem(), &DefaultPasswordResetMessageText{})
	pulumi.RegisterOutputType(DefaultPasswordResetMessageTextOutput{})
}
