// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package zitadel

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/truvity/pulumi-zitadel/sdk/go/zitadel/internal"
)

// Resource representing the default password age policy.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/truvity/pulumi-zitadel/sdk/go/zitadel"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := zitadel.NewDefaultPasswordAgePolicy(ctx, "default", &zitadel.DefaultPasswordAgePolicyArgs{
//				MaxAgeDays:     pulumi.Int(30),
//				ExpireWarnDays: pulumi.Int(5),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Import
//
// The resource can be imported using the ID format `<>`, e.g.
//
// ```sh
// $ pulumi import zitadel:index/defaultPasswordAgePolicy:DefaultPasswordAgePolicy imported ”
// ```
type DefaultPasswordAgePolicy struct {
	pulumi.CustomResourceState

	// amount of days after which the user should be notified of the upcoming expiry
	ExpireWarnDays pulumi.IntOutput `pulumi:"expireWarnDays"`
	// amount of days after which a password will expire
	MaxAgeDays pulumi.IntOutput `pulumi:"maxAgeDays"`
}

// NewDefaultPasswordAgePolicy registers a new resource with the given unique name, arguments, and options.
func NewDefaultPasswordAgePolicy(ctx *pulumi.Context,
	name string, args *DefaultPasswordAgePolicyArgs, opts ...pulumi.ResourceOption) (*DefaultPasswordAgePolicy, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.ExpireWarnDays == nil {
		return nil, errors.New("invalid value for required argument 'ExpireWarnDays'")
	}
	if args.MaxAgeDays == nil {
		return nil, errors.New("invalid value for required argument 'MaxAgeDays'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource DefaultPasswordAgePolicy
	err := ctx.RegisterResource("zitadel:index/defaultPasswordAgePolicy:DefaultPasswordAgePolicy", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetDefaultPasswordAgePolicy gets an existing DefaultPasswordAgePolicy resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetDefaultPasswordAgePolicy(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *DefaultPasswordAgePolicyState, opts ...pulumi.ResourceOption) (*DefaultPasswordAgePolicy, error) {
	var resource DefaultPasswordAgePolicy
	err := ctx.ReadResource("zitadel:index/defaultPasswordAgePolicy:DefaultPasswordAgePolicy", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering DefaultPasswordAgePolicy resources.
type defaultPasswordAgePolicyState struct {
	// amount of days after which the user should be notified of the upcoming expiry
	ExpireWarnDays *int `pulumi:"expireWarnDays"`
	// amount of days after which a password will expire
	MaxAgeDays *int `pulumi:"maxAgeDays"`
}

type DefaultPasswordAgePolicyState struct {
	// amount of days after which the user should be notified of the upcoming expiry
	ExpireWarnDays pulumi.IntPtrInput
	// amount of days after which a password will expire
	MaxAgeDays pulumi.IntPtrInput
}

func (DefaultPasswordAgePolicyState) ElementType() reflect.Type {
	return reflect.TypeOf((*defaultPasswordAgePolicyState)(nil)).Elem()
}

type defaultPasswordAgePolicyArgs struct {
	// amount of days after which the user should be notified of the upcoming expiry
	ExpireWarnDays int `pulumi:"expireWarnDays"`
	// amount of days after which a password will expire
	MaxAgeDays int `pulumi:"maxAgeDays"`
}

// The set of arguments for constructing a DefaultPasswordAgePolicy resource.
type DefaultPasswordAgePolicyArgs struct {
	// amount of days after which the user should be notified of the upcoming expiry
	ExpireWarnDays pulumi.IntInput
	// amount of days after which a password will expire
	MaxAgeDays pulumi.IntInput
}

func (DefaultPasswordAgePolicyArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*defaultPasswordAgePolicyArgs)(nil)).Elem()
}

type DefaultPasswordAgePolicyInput interface {
	pulumi.Input

	ToDefaultPasswordAgePolicyOutput() DefaultPasswordAgePolicyOutput
	ToDefaultPasswordAgePolicyOutputWithContext(ctx context.Context) DefaultPasswordAgePolicyOutput
}

func (*DefaultPasswordAgePolicy) ElementType() reflect.Type {
	return reflect.TypeOf((**DefaultPasswordAgePolicy)(nil)).Elem()
}

func (i *DefaultPasswordAgePolicy) ToDefaultPasswordAgePolicyOutput() DefaultPasswordAgePolicyOutput {
	return i.ToDefaultPasswordAgePolicyOutputWithContext(context.Background())
}

func (i *DefaultPasswordAgePolicy) ToDefaultPasswordAgePolicyOutputWithContext(ctx context.Context) DefaultPasswordAgePolicyOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DefaultPasswordAgePolicyOutput)
}

type DefaultPasswordAgePolicyOutput struct{ *pulumi.OutputState }

func (DefaultPasswordAgePolicyOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**DefaultPasswordAgePolicy)(nil)).Elem()
}

func (o DefaultPasswordAgePolicyOutput) ToDefaultPasswordAgePolicyOutput() DefaultPasswordAgePolicyOutput {
	return o
}

func (o DefaultPasswordAgePolicyOutput) ToDefaultPasswordAgePolicyOutputWithContext(ctx context.Context) DefaultPasswordAgePolicyOutput {
	return o
}

// amount of days after which the user should be notified of the upcoming expiry
func (o DefaultPasswordAgePolicyOutput) ExpireWarnDays() pulumi.IntOutput {
	return o.ApplyT(func(v *DefaultPasswordAgePolicy) pulumi.IntOutput { return v.ExpireWarnDays }).(pulumi.IntOutput)
}

// amount of days after which a password will expire
func (o DefaultPasswordAgePolicyOutput) MaxAgeDays() pulumi.IntOutput {
	return o.ApplyT(func(v *DefaultPasswordAgePolicy) pulumi.IntOutput { return v.MaxAgeDays }).(pulumi.IntOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*DefaultPasswordAgePolicyInput)(nil)).Elem(), &DefaultPasswordAgePolicy{})
	pulumi.RegisterOutputType(DefaultPasswordAgePolicyOutput{})
}
