// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package zitadel

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/truvity/pulumi-zitadel/sdk/go/zitadel/internal"
)

// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/truvity/pulumi-zitadel/sdk/go/zitadel"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := zitadel.NewDefaultInitMessageText(ctx, "default", &zitadel.DefaultInitMessageTextArgs{
//				Language:   pulumi.String("en"),
//				Title:      pulumi.String("title example"),
//				PreHeader:  pulumi.String("pre_header example"),
//				Subject:    pulumi.String("subject example"),
//				Greeting:   pulumi.String("greeting example"),
//				Text:       pulumi.String("text example"),
//				ButtonText: pulumi.String("button_text example"),
//				FooterText: pulumi.String("footer_text example"),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
type DefaultInitMessageText struct {
	pulumi.CustomResourceState

	ButtonText pulumi.StringPtrOutput `pulumi:"buttonText"`
	FooterText pulumi.StringPtrOutput `pulumi:"footerText"`
	Greeting   pulumi.StringPtrOutput `pulumi:"greeting"`
	Language   pulumi.StringOutput    `pulumi:"language"`
	PreHeader  pulumi.StringPtrOutput `pulumi:"preHeader"`
	Subject    pulumi.StringPtrOutput `pulumi:"subject"`
	Text       pulumi.StringPtrOutput `pulumi:"text"`
	Title      pulumi.StringPtrOutput `pulumi:"title"`
}

// NewDefaultInitMessageText registers a new resource with the given unique name, arguments, and options.
func NewDefaultInitMessageText(ctx *pulumi.Context,
	name string, args *DefaultInitMessageTextArgs, opts ...pulumi.ResourceOption) (*DefaultInitMessageText, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Language == nil {
		return nil, errors.New("invalid value for required argument 'Language'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource DefaultInitMessageText
	err := ctx.RegisterResource("zitadel:index/defaultInitMessageText:DefaultInitMessageText", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetDefaultInitMessageText gets an existing DefaultInitMessageText resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetDefaultInitMessageText(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *DefaultInitMessageTextState, opts ...pulumi.ResourceOption) (*DefaultInitMessageText, error) {
	var resource DefaultInitMessageText
	err := ctx.ReadResource("zitadel:index/defaultInitMessageText:DefaultInitMessageText", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering DefaultInitMessageText resources.
type defaultInitMessageTextState struct {
	ButtonText *string `pulumi:"buttonText"`
	FooterText *string `pulumi:"footerText"`
	Greeting   *string `pulumi:"greeting"`
	Language   *string `pulumi:"language"`
	PreHeader  *string `pulumi:"preHeader"`
	Subject    *string `pulumi:"subject"`
	Text       *string `pulumi:"text"`
	Title      *string `pulumi:"title"`
}

type DefaultInitMessageTextState struct {
	ButtonText pulumi.StringPtrInput
	FooterText pulumi.StringPtrInput
	Greeting   pulumi.StringPtrInput
	Language   pulumi.StringPtrInput
	PreHeader  pulumi.StringPtrInput
	Subject    pulumi.StringPtrInput
	Text       pulumi.StringPtrInput
	Title      pulumi.StringPtrInput
}

func (DefaultInitMessageTextState) ElementType() reflect.Type {
	return reflect.TypeOf((*defaultInitMessageTextState)(nil)).Elem()
}

type defaultInitMessageTextArgs struct {
	ButtonText *string `pulumi:"buttonText"`
	FooterText *string `pulumi:"footerText"`
	Greeting   *string `pulumi:"greeting"`
	Language   string  `pulumi:"language"`
	PreHeader  *string `pulumi:"preHeader"`
	Subject    *string `pulumi:"subject"`
	Text       *string `pulumi:"text"`
	Title      *string `pulumi:"title"`
}

// The set of arguments for constructing a DefaultInitMessageText resource.
type DefaultInitMessageTextArgs struct {
	ButtonText pulumi.StringPtrInput
	FooterText pulumi.StringPtrInput
	Greeting   pulumi.StringPtrInput
	Language   pulumi.StringInput
	PreHeader  pulumi.StringPtrInput
	Subject    pulumi.StringPtrInput
	Text       pulumi.StringPtrInput
	Title      pulumi.StringPtrInput
}

func (DefaultInitMessageTextArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*defaultInitMessageTextArgs)(nil)).Elem()
}

type DefaultInitMessageTextInput interface {
	pulumi.Input

	ToDefaultInitMessageTextOutput() DefaultInitMessageTextOutput
	ToDefaultInitMessageTextOutputWithContext(ctx context.Context) DefaultInitMessageTextOutput
}

func (*DefaultInitMessageText) ElementType() reflect.Type {
	return reflect.TypeOf((**DefaultInitMessageText)(nil)).Elem()
}

func (i *DefaultInitMessageText) ToDefaultInitMessageTextOutput() DefaultInitMessageTextOutput {
	return i.ToDefaultInitMessageTextOutputWithContext(context.Background())
}

func (i *DefaultInitMessageText) ToDefaultInitMessageTextOutputWithContext(ctx context.Context) DefaultInitMessageTextOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DefaultInitMessageTextOutput)
}

type DefaultInitMessageTextOutput struct{ *pulumi.OutputState }

func (DefaultInitMessageTextOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**DefaultInitMessageText)(nil)).Elem()
}

func (o DefaultInitMessageTextOutput) ToDefaultInitMessageTextOutput() DefaultInitMessageTextOutput {
	return o
}

func (o DefaultInitMessageTextOutput) ToDefaultInitMessageTextOutputWithContext(ctx context.Context) DefaultInitMessageTextOutput {
	return o
}

func (o DefaultInitMessageTextOutput) ButtonText() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DefaultInitMessageText) pulumi.StringPtrOutput { return v.ButtonText }).(pulumi.StringPtrOutput)
}

func (o DefaultInitMessageTextOutput) FooterText() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DefaultInitMessageText) pulumi.StringPtrOutput { return v.FooterText }).(pulumi.StringPtrOutput)
}

func (o DefaultInitMessageTextOutput) Greeting() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DefaultInitMessageText) pulumi.StringPtrOutput { return v.Greeting }).(pulumi.StringPtrOutput)
}

func (o DefaultInitMessageTextOutput) Language() pulumi.StringOutput {
	return o.ApplyT(func(v *DefaultInitMessageText) pulumi.StringOutput { return v.Language }).(pulumi.StringOutput)
}

func (o DefaultInitMessageTextOutput) PreHeader() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DefaultInitMessageText) pulumi.StringPtrOutput { return v.PreHeader }).(pulumi.StringPtrOutput)
}

func (o DefaultInitMessageTextOutput) Subject() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DefaultInitMessageText) pulumi.StringPtrOutput { return v.Subject }).(pulumi.StringPtrOutput)
}

func (o DefaultInitMessageTextOutput) Text() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DefaultInitMessageText) pulumi.StringPtrOutput { return v.Text }).(pulumi.StringPtrOutput)
}

func (o DefaultInitMessageTextOutput) Title() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DefaultInitMessageText) pulumi.StringPtrOutput { return v.Title }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*DefaultInitMessageTextInput)(nil)).Elem(), &DefaultInitMessageText{})
	pulumi.RegisterOutputType(DefaultInitMessageTextOutput{})
}
