// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package zitadel

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/truvity/pulumi-zitadel/sdk/go/zitadel/internal"
)

// Instance-level default template for the passkey/passwordless registration invitation email. Org-level overrides are managed by `PasswordlessRegistrationMessageText`.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/truvity/pulumi-zitadel/sdk/go/zitadel"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := zitadel.NewDefaultPasswordlessRegistrationMessageText(ctx, "default", &zitadel.DefaultPasswordlessRegistrationMessageTextArgs{
//				Language:   pulumi.String("en"),
//				Title:      pulumi.String("title example"),
//				PreHeader:  pulumi.String("pre_header example"),
//				Subject:    pulumi.String("subject example"),
//				Greeting:   pulumi.String("greeting example"),
//				Text:       pulumi.String("text example"),
//				ButtonText: pulumi.String("button_text example"),
//				FooterText: pulumi.String("footer_text example"),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
type DefaultPasswordlessRegistrationMessageText struct {
	pulumi.CustomResourceState

	ButtonText pulumi.StringPtrOutput `pulumi:"buttonText"`
	FooterText pulumi.StringPtrOutput `pulumi:"footerText"`
	Greeting   pulumi.StringPtrOutput `pulumi:"greeting"`
	Language   pulumi.StringOutput    `pulumi:"language"`
	PreHeader  pulumi.StringPtrOutput `pulumi:"preHeader"`
	Subject    pulumi.StringPtrOutput `pulumi:"subject"`
	Text       pulumi.StringPtrOutput `pulumi:"text"`
	Title      pulumi.StringPtrOutput `pulumi:"title"`
}

// NewDefaultPasswordlessRegistrationMessageText registers a new resource with the given unique name, arguments, and options.
func NewDefaultPasswordlessRegistrationMessageText(ctx *pulumi.Context,
	name string, args *DefaultPasswordlessRegistrationMessageTextArgs, opts ...pulumi.ResourceOption) (*DefaultPasswordlessRegistrationMessageText, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Language == nil {
		return nil, errors.New("invalid value for required argument 'Language'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource DefaultPasswordlessRegistrationMessageText
	err := ctx.RegisterResource("zitadel:index/defaultPasswordlessRegistrationMessageText:DefaultPasswordlessRegistrationMessageText", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetDefaultPasswordlessRegistrationMessageText gets an existing DefaultPasswordlessRegistrationMessageText resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetDefaultPasswordlessRegistrationMessageText(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *DefaultPasswordlessRegistrationMessageTextState, opts ...pulumi.ResourceOption) (*DefaultPasswordlessRegistrationMessageText, error) {
	var resource DefaultPasswordlessRegistrationMessageText
	err := ctx.ReadResource("zitadel:index/defaultPasswordlessRegistrationMessageText:DefaultPasswordlessRegistrationMessageText", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering DefaultPasswordlessRegistrationMessageText resources.
type defaultPasswordlessRegistrationMessageTextState struct {
	ButtonText *string `pulumi:"buttonText"`
	FooterText *string `pulumi:"footerText"`
	Greeting   *string `pulumi:"greeting"`
	Language   *string `pulumi:"language"`
	PreHeader  *string `pulumi:"preHeader"`
	Subject    *string `pulumi:"subject"`
	Text       *string `pulumi:"text"`
	Title      *string `pulumi:"title"`
}

type DefaultPasswordlessRegistrationMessageTextState struct {
	ButtonText pulumi.StringPtrInput
	FooterText pulumi.StringPtrInput
	Greeting   pulumi.StringPtrInput
	Language   pulumi.StringPtrInput
	PreHeader  pulumi.StringPtrInput
	Subject    pulumi.StringPtrInput
	Text       pulumi.StringPtrInput
	Title      pulumi.StringPtrInput
}

func (DefaultPasswordlessRegistrationMessageTextState) ElementType() reflect.Type {
	return reflect.TypeOf((*defaultPasswordlessRegistrationMessageTextState)(nil)).Elem()
}

type defaultPasswordlessRegistrationMessageTextArgs struct {
	ButtonText *string `pulumi:"buttonText"`
	FooterText *string `pulumi:"footerText"`
	Greeting   *string `pulumi:"greeting"`
	Language   string  `pulumi:"language"`
	PreHeader  *string `pulumi:"preHeader"`
	Subject    *string `pulumi:"subject"`
	Text       *string `pulumi:"text"`
	Title      *string `pulumi:"title"`
}

// The set of arguments for constructing a DefaultPasswordlessRegistrationMessageText resource.
type DefaultPasswordlessRegistrationMessageTextArgs struct {
	ButtonText pulumi.StringPtrInput
	FooterText pulumi.StringPtrInput
	Greeting   pulumi.StringPtrInput
	Language   pulumi.StringInput
	PreHeader  pulumi.StringPtrInput
	Subject    pulumi.StringPtrInput
	Text       pulumi.StringPtrInput
	Title      pulumi.StringPtrInput
}

func (DefaultPasswordlessRegistrationMessageTextArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*defaultPasswordlessRegistrationMessageTextArgs)(nil)).Elem()
}

type DefaultPasswordlessRegistrationMessageTextInput interface {
	pulumi.Input

	ToDefaultPasswordlessRegistrationMessageTextOutput() DefaultPasswordlessRegistrationMessageTextOutput
	ToDefaultPasswordlessRegistrationMessageTextOutputWithContext(ctx context.Context) DefaultPasswordlessRegistrationMessageTextOutput
}

func (*DefaultPasswordlessRegistrationMessageText) ElementType() reflect.Type {
	return reflect.TypeOf((**DefaultPasswordlessRegistrationMessageText)(nil)).Elem()
}

func (i *DefaultPasswordlessRegistrationMessageText) ToDefaultPasswordlessRegistrationMessageTextOutput() DefaultPasswordlessRegistrationMessageTextOutput {
	return i.ToDefaultPasswordlessRegistrationMessageTextOutputWithContext(context.Background())
}

func (i *DefaultPasswordlessRegistrationMessageText) ToDefaultPasswordlessRegistrationMessageTextOutputWithContext(ctx context.Context) DefaultPasswordlessRegistrationMessageTextOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DefaultPasswordlessRegistrationMessageTextOutput)
}

type DefaultPasswordlessRegistrationMessageTextOutput struct{ *pulumi.OutputState }

func (DefaultPasswordlessRegistrationMessageTextOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**DefaultPasswordlessRegistrationMessageText)(nil)).Elem()
}

func (o DefaultPasswordlessRegistrationMessageTextOutput) ToDefaultPasswordlessRegistrationMessageTextOutput() DefaultPasswordlessRegistrationMessageTextOutput {
	return o
}

func (o DefaultPasswordlessRegistrationMessageTextOutput) ToDefaultPasswordlessRegistrationMessageTextOutputWithContext(ctx context.Context) DefaultPasswordlessRegistrationMessageTextOutput {
	return o
}

func (o DefaultPasswordlessRegistrationMessageTextOutput) ButtonText() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DefaultPasswordlessRegistrationMessageText) pulumi.StringPtrOutput { return v.ButtonText }).(pulumi.StringPtrOutput)
}

func (o DefaultPasswordlessRegistrationMessageTextOutput) FooterText() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DefaultPasswordlessRegistrationMessageText) pulumi.StringPtrOutput { return v.FooterText }).(pulumi.StringPtrOutput)
}

func (o DefaultPasswordlessRegistrationMessageTextOutput) Greeting() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DefaultPasswordlessRegistrationMessageText) pulumi.StringPtrOutput { return v.Greeting }).(pulumi.StringPtrOutput)
}

func (o DefaultPasswordlessRegistrationMessageTextOutput) Language() pulumi.StringOutput {
	return o.ApplyT(func(v *DefaultPasswordlessRegistrationMessageText) pulumi.StringOutput { return v.Language }).(pulumi.StringOutput)
}

func (o DefaultPasswordlessRegistrationMessageTextOutput) PreHeader() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DefaultPasswordlessRegistrationMessageText) pulumi.StringPtrOutput { return v.PreHeader }).(pulumi.StringPtrOutput)
}

func (o DefaultPasswordlessRegistrationMessageTextOutput) Subject() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DefaultPasswordlessRegistrationMessageText) pulumi.StringPtrOutput { return v.Subject }).(pulumi.StringPtrOutput)
}

func (o DefaultPasswordlessRegistrationMessageTextOutput) Text() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DefaultPasswordlessRegistrationMessageText) pulumi.StringPtrOutput { return v.Text }).(pulumi.StringPtrOutput)
}

func (o DefaultPasswordlessRegistrationMessageTextOutput) Title() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DefaultPasswordlessRegistrationMessageText) pulumi.StringPtrOutput { return v.Title }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*DefaultPasswordlessRegistrationMessageTextInput)(nil)).Elem(), &DefaultPasswordlessRegistrationMessageText{})
	pulumi.RegisterOutputType(DefaultPasswordlessRegistrationMessageTextOutput{})
}
