// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package zitadel

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/truvity/pulumi-zitadel/sdk/go/zitadel/internal"
)

// Resource representing the default lockout policy.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/truvity/pulumi-zitadel/sdk/go/zitadel"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := zitadel.NewDefaultLockoutPolicy(ctx, "default", &zitadel.DefaultLockoutPolicyArgs{
//				MaxPasswordAttempts: pulumi.Int(5),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Import
//
// The resource can be imported using the ID format `<>`, e.g.
//
// ```sh
// $ pulumi import zitadel:index/defaultLockoutPolicy:DefaultLockoutPolicy imported ”
// ```
type DefaultLockoutPolicy struct {
	pulumi.CustomResourceState

	// Maximum OTP check attempts before the account gets locked. Attempts are reset as soon as the OTP is entered correctly.
	MaxOtpAttempts pulumi.IntOutput `pulumi:"maxOtpAttempts"`
	// Maximum password check attempts before the account gets locked. Attempts are reset as soon as the password is entered correctly or the password is reset.
	MaxPasswordAttempts pulumi.IntOutput `pulumi:"maxPasswordAttempts"`
}

// NewDefaultLockoutPolicy registers a new resource with the given unique name, arguments, and options.
func NewDefaultLockoutPolicy(ctx *pulumi.Context,
	name string, args *DefaultLockoutPolicyArgs, opts ...pulumi.ResourceOption) (*DefaultLockoutPolicy, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.MaxPasswordAttempts == nil {
		return nil, errors.New("invalid value for required argument 'MaxPasswordAttempts'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource DefaultLockoutPolicy
	err := ctx.RegisterResource("zitadel:index/defaultLockoutPolicy:DefaultLockoutPolicy", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetDefaultLockoutPolicy gets an existing DefaultLockoutPolicy resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetDefaultLockoutPolicy(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *DefaultLockoutPolicyState, opts ...pulumi.ResourceOption) (*DefaultLockoutPolicy, error) {
	var resource DefaultLockoutPolicy
	err := ctx.ReadResource("zitadel:index/defaultLockoutPolicy:DefaultLockoutPolicy", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering DefaultLockoutPolicy resources.
type defaultLockoutPolicyState struct {
	// Maximum OTP check attempts before the account gets locked. Attempts are reset as soon as the OTP is entered correctly.
	MaxOtpAttempts *int `pulumi:"maxOtpAttempts"`
	// Maximum password check attempts before the account gets locked. Attempts are reset as soon as the password is entered correctly or the password is reset.
	MaxPasswordAttempts *int `pulumi:"maxPasswordAttempts"`
}

type DefaultLockoutPolicyState struct {
	// Maximum OTP check attempts before the account gets locked. Attempts are reset as soon as the OTP is entered correctly.
	MaxOtpAttempts pulumi.IntPtrInput
	// Maximum password check attempts before the account gets locked. Attempts are reset as soon as the password is entered correctly or the password is reset.
	MaxPasswordAttempts pulumi.IntPtrInput
}

func (DefaultLockoutPolicyState) ElementType() reflect.Type {
	return reflect.TypeOf((*defaultLockoutPolicyState)(nil)).Elem()
}

type defaultLockoutPolicyArgs struct {
	// Maximum OTP check attempts before the account gets locked. Attempts are reset as soon as the OTP is entered correctly.
	MaxOtpAttempts *int `pulumi:"maxOtpAttempts"`
	// Maximum password check attempts before the account gets locked. Attempts are reset as soon as the password is entered correctly or the password is reset.
	MaxPasswordAttempts int `pulumi:"maxPasswordAttempts"`
}

// The set of arguments for constructing a DefaultLockoutPolicy resource.
type DefaultLockoutPolicyArgs struct {
	// Maximum OTP check attempts before the account gets locked. Attempts are reset as soon as the OTP is entered correctly.
	MaxOtpAttempts pulumi.IntPtrInput
	// Maximum password check attempts before the account gets locked. Attempts are reset as soon as the password is entered correctly or the password is reset.
	MaxPasswordAttempts pulumi.IntInput
}

func (DefaultLockoutPolicyArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*defaultLockoutPolicyArgs)(nil)).Elem()
}

type DefaultLockoutPolicyInput interface {
	pulumi.Input

	ToDefaultLockoutPolicyOutput() DefaultLockoutPolicyOutput
	ToDefaultLockoutPolicyOutputWithContext(ctx context.Context) DefaultLockoutPolicyOutput
}

func (*DefaultLockoutPolicy) ElementType() reflect.Type {
	return reflect.TypeOf((**DefaultLockoutPolicy)(nil)).Elem()
}

func (i *DefaultLockoutPolicy) ToDefaultLockoutPolicyOutput() DefaultLockoutPolicyOutput {
	return i.ToDefaultLockoutPolicyOutputWithContext(context.Background())
}

func (i *DefaultLockoutPolicy) ToDefaultLockoutPolicyOutputWithContext(ctx context.Context) DefaultLockoutPolicyOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DefaultLockoutPolicyOutput)
}

type DefaultLockoutPolicyOutput struct{ *pulumi.OutputState }

func (DefaultLockoutPolicyOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**DefaultLockoutPolicy)(nil)).Elem()
}

func (o DefaultLockoutPolicyOutput) ToDefaultLockoutPolicyOutput() DefaultLockoutPolicyOutput {
	return o
}

func (o DefaultLockoutPolicyOutput) ToDefaultLockoutPolicyOutputWithContext(ctx context.Context) DefaultLockoutPolicyOutput {
	return o
}

// Maximum OTP check attempts before the account gets locked. Attempts are reset as soon as the OTP is entered correctly.
func (o DefaultLockoutPolicyOutput) MaxOtpAttempts() pulumi.IntOutput {
	return o.ApplyT(func(v *DefaultLockoutPolicy) pulumi.IntOutput { return v.MaxOtpAttempts }).(pulumi.IntOutput)
}

// Maximum password check attempts before the account gets locked. Attempts are reset as soon as the password is entered correctly or the password is reset.
func (o DefaultLockoutPolicyOutput) MaxPasswordAttempts() pulumi.IntOutput {
	return o.ApplyT(func(v *DefaultLockoutPolicy) pulumi.IntOutput { return v.MaxPasswordAttempts }).(pulumi.IntOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*DefaultLockoutPolicyInput)(nil)).Elem(), &DefaultLockoutPolicy{})
	pulumi.RegisterOutputType(DefaultLockoutPolicyOutput{})
}
