// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package zitadel

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/truvity/pulumi-zitadel/sdk/go/zitadel/internal"
)

// Resource representing a domain of the organization.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/truvity/pulumi-zitadel/sdk/go/zitadel"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := zitadel.NewDomain(ctx, "default", &zitadel.DomainArgs{
//				OrgId:     pulumi.Any(defaultZitadelOrg.Id),
//				Name:      pulumi.String("zitadel.default.127.0.0.1.sslip.io"),
//				IsPrimary: pulumi.Bool(false),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Import
//
// The resource can be imported using the ID format `name[:org_id]`, e.g.
//
// ```sh
// $ pulumi import zitadel:index/domain:Domain imported 'example.com:123456789012345678'
// ```
type Domain struct {
	pulumi.CustomResourceState

	// Is domain primary
	IsPrimary pulumi.BoolPtrOutput `pulumi:"isPrimary"`
	// Is domain verified
	IsVerified pulumi.BoolOutput `pulumi:"isVerified"`
	// Name of the domain
	Name pulumi.StringOutput `pulumi:"name"`
	// ID of the organization. If not provided, the organization of the authenticated user/service account is used.
	OrgId pulumi.StringPtrOutput `pulumi:"orgId"`
	// Validation type
	ValidationType pulumi.IntOutput `pulumi:"validationType"`
}

// NewDomain registers a new resource with the given unique name, arguments, and options.
func NewDomain(ctx *pulumi.Context,
	name string, args *DomainArgs, opts ...pulumi.ResourceOption) (*Domain, error) {
	if args == nil {
		args = &DomainArgs{}
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Domain
	err := ctx.RegisterResource("zitadel:index/domain:Domain", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetDomain gets an existing Domain resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetDomain(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *DomainState, opts ...pulumi.ResourceOption) (*Domain, error) {
	var resource Domain
	err := ctx.ReadResource("zitadel:index/domain:Domain", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Domain resources.
type domainState struct {
	// Is domain primary
	IsPrimary *bool `pulumi:"isPrimary"`
	// Is domain verified
	IsVerified *bool `pulumi:"isVerified"`
	// Name of the domain
	Name *string `pulumi:"name"`
	// ID of the organization. If not provided, the organization of the authenticated user/service account is used.
	OrgId *string `pulumi:"orgId"`
	// Validation type
	ValidationType *int `pulumi:"validationType"`
}

type DomainState struct {
	// Is domain primary
	IsPrimary pulumi.BoolPtrInput
	// Is domain verified
	IsVerified pulumi.BoolPtrInput
	// Name of the domain
	Name pulumi.StringPtrInput
	// ID of the organization. If not provided, the organization of the authenticated user/service account is used.
	OrgId pulumi.StringPtrInput
	// Validation type
	ValidationType pulumi.IntPtrInput
}

func (DomainState) ElementType() reflect.Type {
	return reflect.TypeOf((*domainState)(nil)).Elem()
}

type domainArgs struct {
	// Is domain primary
	IsPrimary *bool `pulumi:"isPrimary"`
	// Name of the domain
	Name *string `pulumi:"name"`
	// ID of the organization. If not provided, the organization of the authenticated user/service account is used.
	OrgId *string `pulumi:"orgId"`
}

// The set of arguments for constructing a Domain resource.
type DomainArgs struct {
	// Is domain primary
	IsPrimary pulumi.BoolPtrInput
	// Name of the domain
	Name pulumi.StringPtrInput
	// ID of the organization. If not provided, the organization of the authenticated user/service account is used.
	OrgId pulumi.StringPtrInput
}

func (DomainArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*domainArgs)(nil)).Elem()
}

type DomainInput interface {
	pulumi.Input

	ToDomainOutput() DomainOutput
	ToDomainOutputWithContext(ctx context.Context) DomainOutput
}

func (*Domain) ElementType() reflect.Type {
	return reflect.TypeOf((**Domain)(nil)).Elem()
}

func (i *Domain) ToDomainOutput() DomainOutput {
	return i.ToDomainOutputWithContext(context.Background())
}

func (i *Domain) ToDomainOutputWithContext(ctx context.Context) DomainOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DomainOutput)
}

type DomainOutput struct{ *pulumi.OutputState }

func (DomainOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Domain)(nil)).Elem()
}

func (o DomainOutput) ToDomainOutput() DomainOutput {
	return o
}

func (o DomainOutput) ToDomainOutputWithContext(ctx context.Context) DomainOutput {
	return o
}

// Is domain primary
func (o DomainOutput) IsPrimary() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *Domain) pulumi.BoolPtrOutput { return v.IsPrimary }).(pulumi.BoolPtrOutput)
}

// Is domain verified
func (o DomainOutput) IsVerified() pulumi.BoolOutput {
	return o.ApplyT(func(v *Domain) pulumi.BoolOutput { return v.IsVerified }).(pulumi.BoolOutput)
}

// Name of the domain
func (o DomainOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *Domain) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// ID of the organization. If not provided, the organization of the authenticated user/service account is used.
func (o DomainOutput) OrgId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Domain) pulumi.StringPtrOutput { return v.OrgId }).(pulumi.StringPtrOutput)
}

// Validation type
func (o DomainOutput) ValidationType() pulumi.IntOutput {
	return o.ApplyT(func(v *Domain) pulumi.IntOutput { return v.ValidationType }).(pulumi.IntOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*DomainInput)(nil)).Elem(), &Domain{})
	pulumi.RegisterOutputType(DomainOutput{})
}
