// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package zitadel

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/truvity/pulumi-zitadel/sdk/go/zitadel/internal"
)

// Customizes the notification email sent to users when a domain is claimed (org-scoped). Instance-level defaults are managed by `DefaultDomainClaimedMessageText`.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/truvity/pulumi-zitadel/sdk/go/zitadel"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := zitadel.NewDomainClaimedMessageText(ctx, "default", &zitadel.DomainClaimedMessageTextArgs{
//				OrgId:      pulumi.Any(defaultZitadelOrg.Id),
//				Language:   pulumi.String("en"),
//				Title:      pulumi.String("title example"),
//				PreHeader:  pulumi.String("pre_header example"),
//				Subject:    pulumi.String("subject example"),
//				Greeting:   pulumi.String("greeting example"),
//				Text:       pulumi.String("text example"),
//				ButtonText: pulumi.String("button_text example"),
//				FooterText: pulumi.String("footer_text example"),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
type DomainClaimedMessageText struct {
	pulumi.CustomResourceState

	ButtonText pulumi.StringPtrOutput `pulumi:"buttonText"`
	FooterText pulumi.StringPtrOutput `pulumi:"footerText"`
	Greeting   pulumi.StringPtrOutput `pulumi:"greeting"`
	Language   pulumi.StringOutput    `pulumi:"language"`
	OrgId      pulumi.StringOutput    `pulumi:"orgId"`
	PreHeader  pulumi.StringPtrOutput `pulumi:"preHeader"`
	Subject    pulumi.StringPtrOutput `pulumi:"subject"`
	Text       pulumi.StringPtrOutput `pulumi:"text"`
	Title      pulumi.StringPtrOutput `pulumi:"title"`
}

// NewDomainClaimedMessageText registers a new resource with the given unique name, arguments, and options.
func NewDomainClaimedMessageText(ctx *pulumi.Context,
	name string, args *DomainClaimedMessageTextArgs, opts ...pulumi.ResourceOption) (*DomainClaimedMessageText, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Language == nil {
		return nil, errors.New("invalid value for required argument 'Language'")
	}
	if args.OrgId == nil {
		return nil, errors.New("invalid value for required argument 'OrgId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource DomainClaimedMessageText
	err := ctx.RegisterResource("zitadel:index/domainClaimedMessageText:DomainClaimedMessageText", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetDomainClaimedMessageText gets an existing DomainClaimedMessageText resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetDomainClaimedMessageText(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *DomainClaimedMessageTextState, opts ...pulumi.ResourceOption) (*DomainClaimedMessageText, error) {
	var resource DomainClaimedMessageText
	err := ctx.ReadResource("zitadel:index/domainClaimedMessageText:DomainClaimedMessageText", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering DomainClaimedMessageText resources.
type domainClaimedMessageTextState struct {
	ButtonText *string `pulumi:"buttonText"`
	FooterText *string `pulumi:"footerText"`
	Greeting   *string `pulumi:"greeting"`
	Language   *string `pulumi:"language"`
	OrgId      *string `pulumi:"orgId"`
	PreHeader  *string `pulumi:"preHeader"`
	Subject    *string `pulumi:"subject"`
	Text       *string `pulumi:"text"`
	Title      *string `pulumi:"title"`
}

type DomainClaimedMessageTextState struct {
	ButtonText pulumi.StringPtrInput
	FooterText pulumi.StringPtrInput
	Greeting   pulumi.StringPtrInput
	Language   pulumi.StringPtrInput
	OrgId      pulumi.StringPtrInput
	PreHeader  pulumi.StringPtrInput
	Subject    pulumi.StringPtrInput
	Text       pulumi.StringPtrInput
	Title      pulumi.StringPtrInput
}

func (DomainClaimedMessageTextState) ElementType() reflect.Type {
	return reflect.TypeOf((*domainClaimedMessageTextState)(nil)).Elem()
}

type domainClaimedMessageTextArgs struct {
	ButtonText *string `pulumi:"buttonText"`
	FooterText *string `pulumi:"footerText"`
	Greeting   *string `pulumi:"greeting"`
	Language   string  `pulumi:"language"`
	OrgId      string  `pulumi:"orgId"`
	PreHeader  *string `pulumi:"preHeader"`
	Subject    *string `pulumi:"subject"`
	Text       *string `pulumi:"text"`
	Title      *string `pulumi:"title"`
}

// The set of arguments for constructing a DomainClaimedMessageText resource.
type DomainClaimedMessageTextArgs struct {
	ButtonText pulumi.StringPtrInput
	FooterText pulumi.StringPtrInput
	Greeting   pulumi.StringPtrInput
	Language   pulumi.StringInput
	OrgId      pulumi.StringInput
	PreHeader  pulumi.StringPtrInput
	Subject    pulumi.StringPtrInput
	Text       pulumi.StringPtrInput
	Title      pulumi.StringPtrInput
}

func (DomainClaimedMessageTextArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*domainClaimedMessageTextArgs)(nil)).Elem()
}

type DomainClaimedMessageTextInput interface {
	pulumi.Input

	ToDomainClaimedMessageTextOutput() DomainClaimedMessageTextOutput
	ToDomainClaimedMessageTextOutputWithContext(ctx context.Context) DomainClaimedMessageTextOutput
}

func (*DomainClaimedMessageText) ElementType() reflect.Type {
	return reflect.TypeOf((**DomainClaimedMessageText)(nil)).Elem()
}

func (i *DomainClaimedMessageText) ToDomainClaimedMessageTextOutput() DomainClaimedMessageTextOutput {
	return i.ToDomainClaimedMessageTextOutputWithContext(context.Background())
}

func (i *DomainClaimedMessageText) ToDomainClaimedMessageTextOutputWithContext(ctx context.Context) DomainClaimedMessageTextOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DomainClaimedMessageTextOutput)
}

type DomainClaimedMessageTextOutput struct{ *pulumi.OutputState }

func (DomainClaimedMessageTextOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**DomainClaimedMessageText)(nil)).Elem()
}

func (o DomainClaimedMessageTextOutput) ToDomainClaimedMessageTextOutput() DomainClaimedMessageTextOutput {
	return o
}

func (o DomainClaimedMessageTextOutput) ToDomainClaimedMessageTextOutputWithContext(ctx context.Context) DomainClaimedMessageTextOutput {
	return o
}

func (o DomainClaimedMessageTextOutput) ButtonText() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DomainClaimedMessageText) pulumi.StringPtrOutput { return v.ButtonText }).(pulumi.StringPtrOutput)
}

func (o DomainClaimedMessageTextOutput) FooterText() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DomainClaimedMessageText) pulumi.StringPtrOutput { return v.FooterText }).(pulumi.StringPtrOutput)
}

func (o DomainClaimedMessageTextOutput) Greeting() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DomainClaimedMessageText) pulumi.StringPtrOutput { return v.Greeting }).(pulumi.StringPtrOutput)
}

func (o DomainClaimedMessageTextOutput) Language() pulumi.StringOutput {
	return o.ApplyT(func(v *DomainClaimedMessageText) pulumi.StringOutput { return v.Language }).(pulumi.StringOutput)
}

func (o DomainClaimedMessageTextOutput) OrgId() pulumi.StringOutput {
	return o.ApplyT(func(v *DomainClaimedMessageText) pulumi.StringOutput { return v.OrgId }).(pulumi.StringOutput)
}

func (o DomainClaimedMessageTextOutput) PreHeader() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DomainClaimedMessageText) pulumi.StringPtrOutput { return v.PreHeader }).(pulumi.StringPtrOutput)
}

func (o DomainClaimedMessageTextOutput) Subject() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DomainClaimedMessageText) pulumi.StringPtrOutput { return v.Subject }).(pulumi.StringPtrOutput)
}

func (o DomainClaimedMessageTextOutput) Text() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DomainClaimedMessageText) pulumi.StringPtrOutput { return v.Text }).(pulumi.StringPtrOutput)
}

func (o DomainClaimedMessageTextOutput) Title() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DomainClaimedMessageText) pulumi.StringPtrOutput { return v.Title }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*DomainClaimedMessageTextInput)(nil)).Elem(), &DomainClaimedMessageText{})
	pulumi.RegisterOutputType(DomainClaimedMessageTextOutput{})
}
