// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package zitadel

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/truvity/pulumi-zitadel/sdk/go/zitadel/internal"
)

// Datasource representing an action execution triggered by an event.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/truvity/pulumi-zitadel/sdk/go/zitadel"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := zitadel.GetActionExecutionEvent(ctx, &zitadel.LookupActionExecutionEventArgs{
//				Id: "event:user.human.added",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func LookupActionExecutionEvent(ctx *pulumi.Context, args *LookupActionExecutionEventArgs, opts ...pulumi.InvokeOption) (*LookupActionExecutionEventResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupActionExecutionEventResult
	err := ctx.Invoke("zitadel:index/getActionExecutionEvent:getActionExecutionEvent", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getActionExecutionEvent.
type LookupActionExecutionEventArgs struct {
	// The ID of this resource. Must be set to the condition, e.g. `event:user.human.added`, `group:user.human`, or `all`/`all:`
	Id string `pulumi:"id"`
}

// A collection of values returned by getActionExecutionEvent.
type LookupActionExecutionEventResult struct {
	// Trigger on all events.
	All bool `pulumi:"all"`
	// The specific event to trigger on.
	Event string `pulumi:"event"`
	// The event group to trigger on.
	Group string `pulumi:"group"`
	// The ID of this resource. Must be set to the condition, e.g. `event:user.human.added`, `group:user.human`, or `all`/`all:`
	Id string `pulumi:"id"`
	// The list of target IDs to call.
	TargetIds []string `pulumi:"targetIds"`
}

func LookupActionExecutionEventOutput(ctx *pulumi.Context, args LookupActionExecutionEventOutputArgs, opts ...pulumi.InvokeOption) LookupActionExecutionEventResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupActionExecutionEventResultOutput, error) {
			args := v.(LookupActionExecutionEventArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("zitadel:index/getActionExecutionEvent:getActionExecutionEvent", args, LookupActionExecutionEventResultOutput{}, options).(LookupActionExecutionEventResultOutput), nil
		}).(LookupActionExecutionEventResultOutput)
}

// A collection of arguments for invoking getActionExecutionEvent.
type LookupActionExecutionEventOutputArgs struct {
	// The ID of this resource. Must be set to the condition, e.g. `event:user.human.added`, `group:user.human`, or `all`/`all:`
	Id pulumi.StringInput `pulumi:"id"`
}

func (LookupActionExecutionEventOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupActionExecutionEventArgs)(nil)).Elem()
}

// A collection of values returned by getActionExecutionEvent.
type LookupActionExecutionEventResultOutput struct{ *pulumi.OutputState }

func (LookupActionExecutionEventResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupActionExecutionEventResult)(nil)).Elem()
}

func (o LookupActionExecutionEventResultOutput) ToLookupActionExecutionEventResultOutput() LookupActionExecutionEventResultOutput {
	return o
}

func (o LookupActionExecutionEventResultOutput) ToLookupActionExecutionEventResultOutputWithContext(ctx context.Context) LookupActionExecutionEventResultOutput {
	return o
}

// Trigger on all events.
func (o LookupActionExecutionEventResultOutput) All() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupActionExecutionEventResult) bool { return v.All }).(pulumi.BoolOutput)
}

// The specific event to trigger on.
func (o LookupActionExecutionEventResultOutput) Event() pulumi.StringOutput {
	return o.ApplyT(func(v LookupActionExecutionEventResult) string { return v.Event }).(pulumi.StringOutput)
}

// The event group to trigger on.
func (o LookupActionExecutionEventResultOutput) Group() pulumi.StringOutput {
	return o.ApplyT(func(v LookupActionExecutionEventResult) string { return v.Group }).(pulumi.StringOutput)
}

// The ID of this resource. Must be set to the condition, e.g. `event:user.human.added`, `group:user.human`, or `all`/`all:`
func (o LookupActionExecutionEventResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupActionExecutionEventResult) string { return v.Id }).(pulumi.StringOutput)
}

// The list of target IDs to call.
func (o LookupActionExecutionEventResultOutput) TargetIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupActionExecutionEventResult) []string { return v.TargetIds }).(pulumi.StringArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupActionExecutionEventResultOutput{})
}
