// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package zitadel

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/truvity/pulumi-zitadel/sdk/go/zitadel/internal"
)

// Datasource listing application IDs in a project, regardless of application type.
//
// ## Example Usage
func GetApplicationsV2(ctx *pulumi.Context, args *GetApplicationsV2Args, opts ...pulumi.InvokeOption) (*GetApplicationsV2Result, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetApplicationsV2Result
	err := ctx.Invoke("zitadel:index/getApplicationsV2:getApplicationsV2", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getApplicationsV2.
type GetApplicationsV2Args struct {
	// Filter by exact application name.
	Name *string `pulumi:"name"`
	// ID of the organization
	OrgId *string `pulumi:"orgId"`
	// ID of the project to list applications from.
	ProjectId string `pulumi:"projectId"`
}

// A collection of values returned by getApplicationsV2.
type GetApplicationsV2Result struct {
	// Matching application IDs.
	AppIds []string `pulumi:"appIds"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// Filter by exact application name.
	Name *string `pulumi:"name"`
	// ID of the organization
	OrgId *string `pulumi:"orgId"`
	// ID of the project to list applications from.
	ProjectId string `pulumi:"projectId"`
}

func GetApplicationsV2Output(ctx *pulumi.Context, args GetApplicationsV2OutputArgs, opts ...pulumi.InvokeOption) GetApplicationsV2ResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetApplicationsV2ResultOutput, error) {
			args := v.(GetApplicationsV2Args)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("zitadel:index/getApplicationsV2:getApplicationsV2", args, GetApplicationsV2ResultOutput{}, options).(GetApplicationsV2ResultOutput), nil
		}).(GetApplicationsV2ResultOutput)
}

// A collection of arguments for invoking getApplicationsV2.
type GetApplicationsV2OutputArgs struct {
	// Filter by exact application name.
	Name pulumi.StringPtrInput `pulumi:"name"`
	// ID of the organization
	OrgId pulumi.StringPtrInput `pulumi:"orgId"`
	// ID of the project to list applications from.
	ProjectId pulumi.StringInput `pulumi:"projectId"`
}

func (GetApplicationsV2OutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetApplicationsV2Args)(nil)).Elem()
}

// A collection of values returned by getApplicationsV2.
type GetApplicationsV2ResultOutput struct{ *pulumi.OutputState }

func (GetApplicationsV2ResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetApplicationsV2Result)(nil)).Elem()
}

func (o GetApplicationsV2ResultOutput) ToGetApplicationsV2ResultOutput() GetApplicationsV2ResultOutput {
	return o
}

func (o GetApplicationsV2ResultOutput) ToGetApplicationsV2ResultOutputWithContext(ctx context.Context) GetApplicationsV2ResultOutput {
	return o
}

// Matching application IDs.
func (o GetApplicationsV2ResultOutput) AppIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetApplicationsV2Result) []string { return v.AppIds }).(pulumi.StringArrayOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetApplicationsV2ResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetApplicationsV2Result) string { return v.Id }).(pulumi.StringOutput)
}

// Filter by exact application name.
func (o GetApplicationsV2ResultOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetApplicationsV2Result) *string { return v.Name }).(pulumi.StringPtrOutput)
}

// ID of the organization
func (o GetApplicationsV2ResultOutput) OrgId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetApplicationsV2Result) *string { return v.OrgId }).(pulumi.StringPtrOutput)
}

// ID of the project to list applications from.
func (o GetApplicationsV2ResultOutput) ProjectId() pulumi.StringOutput {
	return o.ApplyT(func(v GetApplicationsV2Result) string { return v.ProjectId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetApplicationsV2ResultOutput{})
}
