// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package zitadel

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/truvity/pulumi-zitadel/sdk/go/zitadel/internal"
)

// Datasource representing an action execution triggered by a request.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/truvity/pulumi-zitadel/sdk/go/zitadel"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := zitadel.GetActionExecutionRequest(ctx, &zitadel.LookupActionExecutionRequestArgs{
//				Id: "method:/zitadel.session.v2.SessionService/ListSessions",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func LookupActionExecutionRequest(ctx *pulumi.Context, args *LookupActionExecutionRequestArgs, opts ...pulumi.InvokeOption) (*LookupActionExecutionRequestResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupActionExecutionRequestResult
	err := ctx.Invoke("zitadel:index/getActionExecutionRequest:getActionExecutionRequest", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getActionExecutionRequest.
type LookupActionExecutionRequestArgs struct {
	// The ID of this resource. Must be set to the condition, e.g. `method:/zitadel.session.v2.SessionService/ListSessions`, `service:zitadel.session.v2.SessionService`, or `all`/`all:`
	Id string `pulumi:"id"`
}

// A collection of values returned by getActionExecutionRequest.
type LookupActionExecutionRequestResult struct {
	// Trigger on all requests.
	All bool `pulumi:"all"`
	// The ID of this resource. Must be set to the condition, e.g. `method:/zitadel.session.v2.SessionService/ListSessions`, `service:zitadel.session.v2.SessionService`, or `all`/`all:`
	Id string `pulumi:"id"`
	// The gRPC method to trigger on.
	Method string `pulumi:"method"`
	// The gRPC service to trigger on.
	Service string `pulumi:"service"`
	// The list of target IDs to call.
	TargetIds []string `pulumi:"targetIds"`
}

func LookupActionExecutionRequestOutput(ctx *pulumi.Context, args LookupActionExecutionRequestOutputArgs, opts ...pulumi.InvokeOption) LookupActionExecutionRequestResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupActionExecutionRequestResultOutput, error) {
			args := v.(LookupActionExecutionRequestArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("zitadel:index/getActionExecutionRequest:getActionExecutionRequest", args, LookupActionExecutionRequestResultOutput{}, options).(LookupActionExecutionRequestResultOutput), nil
		}).(LookupActionExecutionRequestResultOutput)
}

// A collection of arguments for invoking getActionExecutionRequest.
type LookupActionExecutionRequestOutputArgs struct {
	// The ID of this resource. Must be set to the condition, e.g. `method:/zitadel.session.v2.SessionService/ListSessions`, `service:zitadel.session.v2.SessionService`, or `all`/`all:`
	Id pulumi.StringInput `pulumi:"id"`
}

func (LookupActionExecutionRequestOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupActionExecutionRequestArgs)(nil)).Elem()
}

// A collection of values returned by getActionExecutionRequest.
type LookupActionExecutionRequestResultOutput struct{ *pulumi.OutputState }

func (LookupActionExecutionRequestResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupActionExecutionRequestResult)(nil)).Elem()
}

func (o LookupActionExecutionRequestResultOutput) ToLookupActionExecutionRequestResultOutput() LookupActionExecutionRequestResultOutput {
	return o
}

func (o LookupActionExecutionRequestResultOutput) ToLookupActionExecutionRequestResultOutputWithContext(ctx context.Context) LookupActionExecutionRequestResultOutput {
	return o
}

// Trigger on all requests.
func (o LookupActionExecutionRequestResultOutput) All() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupActionExecutionRequestResult) bool { return v.All }).(pulumi.BoolOutput)
}

// The ID of this resource. Must be set to the condition, e.g. `method:/zitadel.session.v2.SessionService/ListSessions`, `service:zitadel.session.v2.SessionService`, or `all`/`all:`
func (o LookupActionExecutionRequestResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupActionExecutionRequestResult) string { return v.Id }).(pulumi.StringOutput)
}

// The gRPC method to trigger on.
func (o LookupActionExecutionRequestResultOutput) Method() pulumi.StringOutput {
	return o.ApplyT(func(v LookupActionExecutionRequestResult) string { return v.Method }).(pulumi.StringOutput)
}

// The gRPC service to trigger on.
func (o LookupActionExecutionRequestResultOutput) Service() pulumi.StringOutput {
	return o.ApplyT(func(v LookupActionExecutionRequestResult) string { return v.Service }).(pulumi.StringOutput)
}

// The list of target IDs to call.
func (o LookupActionExecutionRequestResultOutput) TargetIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupActionExecutionRequestResult) []string { return v.TargetIds }).(pulumi.StringArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupActionExecutionRequestResultOutput{})
}
