// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package zitadel

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/truvity/pulumi-zitadel/sdk/go/zitadel/internal"
)

// Datasource representing multiple SAML applications belonging to a project.
//
// ## Example Usage
func GetApplicationSamls(ctx *pulumi.Context, args *GetApplicationSamlsArgs, opts ...pulumi.InvokeOption) (*GetApplicationSamlsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetApplicationSamlsResult
	err := ctx.Invoke("zitadel:index/getApplicationSamls:getApplicationSamls", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getApplicationSamls.
type GetApplicationSamlsArgs struct {
	// Name of the application
	Name string `pulumi:"name"`
	// Method for querying applications by name, supported values: TEXT*QUERY*METHOD*EQUALS, TEXT*QUERY*METHOD*EQUALS*IGNORE*CASE, TEXT*QUERY*METHOD*STARTS*WITH, TEXT*QUERY*METHOD*STARTS*WITH*IGNORE*CASE, TEXT*QUERY*METHOD*CONTAINS, TEXT*QUERY*METHOD*CONTAINS*IGNORE*CASE, TEXT*QUERY*METHOD*ENDS*WITH, TEXT*QUERY*METHOD*ENDS*WITH*IGNORE*CASE
	NameMethod *string `pulumi:"nameMethod"`
	// ID of the organization
	OrgId *string `pulumi:"orgId"`
	// ID of the project
	ProjectId string `pulumi:"projectId"`
}

// A collection of values returned by getApplicationSamls.
type GetApplicationSamlsResult struct {
	// A set of all IDs.
	AppIds []string `pulumi:"appIds"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// Name of the application
	Name string `pulumi:"name"`
	// Method for querying applications by name, supported values: TEXT*QUERY*METHOD*EQUALS, TEXT*QUERY*METHOD*EQUALS*IGNORE*CASE, TEXT*QUERY*METHOD*STARTS*WITH, TEXT*QUERY*METHOD*STARTS*WITH*IGNORE*CASE, TEXT*QUERY*METHOD*CONTAINS, TEXT*QUERY*METHOD*CONTAINS*IGNORE*CASE, TEXT*QUERY*METHOD*ENDS*WITH, TEXT*QUERY*METHOD*ENDS*WITH*IGNORE*CASE
	NameMethod *string `pulumi:"nameMethod"`
	// ID of the organization
	OrgId *string `pulumi:"orgId"`
	// ID of the project
	ProjectId string `pulumi:"projectId"`
}

func GetApplicationSamlsOutput(ctx *pulumi.Context, args GetApplicationSamlsOutputArgs, opts ...pulumi.InvokeOption) GetApplicationSamlsResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetApplicationSamlsResultOutput, error) {
			args := v.(GetApplicationSamlsArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("zitadel:index/getApplicationSamls:getApplicationSamls", args, GetApplicationSamlsResultOutput{}, options).(GetApplicationSamlsResultOutput), nil
		}).(GetApplicationSamlsResultOutput)
}

// A collection of arguments for invoking getApplicationSamls.
type GetApplicationSamlsOutputArgs struct {
	// Name of the application
	Name pulumi.StringInput `pulumi:"name"`
	// Method for querying applications by name, supported values: TEXT*QUERY*METHOD*EQUALS, TEXT*QUERY*METHOD*EQUALS*IGNORE*CASE, TEXT*QUERY*METHOD*STARTS*WITH, TEXT*QUERY*METHOD*STARTS*WITH*IGNORE*CASE, TEXT*QUERY*METHOD*CONTAINS, TEXT*QUERY*METHOD*CONTAINS*IGNORE*CASE, TEXT*QUERY*METHOD*ENDS*WITH, TEXT*QUERY*METHOD*ENDS*WITH*IGNORE*CASE
	NameMethod pulumi.StringPtrInput `pulumi:"nameMethod"`
	// ID of the organization
	OrgId pulumi.StringPtrInput `pulumi:"orgId"`
	// ID of the project
	ProjectId pulumi.StringInput `pulumi:"projectId"`
}

func (GetApplicationSamlsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetApplicationSamlsArgs)(nil)).Elem()
}

// A collection of values returned by getApplicationSamls.
type GetApplicationSamlsResultOutput struct{ *pulumi.OutputState }

func (GetApplicationSamlsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetApplicationSamlsResult)(nil)).Elem()
}

func (o GetApplicationSamlsResultOutput) ToGetApplicationSamlsResultOutput() GetApplicationSamlsResultOutput {
	return o
}

func (o GetApplicationSamlsResultOutput) ToGetApplicationSamlsResultOutputWithContext(ctx context.Context) GetApplicationSamlsResultOutput {
	return o
}

// A set of all IDs.
func (o GetApplicationSamlsResultOutput) AppIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetApplicationSamlsResult) []string { return v.AppIds }).(pulumi.StringArrayOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetApplicationSamlsResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetApplicationSamlsResult) string { return v.Id }).(pulumi.StringOutput)
}

// Name of the application
func (o GetApplicationSamlsResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetApplicationSamlsResult) string { return v.Name }).(pulumi.StringOutput)
}

// Method for querying applications by name, supported values: TEXT*QUERY*METHOD*EQUALS, TEXT*QUERY*METHOD*EQUALS*IGNORE*CASE, TEXT*QUERY*METHOD*STARTS*WITH, TEXT*QUERY*METHOD*STARTS*WITH*IGNORE*CASE, TEXT*QUERY*METHOD*CONTAINS, TEXT*QUERY*METHOD*CONTAINS*IGNORE*CASE, TEXT*QUERY*METHOD*ENDS*WITH, TEXT*QUERY*METHOD*ENDS*WITH*IGNORE*CASE
func (o GetApplicationSamlsResultOutput) NameMethod() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetApplicationSamlsResult) *string { return v.NameMethod }).(pulumi.StringPtrOutput)
}

// ID of the organization
func (o GetApplicationSamlsResultOutput) OrgId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetApplicationSamlsResult) *string { return v.OrgId }).(pulumi.StringPtrOutput)
}

// ID of the project
func (o GetApplicationSamlsResultOutput) ProjectId() pulumi.StringOutput {
	return o.ApplyT(func(v GetApplicationSamlsResult) string { return v.ProjectId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetApplicationSamlsResultOutput{})
}
