// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package zitadel

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/truvity/pulumi-zitadel/sdk/go/zitadel/internal"
)

// Datasource representing a secret generator configuration.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/truvity/pulumi-zitadel/sdk/go/zitadel"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := zitadel.GetInstanceSecretGenerator(ctx, &zitadel.LookupInstanceSecretGeneratorArgs{
//				GeneratorType: "password_reset_code",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func LookupInstanceSecretGenerator(ctx *pulumi.Context, args *LookupInstanceSecretGeneratorArgs, opts ...pulumi.InvokeOption) (*LookupInstanceSecretGeneratorResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupInstanceSecretGeneratorResult
	err := ctx.Invoke("zitadel:index/getInstanceSecretGenerator:getInstanceSecretGenerator", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getInstanceSecretGenerator.
type LookupInstanceSecretGeneratorArgs struct {
	// Type of the secret generator, supported values: app*secret, init*code, otp*email, otp*sms, password*reset*code, passwordless*init*code, verify*email*code, verify*phone*code
	GeneratorType string `pulumi:"generatorType"`
}

// A collection of values returned by getInstanceSecretGenerator.
type LookupInstanceSecretGeneratorResult struct {
	// Expiry duration of the generated secret, e.g. 1h, 15m, 24h
	Expiry string `pulumi:"expiry"`
	// Type of the secret generator, supported values: app*secret, init*code, otp*email, otp*sms, password*reset*code, passwordless*init*code, verify*email*code, verify*phone*code
	GeneratorType string `pulumi:"generatorType"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// Include digits in the generated secret
	IncludeDigits bool `pulumi:"includeDigits"`
	// Include lowercase letters in the generated secret
	IncludeLowerLetters bool `pulumi:"includeLowerLetters"`
	// Include symbols in the generated secret
	IncludeSymbols bool `pulumi:"includeSymbols"`
	// Include uppercase letters in the generated secret
	IncludeUpperLetters bool `pulumi:"includeUpperLetters"`
	// Length of the generated secret
	Length int `pulumi:"length"`
}

func LookupInstanceSecretGeneratorOutput(ctx *pulumi.Context, args LookupInstanceSecretGeneratorOutputArgs, opts ...pulumi.InvokeOption) LookupInstanceSecretGeneratorResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupInstanceSecretGeneratorResultOutput, error) {
			args := v.(LookupInstanceSecretGeneratorArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("zitadel:index/getInstanceSecretGenerator:getInstanceSecretGenerator", args, LookupInstanceSecretGeneratorResultOutput{}, options).(LookupInstanceSecretGeneratorResultOutput), nil
		}).(LookupInstanceSecretGeneratorResultOutput)
}

// A collection of arguments for invoking getInstanceSecretGenerator.
type LookupInstanceSecretGeneratorOutputArgs struct {
	// Type of the secret generator, supported values: app*secret, init*code, otp*email, otp*sms, password*reset*code, passwordless*init*code, verify*email*code, verify*phone*code
	GeneratorType pulumi.StringInput `pulumi:"generatorType"`
}

func (LookupInstanceSecretGeneratorOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupInstanceSecretGeneratorArgs)(nil)).Elem()
}

// A collection of values returned by getInstanceSecretGenerator.
type LookupInstanceSecretGeneratorResultOutput struct{ *pulumi.OutputState }

func (LookupInstanceSecretGeneratorResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupInstanceSecretGeneratorResult)(nil)).Elem()
}

func (o LookupInstanceSecretGeneratorResultOutput) ToLookupInstanceSecretGeneratorResultOutput() LookupInstanceSecretGeneratorResultOutput {
	return o
}

func (o LookupInstanceSecretGeneratorResultOutput) ToLookupInstanceSecretGeneratorResultOutputWithContext(ctx context.Context) LookupInstanceSecretGeneratorResultOutput {
	return o
}

// Expiry duration of the generated secret, e.g. 1h, 15m, 24h
func (o LookupInstanceSecretGeneratorResultOutput) Expiry() pulumi.StringOutput {
	return o.ApplyT(func(v LookupInstanceSecretGeneratorResult) string { return v.Expiry }).(pulumi.StringOutput)
}

// Type of the secret generator, supported values: app*secret, init*code, otp*email, otp*sms, password*reset*code, passwordless*init*code, verify*email*code, verify*phone*code
func (o LookupInstanceSecretGeneratorResultOutput) GeneratorType() pulumi.StringOutput {
	return o.ApplyT(func(v LookupInstanceSecretGeneratorResult) string { return v.GeneratorType }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupInstanceSecretGeneratorResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupInstanceSecretGeneratorResult) string { return v.Id }).(pulumi.StringOutput)
}

// Include digits in the generated secret
func (o LookupInstanceSecretGeneratorResultOutput) IncludeDigits() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupInstanceSecretGeneratorResult) bool { return v.IncludeDigits }).(pulumi.BoolOutput)
}

// Include lowercase letters in the generated secret
func (o LookupInstanceSecretGeneratorResultOutput) IncludeLowerLetters() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupInstanceSecretGeneratorResult) bool { return v.IncludeLowerLetters }).(pulumi.BoolOutput)
}

// Include symbols in the generated secret
func (o LookupInstanceSecretGeneratorResultOutput) IncludeSymbols() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupInstanceSecretGeneratorResult) bool { return v.IncludeSymbols }).(pulumi.BoolOutput)
}

// Include uppercase letters in the generated secret
func (o LookupInstanceSecretGeneratorResultOutput) IncludeUpperLetters() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupInstanceSecretGeneratorResult) bool { return v.IncludeUpperLetters }).(pulumi.BoolOutput)
}

// Length of the generated secret
func (o LookupInstanceSecretGeneratorResultOutput) Length() pulumi.IntOutput {
	return o.ApplyT(func(v LookupInstanceSecretGeneratorResult) int { return v.Length }).(pulumi.IntOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupInstanceSecretGeneratorResultOutput{})
}
