// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package zitadel

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/truvity/pulumi-zitadel/sdk/go/zitadel/internal"
)

// Datasource representing the list of trusted domains configured for a ZITADEL instance.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/truvity/pulumi-zitadel/sdk/go/zitadel"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_default, err := zitadel.GetInstanceTrustedDomains(ctx, &zitadel.GetInstanceTrustedDomainsArgs{}, nil)
//			if err != nil {
//				return err
//			}
//			ctx.Export("trustedDomains", _default.Domains)
//			return nil
//		})
//	}
//
// ```
func GetInstanceTrustedDomains(ctx *pulumi.Context, args *GetInstanceTrustedDomainsArgs, opts ...pulumi.InvokeOption) (*GetInstanceTrustedDomainsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetInstanceTrustedDomainsResult
	err := ctx.Invoke("zitadel:index/getInstanceTrustedDomains:getInstanceTrustedDomains", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getInstanceTrustedDomains.
type GetInstanceTrustedDomainsArgs struct {
	// The ID of the instance. If not provided, the instance from the current context (e.g., identified by the host header) will be used.
	InstanceId *string `pulumi:"instanceId"`
}

// A collection of values returned by getInstanceTrustedDomains.
type GetInstanceTrustedDomainsResult struct {
	// List of trusted domain names
	Domains []string `pulumi:"domains"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// The ID of the instance. If not provided, the instance from the current context (e.g., identified by the host header) will be used.
	InstanceId *string `pulumi:"instanceId"`
}

func GetInstanceTrustedDomainsOutput(ctx *pulumi.Context, args GetInstanceTrustedDomainsOutputArgs, opts ...pulumi.InvokeOption) GetInstanceTrustedDomainsResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetInstanceTrustedDomainsResultOutput, error) {
			args := v.(GetInstanceTrustedDomainsArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("zitadel:index/getInstanceTrustedDomains:getInstanceTrustedDomains", args, GetInstanceTrustedDomainsResultOutput{}, options).(GetInstanceTrustedDomainsResultOutput), nil
		}).(GetInstanceTrustedDomainsResultOutput)
}

// A collection of arguments for invoking getInstanceTrustedDomains.
type GetInstanceTrustedDomainsOutputArgs struct {
	// The ID of the instance. If not provided, the instance from the current context (e.g., identified by the host header) will be used.
	InstanceId pulumi.StringPtrInput `pulumi:"instanceId"`
}

func (GetInstanceTrustedDomainsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetInstanceTrustedDomainsArgs)(nil)).Elem()
}

// A collection of values returned by getInstanceTrustedDomains.
type GetInstanceTrustedDomainsResultOutput struct{ *pulumi.OutputState }

func (GetInstanceTrustedDomainsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetInstanceTrustedDomainsResult)(nil)).Elem()
}

func (o GetInstanceTrustedDomainsResultOutput) ToGetInstanceTrustedDomainsResultOutput() GetInstanceTrustedDomainsResultOutput {
	return o
}

func (o GetInstanceTrustedDomainsResultOutput) ToGetInstanceTrustedDomainsResultOutputWithContext(ctx context.Context) GetInstanceTrustedDomainsResultOutput {
	return o
}

// List of trusted domain names
func (o GetInstanceTrustedDomainsResultOutput) Domains() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetInstanceTrustedDomainsResult) []string { return v.Domains }).(pulumi.StringArrayOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetInstanceTrustedDomainsResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetInstanceTrustedDomainsResult) string { return v.Id }).(pulumi.StringOutput)
}

// The ID of the instance. If not provided, the instance from the current context (e.g., identified by the host header) will be used.
func (o GetInstanceTrustedDomainsResultOutput) InstanceId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetInstanceTrustedDomainsResult) *string { return v.InstanceId }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(GetInstanceTrustedDomainsResultOutput{})
}
