// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package zitadel

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/truvity/pulumi-zitadel/sdk/go/zitadel/internal"
)

// Datasource representing an Apple IDP on the instance.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/truvity/pulumi-zitadel/sdk/go/zitadel"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := zitadel.GetIdpApple(ctx, &zitadel.LookupIdpAppleArgs{
//				Id: "123456789012345678",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func LookupIdpApple(ctx *pulumi.Context, args *LookupIdpAppleArgs, opts ...pulumi.InvokeOption) (*LookupIdpAppleResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupIdpAppleResult
	err := ctx.Invoke("zitadel:index/getIdpApple:getIdpApple", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getIdpApple.
type LookupIdpAppleArgs struct {
	// The ID of this resource.
	Id string `pulumi:"id"`
}

// A collection of values returned by getIdpApple.
type LookupIdpAppleResult struct {
	// Enable if users should get prompted to link an existing ZITADEL user to an external account if the selected attribute matches, supported values: AUTO*LINKING*OPTION*UNSPECIFIED, AUTO*LINKING*OPTION*USERNAME, AUTO*LINKING*OPTION_EMAIL
	AutoLinking string `pulumi:"autoLinking"`
	// client id generated by the identity provider
	ClientId string `pulumi:"clientId"`
	// The ID of this resource.
	Id string `pulumi:"id"`
	// enabled if a new account in ZITADEL are created automatically on login with an external account
	IsAutoCreation bool `pulumi:"isAutoCreation"`
	// enabled if a the ZITADEL account fields are updated automatically on each login
	IsAutoUpdate bool `pulumi:"isAutoUpdate"`
	// enabled if users are able to create a new account in ZITADEL when using an external account
	IsCreationAllowed bool `pulumi:"isCreationAllowed"`
	// enabled if users are able to link an existing ZITADEL user with an external account
	IsLinkingAllowed bool `pulumi:"isLinkingAllowed"`
	// Apple Key ID from your Apple Developer Account
	KeyId string `pulumi:"keyId"`
	// Name of the IDP
	Name string `pulumi:"name"`
	// the scopes requested by ZITADEL during the request on the identity provider
	Scopes []string `pulumi:"scopes"`
	// Apple Team ID from your Apple Developer Account
	TeamId string `pulumi:"teamId"`
}

func LookupIdpAppleOutput(ctx *pulumi.Context, args LookupIdpAppleOutputArgs, opts ...pulumi.InvokeOption) LookupIdpAppleResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupIdpAppleResultOutput, error) {
			args := v.(LookupIdpAppleArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("zitadel:index/getIdpApple:getIdpApple", args, LookupIdpAppleResultOutput{}, options).(LookupIdpAppleResultOutput), nil
		}).(LookupIdpAppleResultOutput)
}

// A collection of arguments for invoking getIdpApple.
type LookupIdpAppleOutputArgs struct {
	// The ID of this resource.
	Id pulumi.StringInput `pulumi:"id"`
}

func (LookupIdpAppleOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupIdpAppleArgs)(nil)).Elem()
}

// A collection of values returned by getIdpApple.
type LookupIdpAppleResultOutput struct{ *pulumi.OutputState }

func (LookupIdpAppleResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupIdpAppleResult)(nil)).Elem()
}

func (o LookupIdpAppleResultOutput) ToLookupIdpAppleResultOutput() LookupIdpAppleResultOutput {
	return o
}

func (o LookupIdpAppleResultOutput) ToLookupIdpAppleResultOutputWithContext(ctx context.Context) LookupIdpAppleResultOutput {
	return o
}

// Enable if users should get prompted to link an existing ZITADEL user to an external account if the selected attribute matches, supported values: AUTO*LINKING*OPTION*UNSPECIFIED, AUTO*LINKING*OPTION*USERNAME, AUTO*LINKING*OPTION_EMAIL
func (o LookupIdpAppleResultOutput) AutoLinking() pulumi.StringOutput {
	return o.ApplyT(func(v LookupIdpAppleResult) string { return v.AutoLinking }).(pulumi.StringOutput)
}

// client id generated by the identity provider
func (o LookupIdpAppleResultOutput) ClientId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupIdpAppleResult) string { return v.ClientId }).(pulumi.StringOutput)
}

// The ID of this resource.
func (o LookupIdpAppleResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupIdpAppleResult) string { return v.Id }).(pulumi.StringOutput)
}

// enabled if a new account in ZITADEL are created automatically on login with an external account
func (o LookupIdpAppleResultOutput) IsAutoCreation() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupIdpAppleResult) bool { return v.IsAutoCreation }).(pulumi.BoolOutput)
}

// enabled if a the ZITADEL account fields are updated automatically on each login
func (o LookupIdpAppleResultOutput) IsAutoUpdate() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupIdpAppleResult) bool { return v.IsAutoUpdate }).(pulumi.BoolOutput)
}

// enabled if users are able to create a new account in ZITADEL when using an external account
func (o LookupIdpAppleResultOutput) IsCreationAllowed() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupIdpAppleResult) bool { return v.IsCreationAllowed }).(pulumi.BoolOutput)
}

// enabled if users are able to link an existing ZITADEL user with an external account
func (o LookupIdpAppleResultOutput) IsLinkingAllowed() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupIdpAppleResult) bool { return v.IsLinkingAllowed }).(pulumi.BoolOutput)
}

// Apple Key ID from your Apple Developer Account
func (o LookupIdpAppleResultOutput) KeyId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupIdpAppleResult) string { return v.KeyId }).(pulumi.StringOutput)
}

// Name of the IDP
func (o LookupIdpAppleResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupIdpAppleResult) string { return v.Name }).(pulumi.StringOutput)
}

// the scopes requested by ZITADEL during the request on the identity provider
func (o LookupIdpAppleResultOutput) Scopes() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupIdpAppleResult) []string { return v.Scopes }).(pulumi.StringArrayOutput)
}

// Apple Team ID from your Apple Developer Account
func (o LookupIdpAppleResultOutput) TeamId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupIdpAppleResult) string { return v.TeamId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupIdpAppleResultOutput{})
}
