// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package zitadel

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/truvity/pulumi-zitadel/sdk/go/zitadel/internal"
)

// Datasource representing the list of custom domains configured for a ZITADEL instance.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/truvity/pulumi-zitadel/sdk/go/zitadel"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_default, err := zitadel.GetInstanceCustomDomains(ctx, &zitadel.GetInstanceCustomDomainsArgs{}, nil)
//			if err != nil {
//				return err
//			}
//			ctx.Export("customDomains", _default.Domains)
//			return nil
//		})
//	}
//
// ```
func GetInstanceCustomDomains(ctx *pulumi.Context, args *GetInstanceCustomDomainsArgs, opts ...pulumi.InvokeOption) (*GetInstanceCustomDomainsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetInstanceCustomDomainsResult
	err := ctx.Invoke("zitadel:index/getInstanceCustomDomains:getInstanceCustomDomains", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getInstanceCustomDomains.
type GetInstanceCustomDomainsArgs struct {
	// The ID of the instance. If not provided, the instance from the current context (e.g., identified by the host header) will be used.
	InstanceId *string `pulumi:"instanceId"`
}

// A collection of values returned by getInstanceCustomDomains.
type GetInstanceCustomDomainsResult struct {
	// List of custom domain names
	Domains []string `pulumi:"domains"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// The ID of the instance. If not provided, the instance from the current context (e.g., identified by the host header) will be used.
	InstanceId *string `pulumi:"instanceId"`
}

func GetInstanceCustomDomainsOutput(ctx *pulumi.Context, args GetInstanceCustomDomainsOutputArgs, opts ...pulumi.InvokeOption) GetInstanceCustomDomainsResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetInstanceCustomDomainsResultOutput, error) {
			args := v.(GetInstanceCustomDomainsArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("zitadel:index/getInstanceCustomDomains:getInstanceCustomDomains", args, GetInstanceCustomDomainsResultOutput{}, options).(GetInstanceCustomDomainsResultOutput), nil
		}).(GetInstanceCustomDomainsResultOutput)
}

// A collection of arguments for invoking getInstanceCustomDomains.
type GetInstanceCustomDomainsOutputArgs struct {
	// The ID of the instance. If not provided, the instance from the current context (e.g., identified by the host header) will be used.
	InstanceId pulumi.StringPtrInput `pulumi:"instanceId"`
}

func (GetInstanceCustomDomainsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetInstanceCustomDomainsArgs)(nil)).Elem()
}

// A collection of values returned by getInstanceCustomDomains.
type GetInstanceCustomDomainsResultOutput struct{ *pulumi.OutputState }

func (GetInstanceCustomDomainsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetInstanceCustomDomainsResult)(nil)).Elem()
}

func (o GetInstanceCustomDomainsResultOutput) ToGetInstanceCustomDomainsResultOutput() GetInstanceCustomDomainsResultOutput {
	return o
}

func (o GetInstanceCustomDomainsResultOutput) ToGetInstanceCustomDomainsResultOutputWithContext(ctx context.Context) GetInstanceCustomDomainsResultOutput {
	return o
}

// List of custom domain names
func (o GetInstanceCustomDomainsResultOutput) Domains() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetInstanceCustomDomainsResult) []string { return v.Domains }).(pulumi.StringArrayOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetInstanceCustomDomainsResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetInstanceCustomDomainsResult) string { return v.Id }).(pulumi.StringOutput)
}

// The ID of the instance. If not provided, the instance from the current context (e.g., identified by the host header) will be used.
func (o GetInstanceCustomDomainsResultOutput) InstanceId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetInstanceCustomDomainsResult) *string { return v.InstanceId }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(GetInstanceCustomDomainsResultOutput{})
}
