// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package zitadel

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/truvity/pulumi-zitadel/sdk/go/zitadel/internal"
)

// Datasource representing a generic OIDC IdP on the organization.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/truvity/pulumi-zitadel/sdk/go/zitadel"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_default, err := zitadel.GetOrgIdpOidc(ctx, &zitadel.LookupOrgIdpOidcArgs{
//				OrgId: pulumi.StringRef(defaultZitadelOrg.Id),
//				Id:    "123456789012345678",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			ctx.Export("orgIdpOidc", _default)
//			return nil
//		})
//	}
//
// ```
func LookupOrgIdpOidc(ctx *pulumi.Context, args *LookupOrgIdpOidcArgs, opts ...pulumi.InvokeOption) (*LookupOrgIdpOidcResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupOrgIdpOidcResult
	err := ctx.Invoke("zitadel:index/getOrgIdpOidc:getOrgIdpOidc", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getOrgIdpOidc.
type LookupOrgIdpOidcArgs struct {
	// The ID of this resource.
	Id string `pulumi:"id"`
	// ID of the organization
	OrgId *string `pulumi:"orgId"`
}

// A collection of values returned by getOrgIdpOidc.
type LookupOrgIdpOidcResult struct {
	// Enable if users should get prompted to link an existing ZITADEL user to an external account if the selected attribute matches, supported values: AUTO*LINKING*OPTION*UNSPECIFIED, AUTO*LINKING*OPTION*USERNAME, AUTO*LINKING*OPTION_EMAIL
	AutoLinking string `pulumi:"autoLinking"`
	// client id generated by the identity provider
	ClientId string `pulumi:"clientId"`
	// client secret generated by the identity provider
	ClientSecret string `pulumi:"clientSecret"`
	// The ID of this resource.
	Id string `pulumi:"id"`
	// enabled if a new account in ZITADEL are created automatically on login with an external account
	IsAutoCreation bool `pulumi:"isAutoCreation"`
	// enabled if a the ZITADEL account fields are updated automatically on each login
	IsAutoUpdate bool `pulumi:"isAutoUpdate"`
	// enabled if users are able to create a new account in ZITADEL when using an external account
	IsCreationAllowed bool `pulumi:"isCreationAllowed"`
	// if true, provider information get mapped from the id token, not from the userinfo endpoint.
	IsIdTokenMapping bool `pulumi:"isIdTokenMapping"`
	// enabled if users are able to link an existing ZITADEL user with an external account
	IsLinkingAllowed bool `pulumi:"isLinkingAllowed"`
	// the OIDC issuer of the identity provider
	Issuer string `pulumi:"issuer"`
	// Name of the IDP
	Name string `pulumi:"name"`
	// ID of the organization
	OrgId *string `pulumi:"orgId"`
	// the scopes requested by ZITADEL during the request on the identity provider
	Scopes []string `pulumi:"scopes"`
	// Defines if the Proof Key for Code Exchange (PKCE) is used for the authorization code flow.
	UsePkce bool `pulumi:"usePkce"`
}

func LookupOrgIdpOidcOutput(ctx *pulumi.Context, args LookupOrgIdpOidcOutputArgs, opts ...pulumi.InvokeOption) LookupOrgIdpOidcResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupOrgIdpOidcResultOutput, error) {
			args := v.(LookupOrgIdpOidcArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("zitadel:index/getOrgIdpOidc:getOrgIdpOidc", args, LookupOrgIdpOidcResultOutput{}, options).(LookupOrgIdpOidcResultOutput), nil
		}).(LookupOrgIdpOidcResultOutput)
}

// A collection of arguments for invoking getOrgIdpOidc.
type LookupOrgIdpOidcOutputArgs struct {
	// The ID of this resource.
	Id pulumi.StringInput `pulumi:"id"`
	// ID of the organization
	OrgId pulumi.StringPtrInput `pulumi:"orgId"`
}

func (LookupOrgIdpOidcOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupOrgIdpOidcArgs)(nil)).Elem()
}

// A collection of values returned by getOrgIdpOidc.
type LookupOrgIdpOidcResultOutput struct{ *pulumi.OutputState }

func (LookupOrgIdpOidcResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupOrgIdpOidcResult)(nil)).Elem()
}

func (o LookupOrgIdpOidcResultOutput) ToLookupOrgIdpOidcResultOutput() LookupOrgIdpOidcResultOutput {
	return o
}

func (o LookupOrgIdpOidcResultOutput) ToLookupOrgIdpOidcResultOutputWithContext(ctx context.Context) LookupOrgIdpOidcResultOutput {
	return o
}

// Enable if users should get prompted to link an existing ZITADEL user to an external account if the selected attribute matches, supported values: AUTO*LINKING*OPTION*UNSPECIFIED, AUTO*LINKING*OPTION*USERNAME, AUTO*LINKING*OPTION_EMAIL
func (o LookupOrgIdpOidcResultOutput) AutoLinking() pulumi.StringOutput {
	return o.ApplyT(func(v LookupOrgIdpOidcResult) string { return v.AutoLinking }).(pulumi.StringOutput)
}

// client id generated by the identity provider
func (o LookupOrgIdpOidcResultOutput) ClientId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupOrgIdpOidcResult) string { return v.ClientId }).(pulumi.StringOutput)
}

// client secret generated by the identity provider
func (o LookupOrgIdpOidcResultOutput) ClientSecret() pulumi.StringOutput {
	return o.ApplyT(func(v LookupOrgIdpOidcResult) string { return v.ClientSecret }).(pulumi.StringOutput)
}

// The ID of this resource.
func (o LookupOrgIdpOidcResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupOrgIdpOidcResult) string { return v.Id }).(pulumi.StringOutput)
}

// enabled if a new account in ZITADEL are created automatically on login with an external account
func (o LookupOrgIdpOidcResultOutput) IsAutoCreation() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupOrgIdpOidcResult) bool { return v.IsAutoCreation }).(pulumi.BoolOutput)
}

// enabled if a the ZITADEL account fields are updated automatically on each login
func (o LookupOrgIdpOidcResultOutput) IsAutoUpdate() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupOrgIdpOidcResult) bool { return v.IsAutoUpdate }).(pulumi.BoolOutput)
}

// enabled if users are able to create a new account in ZITADEL when using an external account
func (o LookupOrgIdpOidcResultOutput) IsCreationAllowed() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupOrgIdpOidcResult) bool { return v.IsCreationAllowed }).(pulumi.BoolOutput)
}

// if true, provider information get mapped from the id token, not from the userinfo endpoint.
func (o LookupOrgIdpOidcResultOutput) IsIdTokenMapping() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupOrgIdpOidcResult) bool { return v.IsIdTokenMapping }).(pulumi.BoolOutput)
}

// enabled if users are able to link an existing ZITADEL user with an external account
func (o LookupOrgIdpOidcResultOutput) IsLinkingAllowed() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupOrgIdpOidcResult) bool { return v.IsLinkingAllowed }).(pulumi.BoolOutput)
}

// the OIDC issuer of the identity provider
func (o LookupOrgIdpOidcResultOutput) Issuer() pulumi.StringOutput {
	return o.ApplyT(func(v LookupOrgIdpOidcResult) string { return v.Issuer }).(pulumi.StringOutput)
}

// Name of the IDP
func (o LookupOrgIdpOidcResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupOrgIdpOidcResult) string { return v.Name }).(pulumi.StringOutput)
}

// ID of the organization
func (o LookupOrgIdpOidcResultOutput) OrgId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupOrgIdpOidcResult) *string { return v.OrgId }).(pulumi.StringPtrOutput)
}

// the scopes requested by ZITADEL during the request on the identity provider
func (o LookupOrgIdpOidcResultOutput) Scopes() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupOrgIdpOidcResult) []string { return v.Scopes }).(pulumi.StringArrayOutput)
}

// Defines if the Proof Key for Code Exchange (PKCE) is used for the authorization code flow.
func (o LookupOrgIdpOidcResultOutput) UsePkce() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupOrgIdpOidcResult) bool { return v.UsePkce }).(pulumi.BoolOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupOrgIdpOidcResultOutput{})
}
