// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package zitadel

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/truvity/pulumi-zitadel/sdk/go/zitadel/internal"
)

// Datasource representing domains of an organization in ZITADEL.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/truvity/pulumi-zitadel/sdk/go/zitadel"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_default, err := zitadel.GetOrganizationDomains(ctx, &zitadel.GetOrganizationDomainsArgs{
//				OrganizationId: "123456789012345678",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			_, err = zitadel.GetOrganizationDomains(ctx, &zitadel.GetOrganizationDomainsArgs{
//				OrganizationId: "123456789012345678",
//				Domain:         pulumi.StringRef("example.com"),
//			}, nil)
//			if err != nil {
//				return err
//			}
//			ctx.Export("allDomains", _default.Domains)
//			return nil
//		})
//	}
//
// ```
func GetOrganizationDomains(ctx *pulumi.Context, args *GetOrganizationDomainsArgs, opts ...pulumi.InvokeOption) (*GetOrganizationDomainsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetOrganizationDomainsResult
	err := ctx.Invoke("zitadel:index/getOrganizationDomains:getOrganizationDomains", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getOrganizationDomains.
type GetOrganizationDomainsArgs struct {
	// Filter domains by name
	Domain *string `pulumi:"domain"`
	// ID of the organization
	OrganizationId string `pulumi:"organizationId"`
}

// A collection of values returned by getOrganizationDomains.
type GetOrganizationDomainsResult struct {
	// Filter domains by name
	Domain *string `pulumi:"domain"`
	// List of organization domains
	Domains []GetOrganizationDomainsDomain `pulumi:"domains"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// ID of the organization
	OrganizationId string `pulumi:"organizationId"`
}

func GetOrganizationDomainsOutput(ctx *pulumi.Context, args GetOrganizationDomainsOutputArgs, opts ...pulumi.InvokeOption) GetOrganizationDomainsResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetOrganizationDomainsResultOutput, error) {
			args := v.(GetOrganizationDomainsArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("zitadel:index/getOrganizationDomains:getOrganizationDomains", args, GetOrganizationDomainsResultOutput{}, options).(GetOrganizationDomainsResultOutput), nil
		}).(GetOrganizationDomainsResultOutput)
}

// A collection of arguments for invoking getOrganizationDomains.
type GetOrganizationDomainsOutputArgs struct {
	// Filter domains by name
	Domain pulumi.StringPtrInput `pulumi:"domain"`
	// ID of the organization
	OrganizationId pulumi.StringInput `pulumi:"organizationId"`
}

func (GetOrganizationDomainsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetOrganizationDomainsArgs)(nil)).Elem()
}

// A collection of values returned by getOrganizationDomains.
type GetOrganizationDomainsResultOutput struct{ *pulumi.OutputState }

func (GetOrganizationDomainsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetOrganizationDomainsResult)(nil)).Elem()
}

func (o GetOrganizationDomainsResultOutput) ToGetOrganizationDomainsResultOutput() GetOrganizationDomainsResultOutput {
	return o
}

func (o GetOrganizationDomainsResultOutput) ToGetOrganizationDomainsResultOutputWithContext(ctx context.Context) GetOrganizationDomainsResultOutput {
	return o
}

// Filter domains by name
func (o GetOrganizationDomainsResultOutput) Domain() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetOrganizationDomainsResult) *string { return v.Domain }).(pulumi.StringPtrOutput)
}

// List of organization domains
func (o GetOrganizationDomainsResultOutput) Domains() GetOrganizationDomainsDomainArrayOutput {
	return o.ApplyT(func(v GetOrganizationDomainsResult) []GetOrganizationDomainsDomain { return v.Domains }).(GetOrganizationDomainsDomainArrayOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetOrganizationDomainsResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetOrganizationDomainsResult) string { return v.Id }).(pulumi.StringOutput)
}

// ID of the organization
func (o GetOrganizationDomainsResultOutput) OrganizationId() pulumi.StringOutput {
	return o.ApplyT(func(v GetOrganizationDomainsResult) string { return v.OrganizationId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetOrganizationDomainsResultOutput{})
}
