// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package zitadel

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/truvity/pulumi-zitadel/sdk/go/zitadel/internal"
)

// Datasource representing a domain of an organization in ZITADEL.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/truvity/pulumi-zitadel/sdk/go/zitadel"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_default, err := zitadel.GetOrganizationDomain(ctx, &zitadel.LookupOrganizationDomainArgs{
//				OrganizationId: "123456789012345678",
//				Domain:         "example.com",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			ctx.Export("domainVerified", _default.IsVerified)
//			return nil
//		})
//	}
//
// ```
func LookupOrganizationDomain(ctx *pulumi.Context, args *LookupOrganizationDomainArgs, opts ...pulumi.InvokeOption) (*LookupOrganizationDomainResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupOrganizationDomainResult
	err := ctx.Invoke("zitadel:index/getOrganizationDomain:getOrganizationDomain", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getOrganizationDomain.
type LookupOrganizationDomainArgs struct {
	// Domain name
	Domain string `pulumi:"domain"`
	// ID of the organization
	OrganizationId string `pulumi:"organizationId"`
}

// A collection of values returned by getOrganizationDomain.
type LookupOrganizationDomainResult struct {
	// Domain name
	Domain string `pulumi:"domain"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// Whether this is the primary domain of the organization
	IsPrimary bool `pulumi:"isPrimary"`
	// Whether the domain has been verified
	IsVerified bool `pulumi:"isVerified"`
	// ID of the organization
	OrganizationId string `pulumi:"organizationId"`
	// Type of domain validation, supported values: DOMAIN*VALIDATION*TYPE*UNSPECIFIED, DOMAIN*VALIDATION*TYPE*HTTP, DOMAIN*VALIDATION*TYPE_DNS
	ValidationType string `pulumi:"validationType"`
}

func LookupOrganizationDomainOutput(ctx *pulumi.Context, args LookupOrganizationDomainOutputArgs, opts ...pulumi.InvokeOption) LookupOrganizationDomainResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupOrganizationDomainResultOutput, error) {
			args := v.(LookupOrganizationDomainArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("zitadel:index/getOrganizationDomain:getOrganizationDomain", args, LookupOrganizationDomainResultOutput{}, options).(LookupOrganizationDomainResultOutput), nil
		}).(LookupOrganizationDomainResultOutput)
}

// A collection of arguments for invoking getOrganizationDomain.
type LookupOrganizationDomainOutputArgs struct {
	// Domain name
	Domain pulumi.StringInput `pulumi:"domain"`
	// ID of the organization
	OrganizationId pulumi.StringInput `pulumi:"organizationId"`
}

func (LookupOrganizationDomainOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupOrganizationDomainArgs)(nil)).Elem()
}

// A collection of values returned by getOrganizationDomain.
type LookupOrganizationDomainResultOutput struct{ *pulumi.OutputState }

func (LookupOrganizationDomainResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupOrganizationDomainResult)(nil)).Elem()
}

func (o LookupOrganizationDomainResultOutput) ToLookupOrganizationDomainResultOutput() LookupOrganizationDomainResultOutput {
	return o
}

func (o LookupOrganizationDomainResultOutput) ToLookupOrganizationDomainResultOutputWithContext(ctx context.Context) LookupOrganizationDomainResultOutput {
	return o
}

// Domain name
func (o LookupOrganizationDomainResultOutput) Domain() pulumi.StringOutput {
	return o.ApplyT(func(v LookupOrganizationDomainResult) string { return v.Domain }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupOrganizationDomainResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupOrganizationDomainResult) string { return v.Id }).(pulumi.StringOutput)
}

// Whether this is the primary domain of the organization
func (o LookupOrganizationDomainResultOutput) IsPrimary() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupOrganizationDomainResult) bool { return v.IsPrimary }).(pulumi.BoolOutput)
}

// Whether the domain has been verified
func (o LookupOrganizationDomainResultOutput) IsVerified() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupOrganizationDomainResult) bool { return v.IsVerified }).(pulumi.BoolOutput)
}

// ID of the organization
func (o LookupOrganizationDomainResultOutput) OrganizationId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupOrganizationDomainResult) string { return v.OrganizationId }).(pulumi.StringOutput)
}

// Type of domain validation, supported values: DOMAIN*VALIDATION*TYPE*UNSPECIFIED, DOMAIN*VALIDATION*TYPE*HTTP, DOMAIN*VALIDATION*TYPE_DNS
func (o LookupOrganizationDomainResultOutput) ValidationType() pulumi.StringOutput {
	return o.ApplyT(func(v LookupOrganizationDomainResult) string { return v.ValidationType }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupOrganizationDomainResultOutput{})
}
