// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package zitadel

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/truvity/pulumi-zitadel/sdk/go/zitadel/internal"
)

// Datasource representing the project, which can then be granted to different organizations or users directly, containing different applications.
//
// ## Example Usage
func GetProjectsV2(ctx *pulumi.Context, args *GetProjectsV2Args, opts ...pulumi.InvokeOption) (*GetProjectsV2Result, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetProjectsV2Result
	err := ctx.Invoke("zitadel:index/getProjectsV2:getProjectsV2", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getProjectsV2.
type GetProjectsV2Args struct {
	// Name of the project
	Name string `pulumi:"name"`
	// Method for querying projects by name, supported values: TEXT*QUERY*METHOD*EQUALS, TEXT*QUERY*METHOD*EQUALS*IGNORE*CASE, TEXT*QUERY*METHOD*STARTS*WITH, TEXT*QUERY*METHOD*STARTS*WITH*IGNORE*CASE, TEXT*QUERY*METHOD*CONTAINS, TEXT*QUERY*METHOD*CONTAINS*IGNORE*CASE, TEXT*QUERY*METHOD*ENDS*WITH, TEXT*QUERY*METHOD*ENDS*WITH*IGNORE*CASE
	NameMethod *string `pulumi:"nameMethod"`
	// ID of the organization
	OrgId *string `pulumi:"orgId"`
}

// A collection of values returned by getProjectsV2.
type GetProjectsV2Result struct {
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// Name of the project
	Name string `pulumi:"name"`
	// Method for querying projects by name, supported values: TEXT*QUERY*METHOD*EQUALS, TEXT*QUERY*METHOD*EQUALS*IGNORE*CASE, TEXT*QUERY*METHOD*STARTS*WITH, TEXT*QUERY*METHOD*STARTS*WITH*IGNORE*CASE, TEXT*QUERY*METHOD*CONTAINS, TEXT*QUERY*METHOD*CONTAINS*IGNORE*CASE, TEXT*QUERY*METHOD*ENDS*WITH, TEXT*QUERY*METHOD*ENDS*WITH*IGNORE*CASE
	NameMethod *string `pulumi:"nameMethod"`
	// ID of the organization
	OrgId *string `pulumi:"orgId"`
	// IDs of the projects matching the name filter.
	ProjectIds []string `pulumi:"projectIds"`
}

func GetProjectsV2Output(ctx *pulumi.Context, args GetProjectsV2OutputArgs, opts ...pulumi.InvokeOption) GetProjectsV2ResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetProjectsV2ResultOutput, error) {
			args := v.(GetProjectsV2Args)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("zitadel:index/getProjectsV2:getProjectsV2", args, GetProjectsV2ResultOutput{}, options).(GetProjectsV2ResultOutput), nil
		}).(GetProjectsV2ResultOutput)
}

// A collection of arguments for invoking getProjectsV2.
type GetProjectsV2OutputArgs struct {
	// Name of the project
	Name pulumi.StringInput `pulumi:"name"`
	// Method for querying projects by name, supported values: TEXT*QUERY*METHOD*EQUALS, TEXT*QUERY*METHOD*EQUALS*IGNORE*CASE, TEXT*QUERY*METHOD*STARTS*WITH, TEXT*QUERY*METHOD*STARTS*WITH*IGNORE*CASE, TEXT*QUERY*METHOD*CONTAINS, TEXT*QUERY*METHOD*CONTAINS*IGNORE*CASE, TEXT*QUERY*METHOD*ENDS*WITH, TEXT*QUERY*METHOD*ENDS*WITH*IGNORE*CASE
	NameMethod pulumi.StringPtrInput `pulumi:"nameMethod"`
	// ID of the organization
	OrgId pulumi.StringPtrInput `pulumi:"orgId"`
}

func (GetProjectsV2OutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetProjectsV2Args)(nil)).Elem()
}

// A collection of values returned by getProjectsV2.
type GetProjectsV2ResultOutput struct{ *pulumi.OutputState }

func (GetProjectsV2ResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetProjectsV2Result)(nil)).Elem()
}

func (o GetProjectsV2ResultOutput) ToGetProjectsV2ResultOutput() GetProjectsV2ResultOutput {
	return o
}

func (o GetProjectsV2ResultOutput) ToGetProjectsV2ResultOutputWithContext(ctx context.Context) GetProjectsV2ResultOutput {
	return o
}

// The provider-assigned unique ID for this managed resource.
func (o GetProjectsV2ResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetProjectsV2Result) string { return v.Id }).(pulumi.StringOutput)
}

// Name of the project
func (o GetProjectsV2ResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetProjectsV2Result) string { return v.Name }).(pulumi.StringOutput)
}

// Method for querying projects by name, supported values: TEXT*QUERY*METHOD*EQUALS, TEXT*QUERY*METHOD*EQUALS*IGNORE*CASE, TEXT*QUERY*METHOD*STARTS*WITH, TEXT*QUERY*METHOD*STARTS*WITH*IGNORE*CASE, TEXT*QUERY*METHOD*CONTAINS, TEXT*QUERY*METHOD*CONTAINS*IGNORE*CASE, TEXT*QUERY*METHOD*ENDS*WITH, TEXT*QUERY*METHOD*ENDS*WITH*IGNORE*CASE
func (o GetProjectsV2ResultOutput) NameMethod() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetProjectsV2Result) *string { return v.NameMethod }).(pulumi.StringPtrOutput)
}

// ID of the organization
func (o GetProjectsV2ResultOutput) OrgId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetProjectsV2Result) *string { return v.OrgId }).(pulumi.StringPtrOutput)
}

// IDs of the projects matching the name filter.
func (o GetProjectsV2ResultOutput) ProjectIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetProjectsV2Result) []string { return v.ProjectIds }).(pulumi.StringArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(GetProjectsV2ResultOutput{})
}
