// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package zitadel

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/truvity/pulumi-zitadel/sdk/go/zitadel/internal"
)

// Datasource representing the feature flags configuration for the system.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/truvity/pulumi-zitadel/sdk/go/zitadel"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := zitadel.GetSystemFeatures(ctx, map[string]interface{}{}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func LookupSystemFeatures(ctx *pulumi.Context, opts ...pulumi.InvokeOption) (*LookupSystemFeaturesResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupSystemFeaturesResult
	err := ctx.Invoke("zitadel:index/getSystemFeatures:getSystemFeatures", nil, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of values returned by getSystemFeatures.
type LookupSystemFeaturesResult struct {
	// If the flag is enabled, you'll be able to use the OIDC Back-Channel Logout to be notified in your application about terminated user sessions.
	EnableBackChannelLogout bool `pulumi:"enableBackChannelLogout"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// Improves performance of specified execution paths.
	ImprovedPerformances []string `pulumi:"improvedPerformances"`
	// The login UI will use the settings of the default org (and not from the instance) if no organization context is set
	LoginDefaultOrg bool `pulumi:"loginDefaultOrg"`
	// Specify the login UI for all users and applications regardless of their preference.
	LoginV2s []GetSystemFeaturesLoginV2 `pulumi:"loginV2s"`
	// If the flag is enabled, you'll be able to terminate a single session from the login UI by providing an id*token with a `sid` claim as id*token*hint on the end*session endpoint. Note that currently all sessions from the same user agent (browser) are terminated in the login UI. Sessions managed through the Session API already allow the termination of single sessions.
	OidcSingleV1SessionTermination bool `pulumi:"oidcSingleV1SessionTermination"`
	// Enable the experimental `urn:ietf:params:oauth:grant-type:token-exchange` grant type for the OIDC token endpoint. Token exchange can be used to request tokens with a lesser scope or impersonate other users. See the security policy to allow impersonation on an instance.
	OidcTokenExchange bool `pulumi:"oidcTokenExchange"`
	// Enable a newer, more performant, permission check used for v2 and v3 resource based APIs.
	PermissionCheckV2 bool `pulumi:"permissionCheckV2"`
	// User Schemas allow to manage data schemas of user. If the flag is enabled, you'll be able to use the new API and its features. Note that it is still in an early stage.
	UserSchema bool `pulumi:"userSchema"`
}

func LookupSystemFeaturesOutput(ctx *pulumi.Context, opts ...pulumi.InvokeOption) LookupSystemFeaturesResultOutput {
	return pulumi.ToOutput(0).ApplyT(func(int) (LookupSystemFeaturesResultOutput, error) {
		options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
		return ctx.InvokeOutput("zitadel:index/getSystemFeatures:getSystemFeatures", nil, LookupSystemFeaturesResultOutput{}, options).(LookupSystemFeaturesResultOutput), nil
	}).(LookupSystemFeaturesResultOutput)
}

// A collection of values returned by getSystemFeatures.
type LookupSystemFeaturesResultOutput struct{ *pulumi.OutputState }

func (LookupSystemFeaturesResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupSystemFeaturesResult)(nil)).Elem()
}

func (o LookupSystemFeaturesResultOutput) ToLookupSystemFeaturesResultOutput() LookupSystemFeaturesResultOutput {
	return o
}

func (o LookupSystemFeaturesResultOutput) ToLookupSystemFeaturesResultOutputWithContext(ctx context.Context) LookupSystemFeaturesResultOutput {
	return o
}

// If the flag is enabled, you'll be able to use the OIDC Back-Channel Logout to be notified in your application about terminated user sessions.
func (o LookupSystemFeaturesResultOutput) EnableBackChannelLogout() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupSystemFeaturesResult) bool { return v.EnableBackChannelLogout }).(pulumi.BoolOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupSystemFeaturesResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSystemFeaturesResult) string { return v.Id }).(pulumi.StringOutput)
}

// Improves performance of specified execution paths.
func (o LookupSystemFeaturesResultOutput) ImprovedPerformances() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupSystemFeaturesResult) []string { return v.ImprovedPerformances }).(pulumi.StringArrayOutput)
}

// The login UI will use the settings of the default org (and not from the instance) if no organization context is set
func (o LookupSystemFeaturesResultOutput) LoginDefaultOrg() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupSystemFeaturesResult) bool { return v.LoginDefaultOrg }).(pulumi.BoolOutput)
}

// Specify the login UI for all users and applications regardless of their preference.
func (o LookupSystemFeaturesResultOutput) LoginV2s() GetSystemFeaturesLoginV2ArrayOutput {
	return o.ApplyT(func(v LookupSystemFeaturesResult) []GetSystemFeaturesLoginV2 { return v.LoginV2s }).(GetSystemFeaturesLoginV2ArrayOutput)
}

// If the flag is enabled, you'll be able to terminate a single session from the login UI by providing an id*token with a `sid` claim as id*token*hint on the end*session endpoint. Note that currently all sessions from the same user agent (browser) are terminated in the login UI. Sessions managed through the Session API already allow the termination of single sessions.
func (o LookupSystemFeaturesResultOutput) OidcSingleV1SessionTermination() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupSystemFeaturesResult) bool { return v.OidcSingleV1SessionTermination }).(pulumi.BoolOutput)
}

// Enable the experimental `urn:ietf:params:oauth:grant-type:token-exchange` grant type for the OIDC token endpoint. Token exchange can be used to request tokens with a lesser scope or impersonate other users. See the security policy to allow impersonation on an instance.
func (o LookupSystemFeaturesResultOutput) OidcTokenExchange() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupSystemFeaturesResult) bool { return v.OidcTokenExchange }).(pulumi.BoolOutput)
}

// Enable a newer, more performant, permission check used for v2 and v3 resource based APIs.
func (o LookupSystemFeaturesResultOutput) PermissionCheckV2() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupSystemFeaturesResult) bool { return v.PermissionCheckV2 }).(pulumi.BoolOutput)
}

// User Schemas allow to manage data schemas of user. If the flag is enabled, you'll be able to use the new API and its features. Note that it is still in an early stage.
func (o LookupSystemFeaturesResultOutput) UserSchema() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupSystemFeaturesResult) bool { return v.UserSchema }).(pulumi.BoolOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupSystemFeaturesResultOutput{})
}
