// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package zitadel

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/truvity/pulumi-zitadel/sdk/go/zitadel/internal"
)

// Datasource representing a metadata entry of a user in ZITADEL.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/truvity/pulumi-zitadel/sdk/go/zitadel"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_default, err := zitadel.GetUserMetadata(ctx, &zitadel.LookupUserMetadataArgs{
//				OrgId:  pulumi.StringRef(defaultZitadelOrg.Id),
//				UserId: "123456789012345678",
//				Key:    "example_key",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			ctx.Export("metadataValue", _default.Value)
//			return nil
//		})
//	}
//
// ```
func LookupUserMetadata(ctx *pulumi.Context, args *LookupUserMetadataArgs, opts ...pulumi.InvokeOption) (*LookupUserMetadataResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupUserMetadataResult
	err := ctx.Invoke("zitadel:index/getUserMetadata:getUserMetadata", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getUserMetadata.
type LookupUserMetadataArgs struct {
	// Key of the metadata entry
	Key string `pulumi:"key"`
	// ID of the organization
	OrgId *string `pulumi:"orgId"`
	// ID of the user
	UserId string `pulumi:"userId"`
}

// A collection of values returned by getUserMetadata.
type LookupUserMetadataResult struct {
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// Key of the metadata entry
	Key string `pulumi:"key"`
	// ID of the organization
	OrgId *string `pulumi:"orgId"`
	// ID of the user
	UserId string `pulumi:"userId"`
	// Value of the metadata entry
	Value string `pulumi:"value"`
}

func LookupUserMetadataOutput(ctx *pulumi.Context, args LookupUserMetadataOutputArgs, opts ...pulumi.InvokeOption) LookupUserMetadataResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupUserMetadataResultOutput, error) {
			args := v.(LookupUserMetadataArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("zitadel:index/getUserMetadata:getUserMetadata", args, LookupUserMetadataResultOutput{}, options).(LookupUserMetadataResultOutput), nil
		}).(LookupUserMetadataResultOutput)
}

// A collection of arguments for invoking getUserMetadata.
type LookupUserMetadataOutputArgs struct {
	// Key of the metadata entry
	Key pulumi.StringInput `pulumi:"key"`
	// ID of the organization
	OrgId pulumi.StringPtrInput `pulumi:"orgId"`
	// ID of the user
	UserId pulumi.StringInput `pulumi:"userId"`
}

func (LookupUserMetadataOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupUserMetadataArgs)(nil)).Elem()
}

// A collection of values returned by getUserMetadata.
type LookupUserMetadataResultOutput struct{ *pulumi.OutputState }

func (LookupUserMetadataResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupUserMetadataResult)(nil)).Elem()
}

func (o LookupUserMetadataResultOutput) ToLookupUserMetadataResultOutput() LookupUserMetadataResultOutput {
	return o
}

func (o LookupUserMetadataResultOutput) ToLookupUserMetadataResultOutputWithContext(ctx context.Context) LookupUserMetadataResultOutput {
	return o
}

// The provider-assigned unique ID for this managed resource.
func (o LookupUserMetadataResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupUserMetadataResult) string { return v.Id }).(pulumi.StringOutput)
}

// Key of the metadata entry
func (o LookupUserMetadataResultOutput) Key() pulumi.StringOutput {
	return o.ApplyT(func(v LookupUserMetadataResult) string { return v.Key }).(pulumi.StringOutput)
}

// ID of the organization
func (o LookupUserMetadataResultOutput) OrgId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupUserMetadataResult) *string { return v.OrgId }).(pulumi.StringPtrOutput)
}

// ID of the user
func (o LookupUserMetadataResultOutput) UserId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupUserMetadataResult) string { return v.UserId }).(pulumi.StringOutput)
}

// Value of the metadata entry
func (o LookupUserMetadataResultOutput) Value() pulumi.StringOutput {
	return o.ApplyT(func(v LookupUserMetadataResult) string { return v.Value }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupUserMetadataResultOutput{})
}
