// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package zitadel

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/truvity/pulumi-zitadel/sdk/go/zitadel/internal"
)

// Datasource representing metadata entries of a user in ZITADEL.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/truvity/pulumi-zitadel/sdk/go/zitadel"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_default, err := zitadel.GetUserMetadatas(ctx, &zitadel.GetUserMetadatasArgs{
//				OrgId:  pulumi.StringRef(defaultZitadelOrg.Id),
//				UserId: "123456789012345678",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			_, err = zitadel.GetUserMetadatas(ctx, &zitadel.GetUserMetadatasArgs{
//				OrgId:  pulumi.StringRef(defaultZitadelOrg.Id),
//				UserId: "123456789012345678",
//				Key:    pulumi.StringRef("example"),
//			}, nil)
//			if err != nil {
//				return err
//			}
//			ctx.Export("allMetadata", _default.Metadatas)
//			return nil
//		})
//	}
//
// ```
func GetUserMetadatas(ctx *pulumi.Context, args *GetUserMetadatasArgs, opts ...pulumi.InvokeOption) (*GetUserMetadatasResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetUserMetadatasResult
	err := ctx.Invoke("zitadel:index/getUserMetadatas:getUserMetadatas", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getUserMetadatas.
type GetUserMetadatasArgs struct {
	// Filter metadata by key
	Key *string `pulumi:"key"`
	// ID of the organization
	OrgId *string `pulumi:"orgId"`
	// ID of the user
	UserId string `pulumi:"userId"`
}

// A collection of values returned by getUserMetadatas.
type GetUserMetadatasResult struct {
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// Filter metadata by key
	Key *string `pulumi:"key"`
	// List of user metadata entries
	Metadatas []GetUserMetadatasMetadata `pulumi:"metadatas"`
	// ID of the organization
	OrgId *string `pulumi:"orgId"`
	// ID of the user
	UserId string `pulumi:"userId"`
}

func GetUserMetadatasOutput(ctx *pulumi.Context, args GetUserMetadatasOutputArgs, opts ...pulumi.InvokeOption) GetUserMetadatasResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetUserMetadatasResultOutput, error) {
			args := v.(GetUserMetadatasArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("zitadel:index/getUserMetadatas:getUserMetadatas", args, GetUserMetadatasResultOutput{}, options).(GetUserMetadatasResultOutput), nil
		}).(GetUserMetadatasResultOutput)
}

// A collection of arguments for invoking getUserMetadatas.
type GetUserMetadatasOutputArgs struct {
	// Filter metadata by key
	Key pulumi.StringPtrInput `pulumi:"key"`
	// ID of the organization
	OrgId pulumi.StringPtrInput `pulumi:"orgId"`
	// ID of the user
	UserId pulumi.StringInput `pulumi:"userId"`
}

func (GetUserMetadatasOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetUserMetadatasArgs)(nil)).Elem()
}

// A collection of values returned by getUserMetadatas.
type GetUserMetadatasResultOutput struct{ *pulumi.OutputState }

func (GetUserMetadatasResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetUserMetadatasResult)(nil)).Elem()
}

func (o GetUserMetadatasResultOutput) ToGetUserMetadatasResultOutput() GetUserMetadatasResultOutput {
	return o
}

func (o GetUserMetadatasResultOutput) ToGetUserMetadatasResultOutputWithContext(ctx context.Context) GetUserMetadatasResultOutput {
	return o
}

// The provider-assigned unique ID for this managed resource.
func (o GetUserMetadatasResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetUserMetadatasResult) string { return v.Id }).(pulumi.StringOutput)
}

// Filter metadata by key
func (o GetUserMetadatasResultOutput) Key() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetUserMetadatasResult) *string { return v.Key }).(pulumi.StringPtrOutput)
}

// List of user metadata entries
func (o GetUserMetadatasResultOutput) Metadatas() GetUserMetadatasMetadataArrayOutput {
	return o.ApplyT(func(v GetUserMetadatasResult) []GetUserMetadatasMetadata { return v.Metadatas }).(GetUserMetadatasMetadataArrayOutput)
}

// ID of the organization
func (o GetUserMetadatasResultOutput) OrgId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetUserMetadatasResult) *string { return v.OrgId }).(pulumi.StringPtrOutput)
}

// ID of the user
func (o GetUserMetadatasResultOutput) UserId() pulumi.StringOutput {
	return o.ApplyT(func(v GetUserMetadatasResult) string { return v.UserId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetUserMetadatasResultOutput{})
}
