// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package zitadel

import (
	"fmt"

	"github.com/blang/semver"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/truvity/pulumi-zitadel/sdk/go/zitadel/internal"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "zitadel:index/action:Action":
		r = &Action{}
	case "zitadel:index/actionExecutionEvent:ActionExecutionEvent":
		r = &ActionExecutionEvent{}
	case "zitadel:index/actionExecutionFunction:ActionExecutionFunction":
		r = &ActionExecutionFunction{}
	case "zitadel:index/actionExecutionRequest:ActionExecutionRequest":
		r = &ActionExecutionRequest{}
	case "zitadel:index/actionExecutionResponse:ActionExecutionResponse":
		r = &ActionExecutionResponse{}
	case "zitadel:index/actionTarget:ActionTarget":
		r = &ActionTarget{}
	case "zitadel:index/actionTargetPublicKey:ActionTargetPublicKey":
		r = &ActionTargetPublicKey{}
	case "zitadel:index/activeWebkey:ActiveWebkey":
		r = &ActiveWebkey{}
	case "zitadel:index/applicationApi:ApplicationApi":
		r = &ApplicationApi{}
	case "zitadel:index/applicationKey:ApplicationKey":
		r = &ApplicationKey{}
	case "zitadel:index/applicationOidc:ApplicationOidc":
		r = &ApplicationOidc{}
	case "zitadel:index/applicationSaml:ApplicationSaml":
		r = &ApplicationSaml{}
	case "zitadel:index/applicationV2:ApplicationV2":
		r = &ApplicationV2{}
	case "zitadel:index/defaultDomainClaimedMessageText:DefaultDomainClaimedMessageText":
		r = &DefaultDomainClaimedMessageText{}
	case "zitadel:index/defaultDomainPolicy:DefaultDomainPolicy":
		r = &DefaultDomainPolicy{}
	case "zitadel:index/defaultInitMessageText:DefaultInitMessageText":
		r = &DefaultInitMessageText{}
	case "zitadel:index/defaultInviteUserMessageText:DefaultInviteUserMessageText":
		r = &DefaultInviteUserMessageText{}
	case "zitadel:index/defaultLabelPolicy:DefaultLabelPolicy":
		r = &DefaultLabelPolicy{}
	case "zitadel:index/defaultLockoutPolicy:DefaultLockoutPolicy":
		r = &DefaultLockoutPolicy{}
	case "zitadel:index/defaultLoginPolicy:DefaultLoginPolicy":
		r = &DefaultLoginPolicy{}
	case "zitadel:index/defaultLoginTexts:DefaultLoginTexts":
		r = &DefaultLoginTexts{}
	case "zitadel:index/defaultNotificationPolicy:DefaultNotificationPolicy":
		r = &DefaultNotificationPolicy{}
	case "zitadel:index/defaultOidcSettings:DefaultOidcSettings":
		r = &DefaultOidcSettings{}
	case "zitadel:index/defaultPasswordAgePolicy:DefaultPasswordAgePolicy":
		r = &DefaultPasswordAgePolicy{}
	case "zitadel:index/defaultPasswordChangeMessageText:DefaultPasswordChangeMessageText":
		r = &DefaultPasswordChangeMessageText{}
	case "zitadel:index/defaultPasswordComplexityPolicy:DefaultPasswordComplexityPolicy":
		r = &DefaultPasswordComplexityPolicy{}
	case "zitadel:index/defaultPasswordResetMessageText:DefaultPasswordResetMessageText":
		r = &DefaultPasswordResetMessageText{}
	case "zitadel:index/defaultPasswordlessRegistrationMessageText:DefaultPasswordlessRegistrationMessageText":
		r = &DefaultPasswordlessRegistrationMessageText{}
	case "zitadel:index/defaultPrivacyPolicy:DefaultPrivacyPolicy":
		r = &DefaultPrivacyPolicy{}
	case "zitadel:index/defaultSecuritySettings:DefaultSecuritySettings":
		r = &DefaultSecuritySettings{}
	case "zitadel:index/defaultVerifyEmailMessageText:DefaultVerifyEmailMessageText":
		r = &DefaultVerifyEmailMessageText{}
	case "zitadel:index/defaultVerifyEmailOtpMessageText:DefaultVerifyEmailOtpMessageText":
		r = &DefaultVerifyEmailOtpMessageText{}
	case "zitadel:index/defaultVerifyPhoneMessageText:DefaultVerifyPhoneMessageText":
		r = &DefaultVerifyPhoneMessageText{}
	case "zitadel:index/defaultVerifySmsOtpMessageText:DefaultVerifySmsOtpMessageText":
		r = &DefaultVerifySmsOtpMessageText{}
	case "zitadel:index/domain:Domain":
		r = &Domain{}
	case "zitadel:index/domainClaimedMessageText:DomainClaimedMessageText":
		r = &DomainClaimedMessageText{}
	case "zitadel:index/domainPolicy:DomainPolicy":
		r = &DomainPolicy{}
	case "zitadel:index/emailProviderHttp:EmailProviderHttp":
		r = &EmailProviderHttp{}
	case "zitadel:index/emailProviderSmtp:EmailProviderSmtp":
		r = &EmailProviderSmtp{}
	case "zitadel:index/humanUser:HumanUser":
		r = &HumanUser{}
	case "zitadel:index/idpApple:IdpApple":
		r = &IdpApple{}
	case "zitadel:index/idpAzureAd:IdpAzureAd":
		r = &IdpAzureAd{}
	case "zitadel:index/idpGithub:IdpGithub":
		r = &IdpGithub{}
	case "zitadel:index/idpGithubEs:IdpGithubEs":
		r = &IdpGithubEs{}
	case "zitadel:index/idpGitlab:IdpGitlab":
		r = &IdpGitlab{}
	case "zitadel:index/idpGitlabSelfHosted:IdpGitlabSelfHosted":
		r = &IdpGitlabSelfHosted{}
	case "zitadel:index/idpGoogle:IdpGoogle":
		r = &IdpGoogle{}
	case "zitadel:index/idpLdap:IdpLdap":
		r = &IdpLdap{}
	case "zitadel:index/idpOauth:IdpOauth":
		r = &IdpOauth{}
	case "zitadel:index/idpOidc:IdpOidc":
		r = &IdpOidc{}
	case "zitadel:index/idpSaml:IdpSaml":
		r = &IdpSaml{}
	case "zitadel:index/initMessageText:InitMessageText":
		r = &InitMessageText{}
	case "zitadel:index/instanceCustomDomain:InstanceCustomDomain":
		r = &InstanceCustomDomain{}
	case "zitadel:index/instanceFeatures:InstanceFeatures":
		r = &InstanceFeatures{}
	case "zitadel:index/instanceMember:InstanceMember":
		r = &InstanceMember{}
	case "zitadel:index/instanceRestrictions:InstanceRestrictions":
		r = &InstanceRestrictions{}
	case "zitadel:index/instanceSecretGenerator:InstanceSecretGenerator":
		r = &InstanceSecretGenerator{}
	case "zitadel:index/instanceTrustedDomain:InstanceTrustedDomain":
		r = &InstanceTrustedDomain{}
	case "zitadel:index/labelPolicy:LabelPolicy":
		r = &LabelPolicy{}
	case "zitadel:index/lockoutPolicy:LockoutPolicy":
		r = &LockoutPolicy{}
	case "zitadel:index/loginPolicy:LoginPolicy":
		r = &LoginPolicy{}
	case "zitadel:index/loginTexts:LoginTexts":
		r = &LoginTexts{}
	case "zitadel:index/machineKey:MachineKey":
		r = &MachineKey{}
	case "zitadel:index/machineUser:MachineUser":
		r = &MachineUser{}
	case "zitadel:index/notificationPolicy:NotificationPolicy":
		r = &NotificationPolicy{}
	case "zitadel:index/org:Org":
		r = &Org{}
	case "zitadel:index/orgIdpApple:OrgIdpApple":
		r = &OrgIdpApple{}
	case "zitadel:index/orgIdpAzureAd:OrgIdpAzureAd":
		r = &OrgIdpAzureAd{}
	case "zitadel:index/orgIdpGithub:OrgIdpGithub":
		r = &OrgIdpGithub{}
	case "zitadel:index/orgIdpGithubEs:OrgIdpGithubEs":
		r = &OrgIdpGithubEs{}
	case "zitadel:index/orgIdpGitlab:OrgIdpGitlab":
		r = &OrgIdpGitlab{}
	case "zitadel:index/orgIdpGitlabSelfHosted:OrgIdpGitlabSelfHosted":
		r = &OrgIdpGitlabSelfHosted{}
	case "zitadel:index/orgIdpGoogle:OrgIdpGoogle":
		r = &OrgIdpGoogle{}
	case "zitadel:index/orgIdpJwt:OrgIdpJwt":
		r = &OrgIdpJwt{}
	case "zitadel:index/orgIdpLdap:OrgIdpLdap":
		r = &OrgIdpLdap{}
	case "zitadel:index/orgIdpOauth:OrgIdpOauth":
		r = &OrgIdpOauth{}
	case "zitadel:index/orgIdpOidc:OrgIdpOidc":
		r = &OrgIdpOidc{}
	case "zitadel:index/orgIdpSaml:OrgIdpSaml":
		r = &OrgIdpSaml{}
	case "zitadel:index/orgMember:OrgMember":
		r = &OrgMember{}
	case "zitadel:index/orgMetadata:OrgMetadata":
		r = &OrgMetadata{}
	case "zitadel:index/organization:Organization":
		r = &Organization{}
	case "zitadel:index/organizationDomain:OrganizationDomain":
		r = &OrganizationDomain{}
	case "zitadel:index/organizationMetadata:OrganizationMetadata":
		r = &OrganizationMetadata{}
	case "zitadel:index/passwordAgePolicy:PasswordAgePolicy":
		r = &PasswordAgePolicy{}
	case "zitadel:index/passwordChangeMessageText:PasswordChangeMessageText":
		r = &PasswordChangeMessageText{}
	case "zitadel:index/passwordComplexityPolicy:PasswordComplexityPolicy":
		r = &PasswordComplexityPolicy{}
	case "zitadel:index/passwordResetMessageText:PasswordResetMessageText":
		r = &PasswordResetMessageText{}
	case "zitadel:index/passwordlessRegistrationMessageText:PasswordlessRegistrationMessageText":
		r = &PasswordlessRegistrationMessageText{}
	case "zitadel:index/personalAccessToken:PersonalAccessToken":
		r = &PersonalAccessToken{}
	case "zitadel:index/privacyPolicy:PrivacyPolicy":
		r = &PrivacyPolicy{}
	case "zitadel:index/project:Project":
		r = &Project{}
	case "zitadel:index/projectGrant:ProjectGrant":
		r = &ProjectGrant{}
	case "zitadel:index/projectGrantMember:ProjectGrantMember":
		r = &ProjectGrantMember{}
	case "zitadel:index/projectMember:ProjectMember":
		r = &ProjectMember{}
	case "zitadel:index/projectRole:ProjectRole":
		r = &ProjectRole{}
	case "zitadel:index/projectV2:ProjectV2":
		r = &ProjectV2{}
	case "zitadel:index/smsProviderHttp:SmsProviderHttp":
		r = &SmsProviderHttp{}
	case "zitadel:index/smsProviderTwilio:SmsProviderTwilio":
		r = &SmsProviderTwilio{}
	case "zitadel:index/smtpConfig:SmtpConfig":
		r = &SmtpConfig{}
	case "zitadel:index/systemFeatures:SystemFeatures":
		r = &SystemFeatures{}
	case "zitadel:index/triggerActions:TriggerActions":
		r = &TriggerActions{}
	case "zitadel:index/userGrant:UserGrant":
		r = &UserGrant{}
	case "zitadel:index/userMetadata:UserMetadata":
		r = &UserMetadata{}
	case "zitadel:index/verifyEmailMessageText:VerifyEmailMessageText":
		r = &VerifyEmailMessageText{}
	case "zitadel:index/verifyEmailOtpMessageText:VerifyEmailOtpMessageText":
		r = &VerifyEmailOtpMessageText{}
	case "zitadel:index/verifyPhoneMessageText:VerifyPhoneMessageText":
		r = &VerifyPhoneMessageText{}
	case "zitadel:index/verifySmsOtpMessageText:VerifySmsOtpMessageText":
		r = &VerifySmsOtpMessageText{}
	case "zitadel:index/webkey:Webkey":
		r = &Webkey{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

type pkg struct {
	version semver.Version
}

func (p *pkg) Version() semver.Version {
	return p.version
}

func (p *pkg) ConstructProvider(ctx *pulumi.Context, name, typ, urn string) (pulumi.ProviderResource, error) {
	if typ != "pulumi:providers:zitadel" {
		return nil, fmt.Errorf("unknown provider type: %s", typ)
	}

	r := &Provider{}
	err := ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return r, err
}

func init() {
	version, err := internal.PkgVersion()
	if err != nil {
		version = semver.Version{Major: 1}
	}
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/action",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/actionExecutionEvent",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/actionExecutionFunction",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/actionExecutionRequest",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/actionExecutionResponse",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/actionTarget",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/actionTargetPublicKey",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/activeWebkey",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/applicationApi",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/applicationKey",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/applicationOidc",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/applicationSaml",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/applicationV2",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/defaultDomainClaimedMessageText",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/defaultDomainPolicy",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/defaultInitMessageText",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/defaultInviteUserMessageText",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/defaultLabelPolicy",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/defaultLockoutPolicy",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/defaultLoginPolicy",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/defaultLoginTexts",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/defaultNotificationPolicy",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/defaultOidcSettings",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/defaultPasswordAgePolicy",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/defaultPasswordChangeMessageText",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/defaultPasswordComplexityPolicy",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/defaultPasswordResetMessageText",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/defaultPasswordlessRegistrationMessageText",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/defaultPrivacyPolicy",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/defaultSecuritySettings",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/defaultVerifyEmailMessageText",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/defaultVerifyEmailOtpMessageText",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/defaultVerifyPhoneMessageText",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/defaultVerifySmsOtpMessageText",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/domain",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/domainClaimedMessageText",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/domainPolicy",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/emailProviderHttp",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/emailProviderSmtp",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/humanUser",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/idpApple",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/idpAzureAd",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/idpGithub",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/idpGithubEs",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/idpGitlab",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/idpGitlabSelfHosted",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/idpGoogle",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/idpLdap",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/idpOauth",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/idpOidc",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/idpSaml",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/initMessageText",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/instanceCustomDomain",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/instanceFeatures",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/instanceMember",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/instanceRestrictions",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/instanceSecretGenerator",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/instanceTrustedDomain",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/labelPolicy",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/lockoutPolicy",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/loginPolicy",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/loginTexts",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/machineKey",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/machineUser",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/notificationPolicy",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/org",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/orgIdpApple",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/orgIdpAzureAd",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/orgIdpGithub",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/orgIdpGithubEs",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/orgIdpGitlab",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/orgIdpGitlabSelfHosted",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/orgIdpGoogle",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/orgIdpJwt",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/orgIdpLdap",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/orgIdpOauth",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/orgIdpOidc",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/orgIdpSaml",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/orgMember",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/orgMetadata",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/organization",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/organizationDomain",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/organizationMetadata",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/passwordAgePolicy",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/passwordChangeMessageText",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/passwordComplexityPolicy",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/passwordResetMessageText",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/passwordlessRegistrationMessageText",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/personalAccessToken",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/privacyPolicy",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/project",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/projectGrant",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/projectGrantMember",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/projectMember",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/projectRole",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/projectV2",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/smsProviderHttp",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/smsProviderTwilio",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/smtpConfig",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/systemFeatures",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/triggerActions",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/userGrant",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/userMetadata",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/verifyEmailMessageText",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/verifyEmailOtpMessageText",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/verifyPhoneMessageText",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/verifySmsOtpMessageText",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"zitadel",
		"index/webkey",
		&module{version},
	)
	pulumi.RegisterResourcePackage(
		"zitadel",
		&pkg{version},
	)
}
