// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package zitadel

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/truvity/pulumi-zitadel/sdk/go/zitadel/internal"
)

// Resource representing the feature flags configuration for an instance.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/truvity/pulumi-zitadel/sdk/go/zitadel"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := zitadel.NewInstanceFeatures(ctx, "default", &zitadel.InstanceFeaturesArgs{
//				LoginDefaultOrg:   pulumi.Bool(true),
//				OidcTokenExchange: pulumi.Bool(true),
//				UserSchema:        pulumi.Bool(false),
//				ImprovedPerformances: pulumi.StringArray{
//					pulumi.String("IMPROVED_PERFORMANCE_PROJECT_GRANT"),
//					pulumi.String("IMPROVED_PERFORMANCE_ORG_DOMAIN_VERIFIED"),
//				},
//				DebugOidcParentError:           pulumi.Bool(false),
//				OidcSingleV1SessionTermination: pulumi.Bool(true),
//				EnableBackChannelLogout:        pulumi.Bool(true),
//				LoginV2: &zitadel.InstanceFeaturesLoginV2Args{
//					Required: pulumi.Bool(true),
//					BaseUri:  pulumi.String("https://login.example.com"),
//				},
//				PermissionCheckV2:   pulumi.Bool(true),
//				ConsoleUseV2UserApi: pulumi.Bool(true),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Import
//
// The resource can be imported using the constant ID "instance"
//
// ```sh
// $ pulumi import zitadel:index/instanceFeatures:InstanceFeatures imported 'instance'
// ```
type InstanceFeatures struct {
	pulumi.CustomResourceState

	// If this is enabled the console web client will use the new User v2 API for certain calls
	ConsoleUseV2UserApi pulumi.BoolOutput `pulumi:"consoleUseV2UserApi"`
	// Return parent errors to OIDC clients for debugging purposes. Parent errors may contain sensitive data or unwanted details about the system status of zitadel. Only enable if really needed.
	DebugOidcParentError pulumi.BoolOutput `pulumi:"debugOidcParentError"`
	// If the flag is enabled, you'll be able to use the OIDC Back-Channel Logout to be notified in your application about terminated user sessions.
	EnableBackChannelLogout pulumi.BoolOutput `pulumi:"enableBackChannelLogout"`
	// Improves performance of specified execution paths. Possible values: IMPROVED*PERFORMANCE*PROJECT*GRANT, IMPROVED*PERFORMANCE*PROJECT, IMPROVED*PERFORMANCE*USER*GRANT, IMPROVED*PERFORMANCE*ORG*DOMAIN*VERIFIED
	ImprovedPerformances pulumi.StringArrayOutput `pulumi:"improvedPerformances"`
	// The login UI will use the settings of the default org (and not from the instance) if no organization context is set
	LoginDefaultOrg pulumi.BoolOutput `pulumi:"loginDefaultOrg"`
	// Specify the login UI for all users and applications regardless of their preference.
	LoginV2 InstanceFeaturesLoginV2Output `pulumi:"loginV2"`
	// If the flag is enabled, you'll be able to terminate a single session from the login UI by providing an id*token with a `sid` claim as id*token*hint on the end*session endpoint. Note that currently all sessions from the same user agent (browser) are terminated in the login UI. Sessions managed through the Session API already allow the termination of single sessions.
	OidcSingleV1SessionTermination pulumi.BoolOutput `pulumi:"oidcSingleV1SessionTermination"`
	// Enable the experimental `urn:ietf:params:oauth:grant-type:token-exchange` grant type for the OIDC token endpoint. Token exchange can be used to request tokens with a lesser scope or impersonate other users. See the security policy to allow impersonation on an instance.
	OidcTokenExchange pulumi.BoolOutput `pulumi:"oidcTokenExchange"`
	// Enable a newer, more performant, permission check used for v2 and v3 resource based APIs.
	PermissionCheckV2 pulumi.BoolOutput `pulumi:"permissionCheckV2"`
	// User Schemas allow to manage data schemas of user. If the flag is enabled, you'll be able to use the new API and its features. Note that it is still in an early stage.
	UserSchema pulumi.BoolOutput `pulumi:"userSchema"`
}

// NewInstanceFeatures registers a new resource with the given unique name, arguments, and options.
func NewInstanceFeatures(ctx *pulumi.Context,
	name string, args *InstanceFeaturesArgs, opts ...pulumi.ResourceOption) (*InstanceFeatures, error) {
	if args == nil {
		args = &InstanceFeaturesArgs{}
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	var resource InstanceFeatures
	err := ctx.RegisterResource("zitadel:index/instanceFeatures:InstanceFeatures", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetInstanceFeatures gets an existing InstanceFeatures resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetInstanceFeatures(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *InstanceFeaturesState, opts ...pulumi.ResourceOption) (*InstanceFeatures, error) {
	var resource InstanceFeatures
	err := ctx.ReadResource("zitadel:index/instanceFeatures:InstanceFeatures", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering InstanceFeatures resources.
type instanceFeaturesState struct {
	// If this is enabled the console web client will use the new User v2 API for certain calls
	ConsoleUseV2UserApi *bool `pulumi:"consoleUseV2UserApi"`
	// Return parent errors to OIDC clients for debugging purposes. Parent errors may contain sensitive data or unwanted details about the system status of zitadel. Only enable if really needed.
	DebugOidcParentError *bool `pulumi:"debugOidcParentError"`
	// If the flag is enabled, you'll be able to use the OIDC Back-Channel Logout to be notified in your application about terminated user sessions.
	EnableBackChannelLogout *bool `pulumi:"enableBackChannelLogout"`
	// Improves performance of specified execution paths. Possible values: IMPROVED*PERFORMANCE*PROJECT*GRANT, IMPROVED*PERFORMANCE*PROJECT, IMPROVED*PERFORMANCE*USER*GRANT, IMPROVED*PERFORMANCE*ORG*DOMAIN*VERIFIED
	ImprovedPerformances []string `pulumi:"improvedPerformances"`
	// The login UI will use the settings of the default org (and not from the instance) if no organization context is set
	LoginDefaultOrg *bool `pulumi:"loginDefaultOrg"`
	// Specify the login UI for all users and applications regardless of their preference.
	LoginV2 *InstanceFeaturesLoginV2 `pulumi:"loginV2"`
	// If the flag is enabled, you'll be able to terminate a single session from the login UI by providing an id*token with a `sid` claim as id*token*hint on the end*session endpoint. Note that currently all sessions from the same user agent (browser) are terminated in the login UI. Sessions managed through the Session API already allow the termination of single sessions.
	OidcSingleV1SessionTermination *bool `pulumi:"oidcSingleV1SessionTermination"`
	// Enable the experimental `urn:ietf:params:oauth:grant-type:token-exchange` grant type for the OIDC token endpoint. Token exchange can be used to request tokens with a lesser scope or impersonate other users. See the security policy to allow impersonation on an instance.
	OidcTokenExchange *bool `pulumi:"oidcTokenExchange"`
	// Enable a newer, more performant, permission check used for v2 and v3 resource based APIs.
	PermissionCheckV2 *bool `pulumi:"permissionCheckV2"`
	// User Schemas allow to manage data schemas of user. If the flag is enabled, you'll be able to use the new API and its features. Note that it is still in an early stage.
	UserSchema *bool `pulumi:"userSchema"`
}

type InstanceFeaturesState struct {
	// If this is enabled the console web client will use the new User v2 API for certain calls
	ConsoleUseV2UserApi pulumi.BoolPtrInput
	// Return parent errors to OIDC clients for debugging purposes. Parent errors may contain sensitive data or unwanted details about the system status of zitadel. Only enable if really needed.
	DebugOidcParentError pulumi.BoolPtrInput
	// If the flag is enabled, you'll be able to use the OIDC Back-Channel Logout to be notified in your application about terminated user sessions.
	EnableBackChannelLogout pulumi.BoolPtrInput
	// Improves performance of specified execution paths. Possible values: IMPROVED*PERFORMANCE*PROJECT*GRANT, IMPROVED*PERFORMANCE*PROJECT, IMPROVED*PERFORMANCE*USER*GRANT, IMPROVED*PERFORMANCE*ORG*DOMAIN*VERIFIED
	ImprovedPerformances pulumi.StringArrayInput
	// The login UI will use the settings of the default org (and not from the instance) if no organization context is set
	LoginDefaultOrg pulumi.BoolPtrInput
	// Specify the login UI for all users and applications regardless of their preference.
	LoginV2 InstanceFeaturesLoginV2PtrInput
	// If the flag is enabled, you'll be able to terminate a single session from the login UI by providing an id*token with a `sid` claim as id*token*hint on the end*session endpoint. Note that currently all sessions from the same user agent (browser) are terminated in the login UI. Sessions managed through the Session API already allow the termination of single sessions.
	OidcSingleV1SessionTermination pulumi.BoolPtrInput
	// Enable the experimental `urn:ietf:params:oauth:grant-type:token-exchange` grant type for the OIDC token endpoint. Token exchange can be used to request tokens with a lesser scope or impersonate other users. See the security policy to allow impersonation on an instance.
	OidcTokenExchange pulumi.BoolPtrInput
	// Enable a newer, more performant, permission check used for v2 and v3 resource based APIs.
	PermissionCheckV2 pulumi.BoolPtrInput
	// User Schemas allow to manage data schemas of user. If the flag is enabled, you'll be able to use the new API and its features. Note that it is still in an early stage.
	UserSchema pulumi.BoolPtrInput
}

func (InstanceFeaturesState) ElementType() reflect.Type {
	return reflect.TypeOf((*instanceFeaturesState)(nil)).Elem()
}

type instanceFeaturesArgs struct {
	// If this is enabled the console web client will use the new User v2 API for certain calls
	ConsoleUseV2UserApi *bool `pulumi:"consoleUseV2UserApi"`
	// Return parent errors to OIDC clients for debugging purposes. Parent errors may contain sensitive data or unwanted details about the system status of zitadel. Only enable if really needed.
	DebugOidcParentError *bool `pulumi:"debugOidcParentError"`
	// If the flag is enabled, you'll be able to use the OIDC Back-Channel Logout to be notified in your application about terminated user sessions.
	EnableBackChannelLogout *bool `pulumi:"enableBackChannelLogout"`
	// Improves performance of specified execution paths. Possible values: IMPROVED*PERFORMANCE*PROJECT*GRANT, IMPROVED*PERFORMANCE*PROJECT, IMPROVED*PERFORMANCE*USER*GRANT, IMPROVED*PERFORMANCE*ORG*DOMAIN*VERIFIED
	ImprovedPerformances []string `pulumi:"improvedPerformances"`
	// The login UI will use the settings of the default org (and not from the instance) if no organization context is set
	LoginDefaultOrg *bool `pulumi:"loginDefaultOrg"`
	// Specify the login UI for all users and applications regardless of their preference.
	LoginV2 *InstanceFeaturesLoginV2 `pulumi:"loginV2"`
	// If the flag is enabled, you'll be able to terminate a single session from the login UI by providing an id*token with a `sid` claim as id*token*hint on the end*session endpoint. Note that currently all sessions from the same user agent (browser) are terminated in the login UI. Sessions managed through the Session API already allow the termination of single sessions.
	OidcSingleV1SessionTermination *bool `pulumi:"oidcSingleV1SessionTermination"`
	// Enable the experimental `urn:ietf:params:oauth:grant-type:token-exchange` grant type for the OIDC token endpoint. Token exchange can be used to request tokens with a lesser scope or impersonate other users. See the security policy to allow impersonation on an instance.
	OidcTokenExchange *bool `pulumi:"oidcTokenExchange"`
	// Enable a newer, more performant, permission check used for v2 and v3 resource based APIs.
	PermissionCheckV2 *bool `pulumi:"permissionCheckV2"`
	// User Schemas allow to manage data schemas of user. If the flag is enabled, you'll be able to use the new API and its features. Note that it is still in an early stage.
	UserSchema *bool `pulumi:"userSchema"`
}

// The set of arguments for constructing a InstanceFeatures resource.
type InstanceFeaturesArgs struct {
	// If this is enabled the console web client will use the new User v2 API for certain calls
	ConsoleUseV2UserApi pulumi.BoolPtrInput
	// Return parent errors to OIDC clients for debugging purposes. Parent errors may contain sensitive data or unwanted details about the system status of zitadel. Only enable if really needed.
	DebugOidcParentError pulumi.BoolPtrInput
	// If the flag is enabled, you'll be able to use the OIDC Back-Channel Logout to be notified in your application about terminated user sessions.
	EnableBackChannelLogout pulumi.BoolPtrInput
	// Improves performance of specified execution paths. Possible values: IMPROVED*PERFORMANCE*PROJECT*GRANT, IMPROVED*PERFORMANCE*PROJECT, IMPROVED*PERFORMANCE*USER*GRANT, IMPROVED*PERFORMANCE*ORG*DOMAIN*VERIFIED
	ImprovedPerformances pulumi.StringArrayInput
	// The login UI will use the settings of the default org (and not from the instance) if no organization context is set
	LoginDefaultOrg pulumi.BoolPtrInput
	// Specify the login UI for all users and applications regardless of their preference.
	LoginV2 InstanceFeaturesLoginV2PtrInput
	// If the flag is enabled, you'll be able to terminate a single session from the login UI by providing an id*token with a `sid` claim as id*token*hint on the end*session endpoint. Note that currently all sessions from the same user agent (browser) are terminated in the login UI. Sessions managed through the Session API already allow the termination of single sessions.
	OidcSingleV1SessionTermination pulumi.BoolPtrInput
	// Enable the experimental `urn:ietf:params:oauth:grant-type:token-exchange` grant type for the OIDC token endpoint. Token exchange can be used to request tokens with a lesser scope or impersonate other users. See the security policy to allow impersonation on an instance.
	OidcTokenExchange pulumi.BoolPtrInput
	// Enable a newer, more performant, permission check used for v2 and v3 resource based APIs.
	PermissionCheckV2 pulumi.BoolPtrInput
	// User Schemas allow to manage data schemas of user. If the flag is enabled, you'll be able to use the new API and its features. Note that it is still in an early stage.
	UserSchema pulumi.BoolPtrInput
}

func (InstanceFeaturesArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*instanceFeaturesArgs)(nil)).Elem()
}

type InstanceFeaturesInput interface {
	pulumi.Input

	ToInstanceFeaturesOutput() InstanceFeaturesOutput
	ToInstanceFeaturesOutputWithContext(ctx context.Context) InstanceFeaturesOutput
}

func (*InstanceFeatures) ElementType() reflect.Type {
	return reflect.TypeOf((**InstanceFeatures)(nil)).Elem()
}

func (i *InstanceFeatures) ToInstanceFeaturesOutput() InstanceFeaturesOutput {
	return i.ToInstanceFeaturesOutputWithContext(context.Background())
}

func (i *InstanceFeatures) ToInstanceFeaturesOutputWithContext(ctx context.Context) InstanceFeaturesOutput {
	return pulumi.ToOutputWithContext(ctx, i).(InstanceFeaturesOutput)
}

type InstanceFeaturesOutput struct{ *pulumi.OutputState }

func (InstanceFeaturesOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**InstanceFeatures)(nil)).Elem()
}

func (o InstanceFeaturesOutput) ToInstanceFeaturesOutput() InstanceFeaturesOutput {
	return o
}

func (o InstanceFeaturesOutput) ToInstanceFeaturesOutputWithContext(ctx context.Context) InstanceFeaturesOutput {
	return o
}

// If this is enabled the console web client will use the new User v2 API for certain calls
func (o InstanceFeaturesOutput) ConsoleUseV2UserApi() pulumi.BoolOutput {
	return o.ApplyT(func(v *InstanceFeatures) pulumi.BoolOutput { return v.ConsoleUseV2UserApi }).(pulumi.BoolOutput)
}

// Return parent errors to OIDC clients for debugging purposes. Parent errors may contain sensitive data or unwanted details about the system status of zitadel. Only enable if really needed.
func (o InstanceFeaturesOutput) DebugOidcParentError() pulumi.BoolOutput {
	return o.ApplyT(func(v *InstanceFeatures) pulumi.BoolOutput { return v.DebugOidcParentError }).(pulumi.BoolOutput)
}

// If the flag is enabled, you'll be able to use the OIDC Back-Channel Logout to be notified in your application about terminated user sessions.
func (o InstanceFeaturesOutput) EnableBackChannelLogout() pulumi.BoolOutput {
	return o.ApplyT(func(v *InstanceFeatures) pulumi.BoolOutput { return v.EnableBackChannelLogout }).(pulumi.BoolOutput)
}

// Improves performance of specified execution paths. Possible values: IMPROVED*PERFORMANCE*PROJECT*GRANT, IMPROVED*PERFORMANCE*PROJECT, IMPROVED*PERFORMANCE*USER*GRANT, IMPROVED*PERFORMANCE*ORG*DOMAIN*VERIFIED
func (o InstanceFeaturesOutput) ImprovedPerformances() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *InstanceFeatures) pulumi.StringArrayOutput { return v.ImprovedPerformances }).(pulumi.StringArrayOutput)
}

// The login UI will use the settings of the default org (and not from the instance) if no organization context is set
func (o InstanceFeaturesOutput) LoginDefaultOrg() pulumi.BoolOutput {
	return o.ApplyT(func(v *InstanceFeatures) pulumi.BoolOutput { return v.LoginDefaultOrg }).(pulumi.BoolOutput)
}

// Specify the login UI for all users and applications regardless of their preference.
func (o InstanceFeaturesOutput) LoginV2() InstanceFeaturesLoginV2Output {
	return o.ApplyT(func(v *InstanceFeatures) InstanceFeaturesLoginV2Output { return v.LoginV2 }).(InstanceFeaturesLoginV2Output)
}

// If the flag is enabled, you'll be able to terminate a single session from the login UI by providing an id*token with a `sid` claim as id*token*hint on the end*session endpoint. Note that currently all sessions from the same user agent (browser) are terminated in the login UI. Sessions managed through the Session API already allow the termination of single sessions.
func (o InstanceFeaturesOutput) OidcSingleV1SessionTermination() pulumi.BoolOutput {
	return o.ApplyT(func(v *InstanceFeatures) pulumi.BoolOutput { return v.OidcSingleV1SessionTermination }).(pulumi.BoolOutput)
}

// Enable the experimental `urn:ietf:params:oauth:grant-type:token-exchange` grant type for the OIDC token endpoint. Token exchange can be used to request tokens with a lesser scope or impersonate other users. See the security policy to allow impersonation on an instance.
func (o InstanceFeaturesOutput) OidcTokenExchange() pulumi.BoolOutput {
	return o.ApplyT(func(v *InstanceFeatures) pulumi.BoolOutput { return v.OidcTokenExchange }).(pulumi.BoolOutput)
}

// Enable a newer, more performant, permission check used for v2 and v3 resource based APIs.
func (o InstanceFeaturesOutput) PermissionCheckV2() pulumi.BoolOutput {
	return o.ApplyT(func(v *InstanceFeatures) pulumi.BoolOutput { return v.PermissionCheckV2 }).(pulumi.BoolOutput)
}

// User Schemas allow to manage data schemas of user. If the flag is enabled, you'll be able to use the new API and its features. Note that it is still in an early stage.
func (o InstanceFeaturesOutput) UserSchema() pulumi.BoolOutput {
	return o.ApplyT(func(v *InstanceFeatures) pulumi.BoolOutput { return v.UserSchema }).(pulumi.BoolOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*InstanceFeaturesInput)(nil)).Elem(), &InstanceFeatures{})
	pulumi.RegisterOutputType(InstanceFeaturesOutput{})
}
