// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package zitadel

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/truvity/pulumi-zitadel/sdk/go/zitadel/internal"
)

// Resource representing a trusted domain on a ZITADEL instance. Trusted domains can be used in API responses like OIDC discovery and email templates. Unlike custom domains, trusted domains are not used for routing and do not need to be unique across instances. This resource requires iam.write permission.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/truvity/pulumi-zitadel/sdk/go/zitadel"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := zitadel.NewInstanceTrustedDomain(ctx, "default", &zitadel.InstanceTrustedDomainArgs{
//				InstanceId: pulumi.String("123456789012345678"),
//				Domain:     pulumi.String("idp.partner.com"),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Import
//
// The resource can be imported using the ID format `<instance_id>/<domain>`, e.g.
//
// ```sh
// $ pulumi import zitadel:index/instanceTrustedDomain:InstanceTrustedDomain imported '123456789012345678/idp.partner.com'
// ```
type InstanceTrustedDomain struct {
	pulumi.CustomResourceState

	// Trusted domain to add to the instance (max 253 characters)
	Domain pulumi.StringOutput `pulumi:"domain"`
	// The ID of the instance. If not provided, the instance from the current context will be used.
	InstanceId pulumi.StringOutput `pulumi:"instanceId"`
}

// NewInstanceTrustedDomain registers a new resource with the given unique name, arguments, and options.
func NewInstanceTrustedDomain(ctx *pulumi.Context,
	name string, args *InstanceTrustedDomainArgs, opts ...pulumi.ResourceOption) (*InstanceTrustedDomain, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Domain == nil {
		return nil, errors.New("invalid value for required argument 'Domain'")
	}
	if args.InstanceId == nil {
		return nil, errors.New("invalid value for required argument 'InstanceId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource InstanceTrustedDomain
	err := ctx.RegisterResource("zitadel:index/instanceTrustedDomain:InstanceTrustedDomain", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetInstanceTrustedDomain gets an existing InstanceTrustedDomain resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetInstanceTrustedDomain(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *InstanceTrustedDomainState, opts ...pulumi.ResourceOption) (*InstanceTrustedDomain, error) {
	var resource InstanceTrustedDomain
	err := ctx.ReadResource("zitadel:index/instanceTrustedDomain:InstanceTrustedDomain", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering InstanceTrustedDomain resources.
type instanceTrustedDomainState struct {
	// Trusted domain to add to the instance (max 253 characters)
	Domain *string `pulumi:"domain"`
	// The ID of the instance. If not provided, the instance from the current context will be used.
	InstanceId *string `pulumi:"instanceId"`
}

type InstanceTrustedDomainState struct {
	// Trusted domain to add to the instance (max 253 characters)
	Domain pulumi.StringPtrInput
	// The ID of the instance. If not provided, the instance from the current context will be used.
	InstanceId pulumi.StringPtrInput
}

func (InstanceTrustedDomainState) ElementType() reflect.Type {
	return reflect.TypeOf((*instanceTrustedDomainState)(nil)).Elem()
}

type instanceTrustedDomainArgs struct {
	// Trusted domain to add to the instance (max 253 characters)
	Domain string `pulumi:"domain"`
	// The ID of the instance. If not provided, the instance from the current context will be used.
	InstanceId string `pulumi:"instanceId"`
}

// The set of arguments for constructing a InstanceTrustedDomain resource.
type InstanceTrustedDomainArgs struct {
	// Trusted domain to add to the instance (max 253 characters)
	Domain pulumi.StringInput
	// The ID of the instance. If not provided, the instance from the current context will be used.
	InstanceId pulumi.StringInput
}

func (InstanceTrustedDomainArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*instanceTrustedDomainArgs)(nil)).Elem()
}

type InstanceTrustedDomainInput interface {
	pulumi.Input

	ToInstanceTrustedDomainOutput() InstanceTrustedDomainOutput
	ToInstanceTrustedDomainOutputWithContext(ctx context.Context) InstanceTrustedDomainOutput
}

func (*InstanceTrustedDomain) ElementType() reflect.Type {
	return reflect.TypeOf((**InstanceTrustedDomain)(nil)).Elem()
}

func (i *InstanceTrustedDomain) ToInstanceTrustedDomainOutput() InstanceTrustedDomainOutput {
	return i.ToInstanceTrustedDomainOutputWithContext(context.Background())
}

func (i *InstanceTrustedDomain) ToInstanceTrustedDomainOutputWithContext(ctx context.Context) InstanceTrustedDomainOutput {
	return pulumi.ToOutputWithContext(ctx, i).(InstanceTrustedDomainOutput)
}

type InstanceTrustedDomainOutput struct{ *pulumi.OutputState }

func (InstanceTrustedDomainOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**InstanceTrustedDomain)(nil)).Elem()
}

func (o InstanceTrustedDomainOutput) ToInstanceTrustedDomainOutput() InstanceTrustedDomainOutput {
	return o
}

func (o InstanceTrustedDomainOutput) ToInstanceTrustedDomainOutputWithContext(ctx context.Context) InstanceTrustedDomainOutput {
	return o
}

// Trusted domain to add to the instance (max 253 characters)
func (o InstanceTrustedDomainOutput) Domain() pulumi.StringOutput {
	return o.ApplyT(func(v *InstanceTrustedDomain) pulumi.StringOutput { return v.Domain }).(pulumi.StringOutput)
}

// The ID of the instance. If not provided, the instance from the current context will be used.
func (o InstanceTrustedDomainOutput) InstanceId() pulumi.StringOutput {
	return o.ApplyT(func(v *InstanceTrustedDomain) pulumi.StringOutput { return v.InstanceId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*InstanceTrustedDomainInput)(nil)).Elem(), &InstanceTrustedDomain{})
	pulumi.RegisterOutputType(InstanceTrustedDomainOutput{})
}
