// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package zitadel

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/truvity/pulumi-zitadel/sdk/go/zitadel/internal"
)

// Resource representing the custom lockout policy of an organization.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/truvity/pulumi-zitadel/sdk/go/zitadel"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := zitadel.NewLockoutPolicy(ctx, "default", &zitadel.LockoutPolicyArgs{
//				OrgId:               pulumi.Any(defaultZitadelOrg.Id),
//				MaxPasswordAttempts: pulumi.Int(5),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Import
//
// The resource can be imported using the ID format `<[orgId]>`, e.g.
//
// ```sh
// $ pulumi import zitadel:index/lockoutPolicy:LockoutPolicy imported '123456789012345678'
// ```
type LockoutPolicy struct {
	pulumi.CustomResourceState

	// Maximum OTP check attempts before the account gets locked. Attempts are reset as soon as the OTP is entered correct.
	MaxOtpAttempts pulumi.IntOutput `pulumi:"maxOtpAttempts"`
	// Maximum password check attempts before the account gets locked. Attempts are reset as soon as the password is entered correct or the password is reset.
	MaxPasswordAttempts pulumi.IntOutput `pulumi:"maxPasswordAttempts"`
	// ID of the organization. If not provided, the organization of the authenticated user/service account is used.
	OrgId pulumi.StringPtrOutput `pulumi:"orgId"`
}

// NewLockoutPolicy registers a new resource with the given unique name, arguments, and options.
func NewLockoutPolicy(ctx *pulumi.Context,
	name string, args *LockoutPolicyArgs, opts ...pulumi.ResourceOption) (*LockoutPolicy, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.MaxPasswordAttempts == nil {
		return nil, errors.New("invalid value for required argument 'MaxPasswordAttempts'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource LockoutPolicy
	err := ctx.RegisterResource("zitadel:index/lockoutPolicy:LockoutPolicy", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetLockoutPolicy gets an existing LockoutPolicy resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetLockoutPolicy(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *LockoutPolicyState, opts ...pulumi.ResourceOption) (*LockoutPolicy, error) {
	var resource LockoutPolicy
	err := ctx.ReadResource("zitadel:index/lockoutPolicy:LockoutPolicy", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering LockoutPolicy resources.
type lockoutPolicyState struct {
	// Maximum OTP check attempts before the account gets locked. Attempts are reset as soon as the OTP is entered correct.
	MaxOtpAttempts *int `pulumi:"maxOtpAttempts"`
	// Maximum password check attempts before the account gets locked. Attempts are reset as soon as the password is entered correct or the password is reset.
	MaxPasswordAttempts *int `pulumi:"maxPasswordAttempts"`
	// ID of the organization. If not provided, the organization of the authenticated user/service account is used.
	OrgId *string `pulumi:"orgId"`
}

type LockoutPolicyState struct {
	// Maximum OTP check attempts before the account gets locked. Attempts are reset as soon as the OTP is entered correct.
	MaxOtpAttempts pulumi.IntPtrInput
	// Maximum password check attempts before the account gets locked. Attempts are reset as soon as the password is entered correct or the password is reset.
	MaxPasswordAttempts pulumi.IntPtrInput
	// ID of the organization. If not provided, the organization of the authenticated user/service account is used.
	OrgId pulumi.StringPtrInput
}

func (LockoutPolicyState) ElementType() reflect.Type {
	return reflect.TypeOf((*lockoutPolicyState)(nil)).Elem()
}

type lockoutPolicyArgs struct {
	// Maximum OTP check attempts before the account gets locked. Attempts are reset as soon as the OTP is entered correct.
	MaxOtpAttempts *int `pulumi:"maxOtpAttempts"`
	// Maximum password check attempts before the account gets locked. Attempts are reset as soon as the password is entered correct or the password is reset.
	MaxPasswordAttempts int `pulumi:"maxPasswordAttempts"`
	// ID of the organization. If not provided, the organization of the authenticated user/service account is used.
	OrgId *string `pulumi:"orgId"`
}

// The set of arguments for constructing a LockoutPolicy resource.
type LockoutPolicyArgs struct {
	// Maximum OTP check attempts before the account gets locked. Attempts are reset as soon as the OTP is entered correct.
	MaxOtpAttempts pulumi.IntPtrInput
	// Maximum password check attempts before the account gets locked. Attempts are reset as soon as the password is entered correct or the password is reset.
	MaxPasswordAttempts pulumi.IntInput
	// ID of the organization. If not provided, the organization of the authenticated user/service account is used.
	OrgId pulumi.StringPtrInput
}

func (LockoutPolicyArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*lockoutPolicyArgs)(nil)).Elem()
}

type LockoutPolicyInput interface {
	pulumi.Input

	ToLockoutPolicyOutput() LockoutPolicyOutput
	ToLockoutPolicyOutputWithContext(ctx context.Context) LockoutPolicyOutput
}

func (*LockoutPolicy) ElementType() reflect.Type {
	return reflect.TypeOf((**LockoutPolicy)(nil)).Elem()
}

func (i *LockoutPolicy) ToLockoutPolicyOutput() LockoutPolicyOutput {
	return i.ToLockoutPolicyOutputWithContext(context.Background())
}

func (i *LockoutPolicy) ToLockoutPolicyOutputWithContext(ctx context.Context) LockoutPolicyOutput {
	return pulumi.ToOutputWithContext(ctx, i).(LockoutPolicyOutput)
}

type LockoutPolicyOutput struct{ *pulumi.OutputState }

func (LockoutPolicyOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**LockoutPolicy)(nil)).Elem()
}

func (o LockoutPolicyOutput) ToLockoutPolicyOutput() LockoutPolicyOutput {
	return o
}

func (o LockoutPolicyOutput) ToLockoutPolicyOutputWithContext(ctx context.Context) LockoutPolicyOutput {
	return o
}

// Maximum OTP check attempts before the account gets locked. Attempts are reset as soon as the OTP is entered correct.
func (o LockoutPolicyOutput) MaxOtpAttempts() pulumi.IntOutput {
	return o.ApplyT(func(v *LockoutPolicy) pulumi.IntOutput { return v.MaxOtpAttempts }).(pulumi.IntOutput)
}

// Maximum password check attempts before the account gets locked. Attempts are reset as soon as the password is entered correct or the password is reset.
func (o LockoutPolicyOutput) MaxPasswordAttempts() pulumi.IntOutput {
	return o.ApplyT(func(v *LockoutPolicy) pulumi.IntOutput { return v.MaxPasswordAttempts }).(pulumi.IntOutput)
}

// ID of the organization. If not provided, the organization of the authenticated user/service account is used.
func (o LockoutPolicyOutput) OrgId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *LockoutPolicy) pulumi.StringPtrOutput { return v.OrgId }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*LockoutPolicyInput)(nil)).Elem(), &LockoutPolicy{})
	pulumi.RegisterOutputType(LockoutPolicyOutput{})
}
