// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package zitadel

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/truvity/pulumi-zitadel/sdk/go/zitadel/internal"
)

// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/truvity/pulumi-zitadel/sdk/go/zitadel"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := zitadel.NewLoginTexts(ctx, "default", &zitadel.LoginTextsArgs{
//				OrgId:    pulumi.Any(defaultZitadelOrg.Id),
//				Language: pulumi.String("en"),
//				EmailVerificationDoneText: &zitadel.LoginTextsEmailVerificationDoneTextArgs{
//					CancelButtonText: pulumi.String("example"),
//					Description:      pulumi.String("example"),
//					LoginButtonText:  pulumi.String("example"),
//					NextButtonText:   pulumi.String("example"),
//					Title:            pulumi.String("example"),
//				},
//				EmailVerificationText: &zitadel.LoginTextsEmailVerificationTextArgs{
//					CodeLabel:        pulumi.String("example"),
//					Description:      pulumi.String("example"),
//					NextButtonText:   pulumi.String("example"),
//					ResendButtonText: pulumi.String("example"),
//					Title:            pulumi.String("example"),
//				},
//				ExternalRegistrationUserOverviewText: &zitadel.LoginTextsExternalRegistrationUserOverviewTextArgs{
//					BackButtonText:     pulumi.String("example"),
//					Description:        pulumi.String("example"),
//					EmailLabel:         pulumi.String("example"),
//					FirstnameLabel:     pulumi.String("example"),
//					LanguageLabel:      pulumi.String("example"),
//					LastnameLabel:      pulumi.String("example"),
//					NextButtonText:     pulumi.String("example"),
//					NicknameLabel:      pulumi.String("example"),
//					PhoneLabel:         pulumi.String("example"),
//					PrivacyLinkText:    pulumi.String("example"),
//					Title:              pulumi.String("example"),
//					TosAndPrivacyLabel: pulumi.String("example"),
//					TosConfirm:         pulumi.String("example"),
//					TosConfirmAnd:      "example",
//					TosLinkText:        pulumi.String("example"),
//					UsernameLabel:      pulumi.String("example"),
//				},
//				ExternalUserNotFoundText: &zitadel.LoginTextsExternalUserNotFoundTextArgs{
//					AutoRegisterButtonText: pulumi.String("example"),
//					Description:            pulumi.String("example"),
//					LinkButtonText:         pulumi.String("example"),
//					PrivacyLinkText:        pulumi.String("example"),
//					Title:                  pulumi.String("example"),
//					TosAndPrivacyLabel:     pulumi.String("example"),
//					TosConfirm:             pulumi.String("example"),
//					TosConfirmAnd:          "example",
//					TosLinkText:            pulumi.String("example"),
//				},
//				FooterText: &zitadel.LoginTextsFooterTextArgs{
//					Help:          pulumi.String("example"),
//					PrivacyPolicy: pulumi.String("example"),
//					Tos:           pulumi.String("example"),
//				},
//				InitMfaDoneText: &zitadel.LoginTextsInitMfaDoneTextArgs{
//					CancelButtonText: pulumi.String("example"),
//					Description:      pulumi.String("example"),
//					NextButtonText:   pulumi.String("example"),
//					Title:            pulumi.String("example"),
//				},
//				InitMfaOtpText: &zitadel.LoginTextsInitMfaOtpTextArgs{
//					CancelButtonText: pulumi.String("example"),
//					CodeLabel:        pulumi.String("example"),
//					Description:      pulumi.String("example"),
//					DescriptionOtp:   pulumi.String("example"),
//					NextButtonText:   pulumi.String("example"),
//					SecretLabel:      pulumi.String("example"),
//					Title:            pulumi.String("example"),
//				},
//				InitMfaPromptText: &zitadel.LoginTextsInitMfaPromptTextArgs{
//					Description:    pulumi.String("example"),
//					NextButtonText: pulumi.String("example"),
//					OtpOption:      pulumi.String("example"),
//					SkipButtonText: pulumi.String("example"),
//					Title:          pulumi.String("example"),
//					U2fOption:      pulumi.String("example"),
//				},
//				InitMfaU2fText: &zitadel.LoginTextsInitMfaU2fTextArgs{
//					Description:             pulumi.String("example"),
//					ErrorRetry:              pulumi.String("example"),
//					NotSupported:            pulumi.String("example"),
//					RegisterTokenButtonText: pulumi.String("example"),
//					Title:                   pulumi.String("example"),
//					TokenNameLabel:          pulumi.String("example"),
//				},
//				InitPasswordDoneText: &zitadel.LoginTextsInitPasswordDoneTextArgs{
//					CancelButtonText: pulumi.String("example"),
//					Description:      pulumi.String("example"),
//					NextButtonText:   pulumi.String("example"),
//					Title:            pulumi.String("example"),
//				},
//				InitPasswordText: &zitadel.LoginTextsInitPasswordTextArgs{
//					CodeLabel:               pulumi.String("example"),
//					Description:             pulumi.String("example"),
//					NewPasswordConfirmLabel: pulumi.String("example"),
//					NewPasswordLabel:        pulumi.String("example"),
//					NextButtonText:          pulumi.String("example"),
//					ResendButtonText:        pulumi.String("example"),
//					Title:                   pulumi.String("example"),
//				},
//				InitializeDoneText: &zitadel.LoginTextsInitializeDoneTextArgs{
//					CancelButtonText: pulumi.String("example"),
//					Description:      pulumi.String("example"),
//					NextButtonText:   pulumi.String("example"),
//					Title:            pulumi.String("example"),
//				},
//				InitializeUserText: &zitadel.LoginTextsInitializeUserTextArgs{
//					CodeLabel:               pulumi.String("example"),
//					Description:             pulumi.String("example"),
//					NewPasswordConfirmLabel: pulumi.String("example"),
//					NewPasswordLabel:        pulumi.String("example"),
//					NextButtonText:          pulumi.String("example"),
//					ResendButtonText:        pulumi.String("example"),
//					Title:                   pulumi.String("example"),
//				},
//				LinkingUserDoneText: &zitadel.LoginTextsLinkingUserDoneTextArgs{
//					CancelButtonText: pulumi.String("example"),
//					Description:      pulumi.String("example"),
//					NextButtonText:   pulumi.String("example"),
//					Title:            pulumi.String("example"),
//				},
//				LoginText: &zitadel.LoginTextsLoginTextArgs{
//					Description:               pulumi.String("example"),
//					DescriptionLinkingProcess: pulumi.String("example"),
//					ExternalUserDescription:   pulumi.String("example"),
//					LoginNameLabel:            pulumi.String("example"),
//					LoginNamePlaceholder:      pulumi.String("example"),
//					NextButtonText:            pulumi.String("example"),
//					RegisterButtonText:        pulumi.String("example"),
//					Title:                     pulumi.String("example"),
//					TitleLinkingProcess:       pulumi.String("example"),
//					UserMustBeMemberOfOrg:     pulumi.String("example"),
//					UserNamePlaceholder:       pulumi.String("example"),
//				},
//				LogoutText: &zitadel.LoginTextsLogoutTextArgs{
//					Description:     pulumi.String("example"),
//					LoginButtonText: pulumi.String("example"),
//					Title:           pulumi.String("example"),
//				},
//				MfaProvidersText: &zitadel.LoginTextsMfaProvidersTextArgs{
//					ChooseOther: pulumi.String("example"),
//					Otp:         pulumi.String("example"),
//					U2f:         pulumi.String("example"),
//				},
//				PasswordChangeDoneText: &zitadel.LoginTextsPasswordChangeDoneTextArgs{
//					Description:    pulumi.String("example"),
//					NextButtonText: pulumi.String("example"),
//					Title:          pulumi.String("example"),
//				},
//				PasswordChangeText: &zitadel.LoginTextsPasswordChangeTextArgs{
//					CancelButtonText:        pulumi.String("example"),
//					Description:             pulumi.String("example"),
//					NewPasswordConfirmLabel: pulumi.String("example"),
//					NewPasswordLabel:        pulumi.String("example"),
//					NextButtonText:          pulumi.String("example"),
//					OldPasswordLabel:        pulumi.String("example"),
//					Title:                   pulumi.String("example"),
//				},
//				PasswordResetDoneText: &zitadel.LoginTextsPasswordResetDoneTextArgs{
//					Description:    pulumi.String("example"),
//					NextButtonText: pulumi.String("example"),
//					Title:          pulumi.String("example"),
//				},
//				PasswordText: &zitadel.LoginTextsPasswordTextArgs{
//					BackButtonText: pulumi.String("example"),
//					Confirmation:   pulumi.String("example"),
//					Description:    pulumi.String("example"),
//					HasLowercase:   pulumi.String("example"),
//					HasNumber:      pulumi.String("example"),
//					HasSymbol:      pulumi.String("example"),
//					HasUppercase:   pulumi.String("example"),
//					MinLength:      pulumi.String("example"),
//					NextButtonText: pulumi.String("example"),
//					PasswordLabel:  pulumi.String("example"),
//					ResetLinkText:  pulumi.String("example"),
//					Title:          pulumi.String("example"),
//				},
//				PasswordlessPromptText: &zitadel.LoginTextsPasswordlessPromptTextArgs{
//					Description:            pulumi.String("example"),
//					DescriptionInit:        pulumi.String("example"),
//					NextButtonText:         pulumi.String("example"),
//					PasswordlessButtonText: pulumi.String("example"),
//					SkipButtonText:         pulumi.String("example"),
//					Title:                  pulumi.String("example"),
//				},
//				PasswordlessRegistrationDoneText: &zitadel.LoginTextsPasswordlessRegistrationDoneTextArgs{
//					CancelButtonText: pulumi.String("example"),
//					Description:      pulumi.String("example"),
//					DescriptionClose: pulumi.String("example"),
//					NextButtonText:   pulumi.String("example"),
//					Title:            pulumi.String("example"),
//				},
//				PasswordlessRegistrationText: &zitadel.LoginTextsPasswordlessRegistrationTextArgs{
//					Description:             pulumi.String("example"),
//					ErrorRetry:              pulumi.String("example"),
//					NotSupported:            pulumi.String("example"),
//					RegisterTokenButtonText: pulumi.String("example"),
//					Title:                   pulumi.String("example"),
//					TokenNameLabel:          pulumi.String("example"),
//				},
//				PasswordlessText: &zitadel.LoginTextsPasswordlessTextArgs{
//					Description:             pulumi.String("example"),
//					ErrorRetry:              pulumi.String("example"),
//					LoginWithPwButtonText:   pulumi.String("example"),
//					NotSupported:            pulumi.String("example"),
//					Title:                   pulumi.String("example"),
//					ValidateTokenButtonText: pulumi.String("example"),
//				},
//				RegistrationOptionText: &zitadel.LoginTextsRegistrationOptionTextArgs{
//					Description:              pulumi.String("example"),
//					ExternalLoginDescription: pulumi.String("example"),
//					Title:                    pulumi.String("example"),
//					UserNameButtonText:       pulumi.String("example"),
//				},
//				RegistrationOrgText: &zitadel.LoginTextsRegistrationOrgTextArgs{
//					Description:          pulumi.String("example"),
//					EmailLabel:           pulumi.String("example"),
//					FirstnameLabel:       pulumi.String("example"),
//					LastnameLabel:        pulumi.String("example"),
//					OrgnameLabel:         pulumi.String("example"),
//					PasswordConfirmLabel: pulumi.String("example"),
//					PasswordLabel:        pulumi.String("example"),
//					PrivacyLinkText:      pulumi.String("example"),
//					SaveButtonText:       pulumi.String("example"),
//					Title:                pulumi.String("example"),
//					TosAndPrivacyLabel:   pulumi.String("example"),
//					TosConfirm:           pulumi.String("example"),
//					TosConfirmAnd:        "example",
//					TosLinkText:          pulumi.String("example"),
//					UsernameLabel:        pulumi.String("example"),
//				},
//				RegistrationUserText: &zitadel.LoginTextsRegistrationUserTextArgs{
//					BackButtonText:         pulumi.String("example"),
//					Description:            pulumi.String("example"),
//					DescriptionOrgRegister: pulumi.String("example"),
//					EmailLabel:             pulumi.String("example"),
//					FirstnameLabel:         pulumi.String("example"),
//					GenderLabel:            pulumi.String("example"),
//					LanguageLabel:          pulumi.String("example"),
//					LastnameLabel:          pulumi.String("example"),
//					NextButtonText:         pulumi.String("example"),
//					PasswordConfirmLabel:   pulumi.String("example"),
//					PasswordLabel:          pulumi.String("example"),
//					PrivacyLinkText:        pulumi.String("example"),
//					Title:                  pulumi.String("example"),
//					TosAndPrivacyLabel:     pulumi.String("example"),
//					TosConfirm:             pulumi.String("example"),
//					TosConfirmAnd:          "example",
//					TosLinkText:            pulumi.String("example"),
//					UsernameLabel:          pulumi.String("example"),
//				},
//				SelectAccountText: &zitadel.LoginTextsSelectAccountTextArgs{
//					Description:               pulumi.String("example"),
//					DescriptionLinkingProcess: pulumi.String("example"),
//					OtherUser:                 pulumi.String("example"),
//					SessionStateActive:        pulumi.String("example"),
//					SessionStateInactive:      pulumi.String("example"),
//					Title:                     pulumi.String("example"),
//					TitleLinkingProcess:       pulumi.String("example"),
//					UserMustBeMemberOfOrg:     pulumi.String("example"),
//				},
//				SuccessLoginText: &zitadel.LoginTextsSuccessLoginTextArgs{
//					AutoRedirectDescription: pulumi.String("example"),
//					NextButtonText:          pulumi.String("example"),
//					RedirectedDescription:   pulumi.String("example"),
//					Title:                   pulumi.String("example"),
//				},
//				UsernameChangeDoneText: &zitadel.LoginTextsUsernameChangeDoneTextArgs{
//					Description:    pulumi.String("example"),
//					NextButtonText: pulumi.String("example"),
//					Title:          pulumi.String("example"),
//				},
//				UsernameChangeText: &zitadel.LoginTextsUsernameChangeTextArgs{
//					CancelButtonText: pulumi.String("example"),
//					Description:      pulumi.String("example"),
//					NextButtonText:   pulumi.String("example"),
//					Title:            pulumi.String("example"),
//					UsernameLabel:    pulumi.String("example"),
//				},
//				VerifyMfaOtpText: &zitadel.LoginTextsVerifyMfaOtpTextArgs{
//					CodeLabel:      pulumi.String("example"),
//					Description:    pulumi.String("example"),
//					NextButtonText: pulumi.String("example"),
//					Title:          pulumi.String("example"),
//				},
//				VerifyMfaU2fText: &zitadel.LoginTextsVerifyMfaU2fTextArgs{
//					Description:       pulumi.String("example"),
//					ErrorRetry:        pulumi.String("example"),
//					NotSupported:      pulumi.String("example"),
//					Title:             pulumi.String("example"),
//					ValidateTokenText: pulumi.String("example"),
//				},
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
type LoginTexts struct {
	pulumi.CustomResourceState

	EmailVerificationDoneText            LoginTextsEmailVerificationDoneTextPtrOutput            `pulumi:"emailVerificationDoneText"`
	EmailVerificationText                LoginTextsEmailVerificationTextPtrOutput                `pulumi:"emailVerificationText"`
	ExternalRegistrationUserOverviewText LoginTextsExternalRegistrationUserOverviewTextPtrOutput `pulumi:"externalRegistrationUserOverviewText"`
	ExternalUserNotFoundText             LoginTextsExternalUserNotFoundTextPtrOutput             `pulumi:"externalUserNotFoundText"`
	FooterText                           LoginTextsFooterTextPtrOutput                           `pulumi:"footerText"`
	InitMfaDoneText                      LoginTextsInitMfaDoneTextPtrOutput                      `pulumi:"initMfaDoneText"`
	InitMfaOtpText                       LoginTextsInitMfaOtpTextPtrOutput                       `pulumi:"initMfaOtpText"`
	InitMfaPromptText                    LoginTextsInitMfaPromptTextPtrOutput                    `pulumi:"initMfaPromptText"`
	InitMfaU2fText                       LoginTextsInitMfaU2fTextPtrOutput                       `pulumi:"initMfaU2fText"`
	InitPasswordDoneText                 LoginTextsInitPasswordDoneTextPtrOutput                 `pulumi:"initPasswordDoneText"`
	InitPasswordText                     LoginTextsInitPasswordTextPtrOutput                     `pulumi:"initPasswordText"`
	InitializeDoneText                   LoginTextsInitializeDoneTextPtrOutput                   `pulumi:"initializeDoneText"`
	InitializeUserText                   LoginTextsInitializeUserTextPtrOutput                   `pulumi:"initializeUserText"`
	Language                             pulumi.StringOutput                                     `pulumi:"language"`
	LinkingUserDoneText                  LoginTextsLinkingUserDoneTextPtrOutput                  `pulumi:"linkingUserDoneText"`
	LinkingUserPromptText                LoginTextsLinkingUserPromptTextPtrOutput                `pulumi:"linkingUserPromptText"`
	LoginText                            LoginTextsLoginTextPtrOutput                            `pulumi:"loginText"`
	LogoutText                           LoginTextsLogoutTextPtrOutput                           `pulumi:"logoutText"`
	MfaProvidersText                     LoginTextsMfaProvidersTextPtrOutput                     `pulumi:"mfaProvidersText"`
	OrgId                                pulumi.StringOutput                                     `pulumi:"orgId"`
	PasswordChangeDoneText               LoginTextsPasswordChangeDoneTextPtrOutput               `pulumi:"passwordChangeDoneText"`
	PasswordChangeText                   LoginTextsPasswordChangeTextPtrOutput                   `pulumi:"passwordChangeText"`
	PasswordResetDoneText                LoginTextsPasswordResetDoneTextPtrOutput                `pulumi:"passwordResetDoneText"`
	PasswordText                         LoginTextsPasswordTextPtrOutput                         `pulumi:"passwordText"`
	PasswordlessPromptText               LoginTextsPasswordlessPromptTextPtrOutput               `pulumi:"passwordlessPromptText"`
	PasswordlessRegistrationDoneText     LoginTextsPasswordlessRegistrationDoneTextPtrOutput     `pulumi:"passwordlessRegistrationDoneText"`
	PasswordlessRegistrationText         LoginTextsPasswordlessRegistrationTextPtrOutput         `pulumi:"passwordlessRegistrationText"`
	PasswordlessText                     LoginTextsPasswordlessTextPtrOutput                     `pulumi:"passwordlessText"`
	RegistrationOptionText               LoginTextsRegistrationOptionTextPtrOutput               `pulumi:"registrationOptionText"`
	RegistrationOrgText                  LoginTextsRegistrationOrgTextPtrOutput                  `pulumi:"registrationOrgText"`
	RegistrationUserText                 LoginTextsRegistrationUserTextPtrOutput                 `pulumi:"registrationUserText"`
	SelectAccountText                    LoginTextsSelectAccountTextPtrOutput                    `pulumi:"selectAccountText"`
	SuccessLoginText                     LoginTextsSuccessLoginTextPtrOutput                     `pulumi:"successLoginText"`
	UsernameChangeDoneText               LoginTextsUsernameChangeDoneTextPtrOutput               `pulumi:"usernameChangeDoneText"`
	UsernameChangeText                   LoginTextsUsernameChangeTextPtrOutput                   `pulumi:"usernameChangeText"`
	VerifyMfaOtpText                     LoginTextsVerifyMfaOtpTextPtrOutput                     `pulumi:"verifyMfaOtpText"`
	VerifyMfaU2fText                     LoginTextsVerifyMfaU2fTextPtrOutput                     `pulumi:"verifyMfaU2fText"`
}

// NewLoginTexts registers a new resource with the given unique name, arguments, and options.
func NewLoginTexts(ctx *pulumi.Context,
	name string, args *LoginTextsArgs, opts ...pulumi.ResourceOption) (*LoginTexts, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Language == nil {
		return nil, errors.New("invalid value for required argument 'Language'")
	}
	if args.OrgId == nil {
		return nil, errors.New("invalid value for required argument 'OrgId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource LoginTexts
	err := ctx.RegisterResource("zitadel:index/loginTexts:LoginTexts", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetLoginTexts gets an existing LoginTexts resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetLoginTexts(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *LoginTextsState, opts ...pulumi.ResourceOption) (*LoginTexts, error) {
	var resource LoginTexts
	err := ctx.ReadResource("zitadel:index/loginTexts:LoginTexts", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering LoginTexts resources.
type loginTextsState struct {
	EmailVerificationDoneText            *LoginTextsEmailVerificationDoneText            `pulumi:"emailVerificationDoneText"`
	EmailVerificationText                *LoginTextsEmailVerificationText                `pulumi:"emailVerificationText"`
	ExternalRegistrationUserOverviewText *LoginTextsExternalRegistrationUserOverviewText `pulumi:"externalRegistrationUserOverviewText"`
	ExternalUserNotFoundText             *LoginTextsExternalUserNotFoundText             `pulumi:"externalUserNotFoundText"`
	FooterText                           *LoginTextsFooterText                           `pulumi:"footerText"`
	InitMfaDoneText                      *LoginTextsInitMfaDoneText                      `pulumi:"initMfaDoneText"`
	InitMfaOtpText                       *LoginTextsInitMfaOtpText                       `pulumi:"initMfaOtpText"`
	InitMfaPromptText                    *LoginTextsInitMfaPromptText                    `pulumi:"initMfaPromptText"`
	InitMfaU2fText                       *LoginTextsInitMfaU2fText                       `pulumi:"initMfaU2fText"`
	InitPasswordDoneText                 *LoginTextsInitPasswordDoneText                 `pulumi:"initPasswordDoneText"`
	InitPasswordText                     *LoginTextsInitPasswordText                     `pulumi:"initPasswordText"`
	InitializeDoneText                   *LoginTextsInitializeDoneText                   `pulumi:"initializeDoneText"`
	InitializeUserText                   *LoginTextsInitializeUserText                   `pulumi:"initializeUserText"`
	Language                             *string                                         `pulumi:"language"`
	LinkingUserDoneText                  *LoginTextsLinkingUserDoneText                  `pulumi:"linkingUserDoneText"`
	LinkingUserPromptText                *LoginTextsLinkingUserPromptText                `pulumi:"linkingUserPromptText"`
	LoginText                            *LoginTextsLoginText                            `pulumi:"loginText"`
	LogoutText                           *LoginTextsLogoutText                           `pulumi:"logoutText"`
	MfaProvidersText                     *LoginTextsMfaProvidersText                     `pulumi:"mfaProvidersText"`
	OrgId                                *string                                         `pulumi:"orgId"`
	PasswordChangeDoneText               *LoginTextsPasswordChangeDoneText               `pulumi:"passwordChangeDoneText"`
	PasswordChangeText                   *LoginTextsPasswordChangeText                   `pulumi:"passwordChangeText"`
	PasswordResetDoneText                *LoginTextsPasswordResetDoneText                `pulumi:"passwordResetDoneText"`
	PasswordText                         *LoginTextsPasswordText                         `pulumi:"passwordText"`
	PasswordlessPromptText               *LoginTextsPasswordlessPromptText               `pulumi:"passwordlessPromptText"`
	PasswordlessRegistrationDoneText     *LoginTextsPasswordlessRegistrationDoneText     `pulumi:"passwordlessRegistrationDoneText"`
	PasswordlessRegistrationText         *LoginTextsPasswordlessRegistrationText         `pulumi:"passwordlessRegistrationText"`
	PasswordlessText                     *LoginTextsPasswordlessText                     `pulumi:"passwordlessText"`
	RegistrationOptionText               *LoginTextsRegistrationOptionText               `pulumi:"registrationOptionText"`
	RegistrationOrgText                  *LoginTextsRegistrationOrgText                  `pulumi:"registrationOrgText"`
	RegistrationUserText                 *LoginTextsRegistrationUserText                 `pulumi:"registrationUserText"`
	SelectAccountText                    *LoginTextsSelectAccountText                    `pulumi:"selectAccountText"`
	SuccessLoginText                     *LoginTextsSuccessLoginText                     `pulumi:"successLoginText"`
	UsernameChangeDoneText               *LoginTextsUsernameChangeDoneText               `pulumi:"usernameChangeDoneText"`
	UsernameChangeText                   *LoginTextsUsernameChangeText                   `pulumi:"usernameChangeText"`
	VerifyMfaOtpText                     *LoginTextsVerifyMfaOtpText                     `pulumi:"verifyMfaOtpText"`
	VerifyMfaU2fText                     *LoginTextsVerifyMfaU2fText                     `pulumi:"verifyMfaU2fText"`
}

type LoginTextsState struct {
	EmailVerificationDoneText            LoginTextsEmailVerificationDoneTextPtrInput
	EmailVerificationText                LoginTextsEmailVerificationTextPtrInput
	ExternalRegistrationUserOverviewText LoginTextsExternalRegistrationUserOverviewTextPtrInput
	ExternalUserNotFoundText             LoginTextsExternalUserNotFoundTextPtrInput
	FooterText                           LoginTextsFooterTextPtrInput
	InitMfaDoneText                      LoginTextsInitMfaDoneTextPtrInput
	InitMfaOtpText                       LoginTextsInitMfaOtpTextPtrInput
	InitMfaPromptText                    LoginTextsInitMfaPromptTextPtrInput
	InitMfaU2fText                       LoginTextsInitMfaU2fTextPtrInput
	InitPasswordDoneText                 LoginTextsInitPasswordDoneTextPtrInput
	InitPasswordText                     LoginTextsInitPasswordTextPtrInput
	InitializeDoneText                   LoginTextsInitializeDoneTextPtrInput
	InitializeUserText                   LoginTextsInitializeUserTextPtrInput
	Language                             pulumi.StringPtrInput
	LinkingUserDoneText                  LoginTextsLinkingUserDoneTextPtrInput
	LinkingUserPromptText                LoginTextsLinkingUserPromptTextPtrInput
	LoginText                            LoginTextsLoginTextPtrInput
	LogoutText                           LoginTextsLogoutTextPtrInput
	MfaProvidersText                     LoginTextsMfaProvidersTextPtrInput
	OrgId                                pulumi.StringPtrInput
	PasswordChangeDoneText               LoginTextsPasswordChangeDoneTextPtrInput
	PasswordChangeText                   LoginTextsPasswordChangeTextPtrInput
	PasswordResetDoneText                LoginTextsPasswordResetDoneTextPtrInput
	PasswordText                         LoginTextsPasswordTextPtrInput
	PasswordlessPromptText               LoginTextsPasswordlessPromptTextPtrInput
	PasswordlessRegistrationDoneText     LoginTextsPasswordlessRegistrationDoneTextPtrInput
	PasswordlessRegistrationText         LoginTextsPasswordlessRegistrationTextPtrInput
	PasswordlessText                     LoginTextsPasswordlessTextPtrInput
	RegistrationOptionText               LoginTextsRegistrationOptionTextPtrInput
	RegistrationOrgText                  LoginTextsRegistrationOrgTextPtrInput
	RegistrationUserText                 LoginTextsRegistrationUserTextPtrInput
	SelectAccountText                    LoginTextsSelectAccountTextPtrInput
	SuccessLoginText                     LoginTextsSuccessLoginTextPtrInput
	UsernameChangeDoneText               LoginTextsUsernameChangeDoneTextPtrInput
	UsernameChangeText                   LoginTextsUsernameChangeTextPtrInput
	VerifyMfaOtpText                     LoginTextsVerifyMfaOtpTextPtrInput
	VerifyMfaU2fText                     LoginTextsVerifyMfaU2fTextPtrInput
}

func (LoginTextsState) ElementType() reflect.Type {
	return reflect.TypeOf((*loginTextsState)(nil)).Elem()
}

type loginTextsArgs struct {
	EmailVerificationDoneText            *LoginTextsEmailVerificationDoneText            `pulumi:"emailVerificationDoneText"`
	EmailVerificationText                *LoginTextsEmailVerificationText                `pulumi:"emailVerificationText"`
	ExternalRegistrationUserOverviewText *LoginTextsExternalRegistrationUserOverviewText `pulumi:"externalRegistrationUserOverviewText"`
	ExternalUserNotFoundText             *LoginTextsExternalUserNotFoundText             `pulumi:"externalUserNotFoundText"`
	FooterText                           *LoginTextsFooterText                           `pulumi:"footerText"`
	InitMfaDoneText                      *LoginTextsInitMfaDoneText                      `pulumi:"initMfaDoneText"`
	InitMfaOtpText                       *LoginTextsInitMfaOtpText                       `pulumi:"initMfaOtpText"`
	InitMfaPromptText                    *LoginTextsInitMfaPromptText                    `pulumi:"initMfaPromptText"`
	InitMfaU2fText                       *LoginTextsInitMfaU2fText                       `pulumi:"initMfaU2fText"`
	InitPasswordDoneText                 *LoginTextsInitPasswordDoneText                 `pulumi:"initPasswordDoneText"`
	InitPasswordText                     *LoginTextsInitPasswordText                     `pulumi:"initPasswordText"`
	InitializeDoneText                   *LoginTextsInitializeDoneText                   `pulumi:"initializeDoneText"`
	InitializeUserText                   *LoginTextsInitializeUserText                   `pulumi:"initializeUserText"`
	Language                             string                                          `pulumi:"language"`
	LinkingUserDoneText                  *LoginTextsLinkingUserDoneText                  `pulumi:"linkingUserDoneText"`
	LinkingUserPromptText                *LoginTextsLinkingUserPromptText                `pulumi:"linkingUserPromptText"`
	LoginText                            *LoginTextsLoginText                            `pulumi:"loginText"`
	LogoutText                           *LoginTextsLogoutText                           `pulumi:"logoutText"`
	MfaProvidersText                     *LoginTextsMfaProvidersText                     `pulumi:"mfaProvidersText"`
	OrgId                                string                                          `pulumi:"orgId"`
	PasswordChangeDoneText               *LoginTextsPasswordChangeDoneText               `pulumi:"passwordChangeDoneText"`
	PasswordChangeText                   *LoginTextsPasswordChangeText                   `pulumi:"passwordChangeText"`
	PasswordResetDoneText                *LoginTextsPasswordResetDoneText                `pulumi:"passwordResetDoneText"`
	PasswordText                         *LoginTextsPasswordText                         `pulumi:"passwordText"`
	PasswordlessPromptText               *LoginTextsPasswordlessPromptText               `pulumi:"passwordlessPromptText"`
	PasswordlessRegistrationDoneText     *LoginTextsPasswordlessRegistrationDoneText     `pulumi:"passwordlessRegistrationDoneText"`
	PasswordlessRegistrationText         *LoginTextsPasswordlessRegistrationText         `pulumi:"passwordlessRegistrationText"`
	PasswordlessText                     *LoginTextsPasswordlessText                     `pulumi:"passwordlessText"`
	RegistrationOptionText               *LoginTextsRegistrationOptionText               `pulumi:"registrationOptionText"`
	RegistrationOrgText                  *LoginTextsRegistrationOrgText                  `pulumi:"registrationOrgText"`
	RegistrationUserText                 *LoginTextsRegistrationUserText                 `pulumi:"registrationUserText"`
	SelectAccountText                    *LoginTextsSelectAccountText                    `pulumi:"selectAccountText"`
	SuccessLoginText                     *LoginTextsSuccessLoginText                     `pulumi:"successLoginText"`
	UsernameChangeDoneText               *LoginTextsUsernameChangeDoneText               `pulumi:"usernameChangeDoneText"`
	UsernameChangeText                   *LoginTextsUsernameChangeText                   `pulumi:"usernameChangeText"`
	VerifyMfaOtpText                     *LoginTextsVerifyMfaOtpText                     `pulumi:"verifyMfaOtpText"`
	VerifyMfaU2fText                     *LoginTextsVerifyMfaU2fText                     `pulumi:"verifyMfaU2fText"`
}

// The set of arguments for constructing a LoginTexts resource.
type LoginTextsArgs struct {
	EmailVerificationDoneText            LoginTextsEmailVerificationDoneTextPtrInput
	EmailVerificationText                LoginTextsEmailVerificationTextPtrInput
	ExternalRegistrationUserOverviewText LoginTextsExternalRegistrationUserOverviewTextPtrInput
	ExternalUserNotFoundText             LoginTextsExternalUserNotFoundTextPtrInput
	FooterText                           LoginTextsFooterTextPtrInput
	InitMfaDoneText                      LoginTextsInitMfaDoneTextPtrInput
	InitMfaOtpText                       LoginTextsInitMfaOtpTextPtrInput
	InitMfaPromptText                    LoginTextsInitMfaPromptTextPtrInput
	InitMfaU2fText                       LoginTextsInitMfaU2fTextPtrInput
	InitPasswordDoneText                 LoginTextsInitPasswordDoneTextPtrInput
	InitPasswordText                     LoginTextsInitPasswordTextPtrInput
	InitializeDoneText                   LoginTextsInitializeDoneTextPtrInput
	InitializeUserText                   LoginTextsInitializeUserTextPtrInput
	Language                             pulumi.StringInput
	LinkingUserDoneText                  LoginTextsLinkingUserDoneTextPtrInput
	LinkingUserPromptText                LoginTextsLinkingUserPromptTextPtrInput
	LoginText                            LoginTextsLoginTextPtrInput
	LogoutText                           LoginTextsLogoutTextPtrInput
	MfaProvidersText                     LoginTextsMfaProvidersTextPtrInput
	OrgId                                pulumi.StringInput
	PasswordChangeDoneText               LoginTextsPasswordChangeDoneTextPtrInput
	PasswordChangeText                   LoginTextsPasswordChangeTextPtrInput
	PasswordResetDoneText                LoginTextsPasswordResetDoneTextPtrInput
	PasswordText                         LoginTextsPasswordTextPtrInput
	PasswordlessPromptText               LoginTextsPasswordlessPromptTextPtrInput
	PasswordlessRegistrationDoneText     LoginTextsPasswordlessRegistrationDoneTextPtrInput
	PasswordlessRegistrationText         LoginTextsPasswordlessRegistrationTextPtrInput
	PasswordlessText                     LoginTextsPasswordlessTextPtrInput
	RegistrationOptionText               LoginTextsRegistrationOptionTextPtrInput
	RegistrationOrgText                  LoginTextsRegistrationOrgTextPtrInput
	RegistrationUserText                 LoginTextsRegistrationUserTextPtrInput
	SelectAccountText                    LoginTextsSelectAccountTextPtrInput
	SuccessLoginText                     LoginTextsSuccessLoginTextPtrInput
	UsernameChangeDoneText               LoginTextsUsernameChangeDoneTextPtrInput
	UsernameChangeText                   LoginTextsUsernameChangeTextPtrInput
	VerifyMfaOtpText                     LoginTextsVerifyMfaOtpTextPtrInput
	VerifyMfaU2fText                     LoginTextsVerifyMfaU2fTextPtrInput
}

func (LoginTextsArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*loginTextsArgs)(nil)).Elem()
}

type LoginTextsInput interface {
	pulumi.Input

	ToLoginTextsOutput() LoginTextsOutput
	ToLoginTextsOutputWithContext(ctx context.Context) LoginTextsOutput
}

func (*LoginTexts) ElementType() reflect.Type {
	return reflect.TypeOf((**LoginTexts)(nil)).Elem()
}

func (i *LoginTexts) ToLoginTextsOutput() LoginTextsOutput {
	return i.ToLoginTextsOutputWithContext(context.Background())
}

func (i *LoginTexts) ToLoginTextsOutputWithContext(ctx context.Context) LoginTextsOutput {
	return pulumi.ToOutputWithContext(ctx, i).(LoginTextsOutput)
}

type LoginTextsOutput struct{ *pulumi.OutputState }

func (LoginTextsOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**LoginTexts)(nil)).Elem()
}

func (o LoginTextsOutput) ToLoginTextsOutput() LoginTextsOutput {
	return o
}

func (o LoginTextsOutput) ToLoginTextsOutputWithContext(ctx context.Context) LoginTextsOutput {
	return o
}

func (o LoginTextsOutput) EmailVerificationDoneText() LoginTextsEmailVerificationDoneTextPtrOutput {
	return o.ApplyT(func(v *LoginTexts) LoginTextsEmailVerificationDoneTextPtrOutput { return v.EmailVerificationDoneText }).(LoginTextsEmailVerificationDoneTextPtrOutput)
}

func (o LoginTextsOutput) EmailVerificationText() LoginTextsEmailVerificationTextPtrOutput {
	return o.ApplyT(func(v *LoginTexts) LoginTextsEmailVerificationTextPtrOutput { return v.EmailVerificationText }).(LoginTextsEmailVerificationTextPtrOutput)
}

func (o LoginTextsOutput) ExternalRegistrationUserOverviewText() LoginTextsExternalRegistrationUserOverviewTextPtrOutput {
	return o.ApplyT(func(v *LoginTexts) LoginTextsExternalRegistrationUserOverviewTextPtrOutput {
		return v.ExternalRegistrationUserOverviewText
	}).(LoginTextsExternalRegistrationUserOverviewTextPtrOutput)
}

func (o LoginTextsOutput) ExternalUserNotFoundText() LoginTextsExternalUserNotFoundTextPtrOutput {
	return o.ApplyT(func(v *LoginTexts) LoginTextsExternalUserNotFoundTextPtrOutput { return v.ExternalUserNotFoundText }).(LoginTextsExternalUserNotFoundTextPtrOutput)
}

func (o LoginTextsOutput) FooterText() LoginTextsFooterTextPtrOutput {
	return o.ApplyT(func(v *LoginTexts) LoginTextsFooterTextPtrOutput { return v.FooterText }).(LoginTextsFooterTextPtrOutput)
}

func (o LoginTextsOutput) InitMfaDoneText() LoginTextsInitMfaDoneTextPtrOutput {
	return o.ApplyT(func(v *LoginTexts) LoginTextsInitMfaDoneTextPtrOutput { return v.InitMfaDoneText }).(LoginTextsInitMfaDoneTextPtrOutput)
}

func (o LoginTextsOutput) InitMfaOtpText() LoginTextsInitMfaOtpTextPtrOutput {
	return o.ApplyT(func(v *LoginTexts) LoginTextsInitMfaOtpTextPtrOutput { return v.InitMfaOtpText }).(LoginTextsInitMfaOtpTextPtrOutput)
}

func (o LoginTextsOutput) InitMfaPromptText() LoginTextsInitMfaPromptTextPtrOutput {
	return o.ApplyT(func(v *LoginTexts) LoginTextsInitMfaPromptTextPtrOutput { return v.InitMfaPromptText }).(LoginTextsInitMfaPromptTextPtrOutput)
}

func (o LoginTextsOutput) InitMfaU2fText() LoginTextsInitMfaU2fTextPtrOutput {
	return o.ApplyT(func(v *LoginTexts) LoginTextsInitMfaU2fTextPtrOutput { return v.InitMfaU2fText }).(LoginTextsInitMfaU2fTextPtrOutput)
}

func (o LoginTextsOutput) InitPasswordDoneText() LoginTextsInitPasswordDoneTextPtrOutput {
	return o.ApplyT(func(v *LoginTexts) LoginTextsInitPasswordDoneTextPtrOutput { return v.InitPasswordDoneText }).(LoginTextsInitPasswordDoneTextPtrOutput)
}

func (o LoginTextsOutput) InitPasswordText() LoginTextsInitPasswordTextPtrOutput {
	return o.ApplyT(func(v *LoginTexts) LoginTextsInitPasswordTextPtrOutput { return v.InitPasswordText }).(LoginTextsInitPasswordTextPtrOutput)
}

func (o LoginTextsOutput) InitializeDoneText() LoginTextsInitializeDoneTextPtrOutput {
	return o.ApplyT(func(v *LoginTexts) LoginTextsInitializeDoneTextPtrOutput { return v.InitializeDoneText }).(LoginTextsInitializeDoneTextPtrOutput)
}

func (o LoginTextsOutput) InitializeUserText() LoginTextsInitializeUserTextPtrOutput {
	return o.ApplyT(func(v *LoginTexts) LoginTextsInitializeUserTextPtrOutput { return v.InitializeUserText }).(LoginTextsInitializeUserTextPtrOutput)
}

func (o LoginTextsOutput) Language() pulumi.StringOutput {
	return o.ApplyT(func(v *LoginTexts) pulumi.StringOutput { return v.Language }).(pulumi.StringOutput)
}

func (o LoginTextsOutput) LinkingUserDoneText() LoginTextsLinkingUserDoneTextPtrOutput {
	return o.ApplyT(func(v *LoginTexts) LoginTextsLinkingUserDoneTextPtrOutput { return v.LinkingUserDoneText }).(LoginTextsLinkingUserDoneTextPtrOutput)
}

func (o LoginTextsOutput) LinkingUserPromptText() LoginTextsLinkingUserPromptTextPtrOutput {
	return o.ApplyT(func(v *LoginTexts) LoginTextsLinkingUserPromptTextPtrOutput { return v.LinkingUserPromptText }).(LoginTextsLinkingUserPromptTextPtrOutput)
}

func (o LoginTextsOutput) LoginText() LoginTextsLoginTextPtrOutput {
	return o.ApplyT(func(v *LoginTexts) LoginTextsLoginTextPtrOutput { return v.LoginText }).(LoginTextsLoginTextPtrOutput)
}

func (o LoginTextsOutput) LogoutText() LoginTextsLogoutTextPtrOutput {
	return o.ApplyT(func(v *LoginTexts) LoginTextsLogoutTextPtrOutput { return v.LogoutText }).(LoginTextsLogoutTextPtrOutput)
}

func (o LoginTextsOutput) MfaProvidersText() LoginTextsMfaProvidersTextPtrOutput {
	return o.ApplyT(func(v *LoginTexts) LoginTextsMfaProvidersTextPtrOutput { return v.MfaProvidersText }).(LoginTextsMfaProvidersTextPtrOutput)
}

func (o LoginTextsOutput) OrgId() pulumi.StringOutput {
	return o.ApplyT(func(v *LoginTexts) pulumi.StringOutput { return v.OrgId }).(pulumi.StringOutput)
}

func (o LoginTextsOutput) PasswordChangeDoneText() LoginTextsPasswordChangeDoneTextPtrOutput {
	return o.ApplyT(func(v *LoginTexts) LoginTextsPasswordChangeDoneTextPtrOutput { return v.PasswordChangeDoneText }).(LoginTextsPasswordChangeDoneTextPtrOutput)
}

func (o LoginTextsOutput) PasswordChangeText() LoginTextsPasswordChangeTextPtrOutput {
	return o.ApplyT(func(v *LoginTexts) LoginTextsPasswordChangeTextPtrOutput { return v.PasswordChangeText }).(LoginTextsPasswordChangeTextPtrOutput)
}

func (o LoginTextsOutput) PasswordResetDoneText() LoginTextsPasswordResetDoneTextPtrOutput {
	return o.ApplyT(func(v *LoginTexts) LoginTextsPasswordResetDoneTextPtrOutput { return v.PasswordResetDoneText }).(LoginTextsPasswordResetDoneTextPtrOutput)
}

func (o LoginTextsOutput) PasswordText() LoginTextsPasswordTextPtrOutput {
	return o.ApplyT(func(v *LoginTexts) LoginTextsPasswordTextPtrOutput { return v.PasswordText }).(LoginTextsPasswordTextPtrOutput)
}

func (o LoginTextsOutput) PasswordlessPromptText() LoginTextsPasswordlessPromptTextPtrOutput {
	return o.ApplyT(func(v *LoginTexts) LoginTextsPasswordlessPromptTextPtrOutput { return v.PasswordlessPromptText }).(LoginTextsPasswordlessPromptTextPtrOutput)
}

func (o LoginTextsOutput) PasswordlessRegistrationDoneText() LoginTextsPasswordlessRegistrationDoneTextPtrOutput {
	return o.ApplyT(func(v *LoginTexts) LoginTextsPasswordlessRegistrationDoneTextPtrOutput {
		return v.PasswordlessRegistrationDoneText
	}).(LoginTextsPasswordlessRegistrationDoneTextPtrOutput)
}

func (o LoginTextsOutput) PasswordlessRegistrationText() LoginTextsPasswordlessRegistrationTextPtrOutput {
	return o.ApplyT(func(v *LoginTexts) LoginTextsPasswordlessRegistrationTextPtrOutput {
		return v.PasswordlessRegistrationText
	}).(LoginTextsPasswordlessRegistrationTextPtrOutput)
}

func (o LoginTextsOutput) PasswordlessText() LoginTextsPasswordlessTextPtrOutput {
	return o.ApplyT(func(v *LoginTexts) LoginTextsPasswordlessTextPtrOutput { return v.PasswordlessText }).(LoginTextsPasswordlessTextPtrOutput)
}

func (o LoginTextsOutput) RegistrationOptionText() LoginTextsRegistrationOptionTextPtrOutput {
	return o.ApplyT(func(v *LoginTexts) LoginTextsRegistrationOptionTextPtrOutput { return v.RegistrationOptionText }).(LoginTextsRegistrationOptionTextPtrOutput)
}

func (o LoginTextsOutput) RegistrationOrgText() LoginTextsRegistrationOrgTextPtrOutput {
	return o.ApplyT(func(v *LoginTexts) LoginTextsRegistrationOrgTextPtrOutput { return v.RegistrationOrgText }).(LoginTextsRegistrationOrgTextPtrOutput)
}

func (o LoginTextsOutput) RegistrationUserText() LoginTextsRegistrationUserTextPtrOutput {
	return o.ApplyT(func(v *LoginTexts) LoginTextsRegistrationUserTextPtrOutput { return v.RegistrationUserText }).(LoginTextsRegistrationUserTextPtrOutput)
}

func (o LoginTextsOutput) SelectAccountText() LoginTextsSelectAccountTextPtrOutput {
	return o.ApplyT(func(v *LoginTexts) LoginTextsSelectAccountTextPtrOutput { return v.SelectAccountText }).(LoginTextsSelectAccountTextPtrOutput)
}

func (o LoginTextsOutput) SuccessLoginText() LoginTextsSuccessLoginTextPtrOutput {
	return o.ApplyT(func(v *LoginTexts) LoginTextsSuccessLoginTextPtrOutput { return v.SuccessLoginText }).(LoginTextsSuccessLoginTextPtrOutput)
}

func (o LoginTextsOutput) UsernameChangeDoneText() LoginTextsUsernameChangeDoneTextPtrOutput {
	return o.ApplyT(func(v *LoginTexts) LoginTextsUsernameChangeDoneTextPtrOutput { return v.UsernameChangeDoneText }).(LoginTextsUsernameChangeDoneTextPtrOutput)
}

func (o LoginTextsOutput) UsernameChangeText() LoginTextsUsernameChangeTextPtrOutput {
	return o.ApplyT(func(v *LoginTexts) LoginTextsUsernameChangeTextPtrOutput { return v.UsernameChangeText }).(LoginTextsUsernameChangeTextPtrOutput)
}

func (o LoginTextsOutput) VerifyMfaOtpText() LoginTextsVerifyMfaOtpTextPtrOutput {
	return o.ApplyT(func(v *LoginTexts) LoginTextsVerifyMfaOtpTextPtrOutput { return v.VerifyMfaOtpText }).(LoginTextsVerifyMfaOtpTextPtrOutput)
}

func (o LoginTextsOutput) VerifyMfaU2fText() LoginTextsVerifyMfaU2fTextPtrOutput {
	return o.ApplyT(func(v *LoginTexts) LoginTextsVerifyMfaU2fTextPtrOutput { return v.VerifyMfaU2fText }).(LoginTextsVerifyMfaU2fTextPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*LoginTextsInput)(nil)).Elem(), &LoginTexts{})
	pulumi.RegisterOutputType(LoginTextsOutput{})
}
