// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package zitadel

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/truvity/pulumi-zitadel/sdk/go/zitadel/internal"
)

// Resource representing an organization in ZITADEL, which is the highest level after the instance and contains several other resource including policies if the configuration differs to the default policies on the instance.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/truvity/pulumi-zitadel/sdk/go/zitadel"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := zitadel.NewOrg(ctx, "default", &zitadel.OrgArgs{
//				Name: pulumi.String("terraform-test"),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Import
//
// The resource can be imported using the ID format `<id>`, e.g.
//
// ```sh
// $ pulumi import zitadel:index/org:Org imported '123456789012345678'
// ```
type Org struct {
	pulumi.CustomResourceState

	// Admin users for the organization
	Admins OrgAdminArrayOutput `pulumi:"admins"`
	// True sets the org as default org for the instance. Only one org can be default org. Nothing happens if you set it to false until you set another org as default org.
	IsDefault pulumi.BoolPtrOutput `pulumi:"isDefault"`
	// Name of the org
	Name pulumi.StringOutput `pulumi:"name"`
	// Optionally set a custom unique ID for the organization. If omitted, ZITADEL will generate one.
	OrgId pulumi.StringPtrOutput `pulumi:"orgId"`
	// Primary domain of the org
	PrimaryDomain pulumi.StringOutput `pulumi:"primaryDomain"`
	// State of the org
	State pulumi.StringOutput `pulumi:"state"`
}

// NewOrg registers a new resource with the given unique name, arguments, and options.
func NewOrg(ctx *pulumi.Context,
	name string, args *OrgArgs, opts ...pulumi.ResourceOption) (*Org, error) {
	if args == nil {
		args = &OrgArgs{}
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Org
	err := ctx.RegisterResource("zitadel:index/org:Org", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetOrg gets an existing Org resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetOrg(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *OrgState, opts ...pulumi.ResourceOption) (*Org, error) {
	var resource Org
	err := ctx.ReadResource("zitadel:index/org:Org", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Org resources.
type orgState struct {
	// Admin users for the organization
	Admins []OrgAdmin `pulumi:"admins"`
	// True sets the org as default org for the instance. Only one org can be default org. Nothing happens if you set it to false until you set another org as default org.
	IsDefault *bool `pulumi:"isDefault"`
	// Name of the org
	Name *string `pulumi:"name"`
	// Optionally set a custom unique ID for the organization. If omitted, ZITADEL will generate one.
	OrgId *string `pulumi:"orgId"`
	// Primary domain of the org
	PrimaryDomain *string `pulumi:"primaryDomain"`
	// State of the org
	State *string `pulumi:"state"`
}

type OrgState struct {
	// Admin users for the organization
	Admins OrgAdminArrayInput
	// True sets the org as default org for the instance. Only one org can be default org. Nothing happens if you set it to false until you set another org as default org.
	IsDefault pulumi.BoolPtrInput
	// Name of the org
	Name pulumi.StringPtrInput
	// Optionally set a custom unique ID for the organization. If omitted, ZITADEL will generate one.
	OrgId pulumi.StringPtrInput
	// Primary domain of the org
	PrimaryDomain pulumi.StringPtrInput
	// State of the org
	State pulumi.StringPtrInput
}

func (OrgState) ElementType() reflect.Type {
	return reflect.TypeOf((*orgState)(nil)).Elem()
}

type orgArgs struct {
	// Admin users for the organization
	Admins []OrgAdmin `pulumi:"admins"`
	// True sets the org as default org for the instance. Only one org can be default org. Nothing happens if you set it to false until you set another org as default org.
	IsDefault *bool `pulumi:"isDefault"`
	// Name of the org
	Name *string `pulumi:"name"`
	// Optionally set a custom unique ID for the organization. If omitted, ZITADEL will generate one.
	OrgId *string `pulumi:"orgId"`
}

// The set of arguments for constructing a Org resource.
type OrgArgs struct {
	// Admin users for the organization
	Admins OrgAdminArrayInput
	// True sets the org as default org for the instance. Only one org can be default org. Nothing happens if you set it to false until you set another org as default org.
	IsDefault pulumi.BoolPtrInput
	// Name of the org
	Name pulumi.StringPtrInput
	// Optionally set a custom unique ID for the organization. If omitted, ZITADEL will generate one.
	OrgId pulumi.StringPtrInput
}

func (OrgArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*orgArgs)(nil)).Elem()
}

type OrgInput interface {
	pulumi.Input

	ToOrgOutput() OrgOutput
	ToOrgOutputWithContext(ctx context.Context) OrgOutput
}

func (*Org) ElementType() reflect.Type {
	return reflect.TypeOf((**Org)(nil)).Elem()
}

func (i *Org) ToOrgOutput() OrgOutput {
	return i.ToOrgOutputWithContext(context.Background())
}

func (i *Org) ToOrgOutputWithContext(ctx context.Context) OrgOutput {
	return pulumi.ToOutputWithContext(ctx, i).(OrgOutput)
}

type OrgOutput struct{ *pulumi.OutputState }

func (OrgOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Org)(nil)).Elem()
}

func (o OrgOutput) ToOrgOutput() OrgOutput {
	return o
}

func (o OrgOutput) ToOrgOutputWithContext(ctx context.Context) OrgOutput {
	return o
}

// Admin users for the organization
func (o OrgOutput) Admins() OrgAdminArrayOutput {
	return o.ApplyT(func(v *Org) OrgAdminArrayOutput { return v.Admins }).(OrgAdminArrayOutput)
}

// True sets the org as default org for the instance. Only one org can be default org. Nothing happens if you set it to false until you set another org as default org.
func (o OrgOutput) IsDefault() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *Org) pulumi.BoolPtrOutput { return v.IsDefault }).(pulumi.BoolPtrOutput)
}

// Name of the org
func (o OrgOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *Org) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Optionally set a custom unique ID for the organization. If omitted, ZITADEL will generate one.
func (o OrgOutput) OrgId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Org) pulumi.StringPtrOutput { return v.OrgId }).(pulumi.StringPtrOutput)
}

// Primary domain of the org
func (o OrgOutput) PrimaryDomain() pulumi.StringOutput {
	return o.ApplyT(func(v *Org) pulumi.StringOutput { return v.PrimaryDomain }).(pulumi.StringOutput)
}

// State of the org
func (o OrgOutput) State() pulumi.StringOutput {
	return o.ApplyT(func(v *Org) pulumi.StringOutput { return v.State }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*OrgInput)(nil)).Elem(), &Org{})
	pulumi.RegisterOutputType(OrgOutput{})
}
