// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package zitadel

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/truvity/pulumi-zitadel/sdk/go/zitadel/internal"
)

// Resource representing an organization in ZITADEL. Uses the org/v2 API and **requires ZITADEL 4.x**. For deployments that must support ZITADEL 3.x, use `Org` instead (it automatically falls back to the management API).
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/truvity/pulumi-zitadel/sdk/go/zitadel"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := zitadel.NewOrganization(ctx, "default", &zitadel.OrganizationArgs{
//				Name: pulumi.String("terraform-test"),
//			})
//			if err != nil {
//				return err
//			}
//			_, err = zitadel.NewOrganization(ctx, "with_admins", &zitadel.OrganizationArgs{
//				Name: pulumi.String("terraform-test-with-admins"),
//				Admins: zitadel.OrganizationAdminArray{
//					&zitadel.OrganizationAdminArgs{
//						UserId: pulumi.String("123456789012345678"),
//						Roles: pulumi.StringArray{
//							pulumi.String("ORG_OWNER"),
//						},
//					},
//				},
//			})
//			if err != nil {
//				return err
//			}
//			_, err = zitadel.NewOrganization(ctx, "with_custom_id", &zitadel.OrganizationArgs{
//				Name:  pulumi.String("terraform-test-custom"),
//				OrgId: pulumi.String("custom-org-id-123"),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Import
//
// ```sh
// $ pulumi import zitadel:index/organization:Organization imported '123456789012345678'
// ```
type Organization struct {
	pulumi.CustomResourceState

	// List of users to be granted organization admin roles
	Admins OrganizationAdminArrayOutput `pulumi:"admins"`
	// Name of the org
	Name pulumi.StringOutput `pulumi:"name"`
	// Custom unique identifier for the organization
	OrgId pulumi.StringPtrOutput `pulumi:"orgId"`
	// Primary domain of the org
	PrimaryDomain pulumi.StringOutput `pulumi:"primaryDomain"`
	// State of the org
	State pulumi.StringOutput `pulumi:"state"`
}

// NewOrganization registers a new resource with the given unique name, arguments, and options.
func NewOrganization(ctx *pulumi.Context,
	name string, args *OrganizationArgs, opts ...pulumi.ResourceOption) (*Organization, error) {
	if args == nil {
		args = &OrganizationArgs{}
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Organization
	err := ctx.RegisterResource("zitadel:index/organization:Organization", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetOrganization gets an existing Organization resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetOrganization(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *OrganizationState, opts ...pulumi.ResourceOption) (*Organization, error) {
	var resource Organization
	err := ctx.ReadResource("zitadel:index/organization:Organization", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Organization resources.
type organizationState struct {
	// List of users to be granted organization admin roles
	Admins []OrganizationAdmin `pulumi:"admins"`
	// Name of the org
	Name *string `pulumi:"name"`
	// Custom unique identifier for the organization
	OrgId *string `pulumi:"orgId"`
	// Primary domain of the org
	PrimaryDomain *string `pulumi:"primaryDomain"`
	// State of the org
	State *string `pulumi:"state"`
}

type OrganizationState struct {
	// List of users to be granted organization admin roles
	Admins OrganizationAdminArrayInput
	// Name of the org
	Name pulumi.StringPtrInput
	// Custom unique identifier for the organization
	OrgId pulumi.StringPtrInput
	// Primary domain of the org
	PrimaryDomain pulumi.StringPtrInput
	// State of the org
	State pulumi.StringPtrInput
}

func (OrganizationState) ElementType() reflect.Type {
	return reflect.TypeOf((*organizationState)(nil)).Elem()
}

type organizationArgs struct {
	// List of users to be granted organization admin roles
	Admins []OrganizationAdmin `pulumi:"admins"`
	// Name of the org
	Name *string `pulumi:"name"`
	// Custom unique identifier for the organization
	OrgId *string `pulumi:"orgId"`
}

// The set of arguments for constructing a Organization resource.
type OrganizationArgs struct {
	// List of users to be granted organization admin roles
	Admins OrganizationAdminArrayInput
	// Name of the org
	Name pulumi.StringPtrInput
	// Custom unique identifier for the organization
	OrgId pulumi.StringPtrInput
}

func (OrganizationArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*organizationArgs)(nil)).Elem()
}

type OrganizationInput interface {
	pulumi.Input

	ToOrganizationOutput() OrganizationOutput
	ToOrganizationOutputWithContext(ctx context.Context) OrganizationOutput
}

func (*Organization) ElementType() reflect.Type {
	return reflect.TypeOf((**Organization)(nil)).Elem()
}

func (i *Organization) ToOrganizationOutput() OrganizationOutput {
	return i.ToOrganizationOutputWithContext(context.Background())
}

func (i *Organization) ToOrganizationOutputWithContext(ctx context.Context) OrganizationOutput {
	return pulumi.ToOutputWithContext(ctx, i).(OrganizationOutput)
}

type OrganizationOutput struct{ *pulumi.OutputState }

func (OrganizationOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Organization)(nil)).Elem()
}

func (o OrganizationOutput) ToOrganizationOutput() OrganizationOutput {
	return o
}

func (o OrganizationOutput) ToOrganizationOutputWithContext(ctx context.Context) OrganizationOutput {
	return o
}

// List of users to be granted organization admin roles
func (o OrganizationOutput) Admins() OrganizationAdminArrayOutput {
	return o.ApplyT(func(v *Organization) OrganizationAdminArrayOutput { return v.Admins }).(OrganizationAdminArrayOutput)
}

// Name of the org
func (o OrganizationOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *Organization) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Custom unique identifier for the organization
func (o OrganizationOutput) OrgId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Organization) pulumi.StringPtrOutput { return v.OrgId }).(pulumi.StringPtrOutput)
}

// Primary domain of the org
func (o OrganizationOutput) PrimaryDomain() pulumi.StringOutput {
	return o.ApplyT(func(v *Organization) pulumi.StringOutput { return v.PrimaryDomain }).(pulumi.StringOutput)
}

// State of the org
func (o OrganizationOutput) State() pulumi.StringOutput {
	return o.ApplyT(func(v *Organization) pulumi.StringOutput { return v.State }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*OrganizationInput)(nil)).Elem(), &Organization{})
	pulumi.RegisterOutputType(OrganizationOutput{})
}
