// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package zitadel

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/truvity/pulumi-zitadel/sdk/go/zitadel/internal"
)

// Resource representing a domain of an organization in ZITADEL.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/truvity/pulumi-zitadel/sdk/go/zitadel"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_default, err := zitadel.NewOrganizationDomain(ctx, "default", &zitadel.OrganizationDomainArgs{
//				OrganizationId: pulumi.Any(defaultZitadelOrganization.Id),
//				Domain:         pulumi.String("example.com"),
//				ValidationType: pulumi.String("DOMAIN_VALIDATION_TYPE_DNS"),
//			})
//			if err != nil {
//				return err
//			}
//			ctx.Export("dnsValidationToken", _default.ValidationToken)
//			_, err = zitadel.NewOrganizationDomain(ctx, "verified", &zitadel.OrganizationDomainArgs{
//				OrganizationId: pulumi.Any(defaultZitadelOrganization.Id),
//				Domain:         pulumi.String("verified.example.com"),
//				ValidationType: pulumi.String("DOMAIN_VALIDATION_TYPE_HTTP"),
//				Verify:         pulumi.Bool(true),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Import
//
// ```sh
// $ pulumi import zitadel:index/organizationDomain:OrganizationDomain imported '123456789012345678:example.com'
// ```
type OrganizationDomain struct {
	pulumi.CustomResourceState

	// Domain name to be added to the organization
	Domain pulumi.StringOutput `pulumi:"domain"`
	// Whether this is the primary domain of the organization
	IsPrimary pulumi.BoolOutput `pulumi:"isPrimary"`
	// Whether the domain has been verified
	IsVerified pulumi.BoolOutput `pulumi:"isVerified"`
	// ID of the organization
	OrganizationId pulumi.StringOutput `pulumi:"organizationId"`
	// Validation token for domain verification
	ValidationToken pulumi.StringOutput `pulumi:"validationToken"`
	// Type of domain validation, supported values: DOMAIN*VALIDATION*TYPE*UNSPECIFIED, DOMAIN*VALIDATION*TYPE*HTTP, DOMAIN*VALIDATION*TYPE_DNS
	ValidationType pulumi.StringOutput `pulumi:"validationType"`
	// URL where validation file should be hosted for HTTP verification
	ValidationUrl pulumi.StringOutput `pulumi:"validationUrl"`
	// Trigger domain verification. Set to true after adding DNS/HTTP validation.
	Verify pulumi.BoolPtrOutput `pulumi:"verify"`
}

// NewOrganizationDomain registers a new resource with the given unique name, arguments, and options.
func NewOrganizationDomain(ctx *pulumi.Context,
	name string, args *OrganizationDomainArgs, opts ...pulumi.ResourceOption) (*OrganizationDomain, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Domain == nil {
		return nil, errors.New("invalid value for required argument 'Domain'")
	}
	if args.OrganizationId == nil {
		return nil, errors.New("invalid value for required argument 'OrganizationId'")
	}
	if args.ValidationType == nil {
		return nil, errors.New("invalid value for required argument 'ValidationType'")
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"validationToken",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource OrganizationDomain
	err := ctx.RegisterResource("zitadel:index/organizationDomain:OrganizationDomain", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetOrganizationDomain gets an existing OrganizationDomain resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetOrganizationDomain(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *OrganizationDomainState, opts ...pulumi.ResourceOption) (*OrganizationDomain, error) {
	var resource OrganizationDomain
	err := ctx.ReadResource("zitadel:index/organizationDomain:OrganizationDomain", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering OrganizationDomain resources.
type organizationDomainState struct {
	// Domain name to be added to the organization
	Domain *string `pulumi:"domain"`
	// Whether this is the primary domain of the organization
	IsPrimary *bool `pulumi:"isPrimary"`
	// Whether the domain has been verified
	IsVerified *bool `pulumi:"isVerified"`
	// ID of the organization
	OrganizationId *string `pulumi:"organizationId"`
	// Validation token for domain verification
	ValidationToken *string `pulumi:"validationToken"`
	// Type of domain validation, supported values: DOMAIN*VALIDATION*TYPE*UNSPECIFIED, DOMAIN*VALIDATION*TYPE*HTTP, DOMAIN*VALIDATION*TYPE_DNS
	ValidationType *string `pulumi:"validationType"`
	// URL where validation file should be hosted for HTTP verification
	ValidationUrl *string `pulumi:"validationUrl"`
	// Trigger domain verification. Set to true after adding DNS/HTTP validation.
	Verify *bool `pulumi:"verify"`
}

type OrganizationDomainState struct {
	// Domain name to be added to the organization
	Domain pulumi.StringPtrInput
	// Whether this is the primary domain of the organization
	IsPrimary pulumi.BoolPtrInput
	// Whether the domain has been verified
	IsVerified pulumi.BoolPtrInput
	// ID of the organization
	OrganizationId pulumi.StringPtrInput
	// Validation token for domain verification
	ValidationToken pulumi.StringPtrInput
	// Type of domain validation, supported values: DOMAIN*VALIDATION*TYPE*UNSPECIFIED, DOMAIN*VALIDATION*TYPE*HTTP, DOMAIN*VALIDATION*TYPE_DNS
	ValidationType pulumi.StringPtrInput
	// URL where validation file should be hosted for HTTP verification
	ValidationUrl pulumi.StringPtrInput
	// Trigger domain verification. Set to true after adding DNS/HTTP validation.
	Verify pulumi.BoolPtrInput
}

func (OrganizationDomainState) ElementType() reflect.Type {
	return reflect.TypeOf((*organizationDomainState)(nil)).Elem()
}

type organizationDomainArgs struct {
	// Domain name to be added to the organization
	Domain string `pulumi:"domain"`
	// ID of the organization
	OrganizationId string `pulumi:"organizationId"`
	// Type of domain validation, supported values: DOMAIN*VALIDATION*TYPE*UNSPECIFIED, DOMAIN*VALIDATION*TYPE*HTTP, DOMAIN*VALIDATION*TYPE_DNS
	ValidationType string `pulumi:"validationType"`
	// Trigger domain verification. Set to true after adding DNS/HTTP validation.
	Verify *bool `pulumi:"verify"`
}

// The set of arguments for constructing a OrganizationDomain resource.
type OrganizationDomainArgs struct {
	// Domain name to be added to the organization
	Domain pulumi.StringInput
	// ID of the organization
	OrganizationId pulumi.StringInput
	// Type of domain validation, supported values: DOMAIN*VALIDATION*TYPE*UNSPECIFIED, DOMAIN*VALIDATION*TYPE*HTTP, DOMAIN*VALIDATION*TYPE_DNS
	ValidationType pulumi.StringInput
	// Trigger domain verification. Set to true after adding DNS/HTTP validation.
	Verify pulumi.BoolPtrInput
}

func (OrganizationDomainArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*organizationDomainArgs)(nil)).Elem()
}

type OrganizationDomainInput interface {
	pulumi.Input

	ToOrganizationDomainOutput() OrganizationDomainOutput
	ToOrganizationDomainOutputWithContext(ctx context.Context) OrganizationDomainOutput
}

func (*OrganizationDomain) ElementType() reflect.Type {
	return reflect.TypeOf((**OrganizationDomain)(nil)).Elem()
}

func (i *OrganizationDomain) ToOrganizationDomainOutput() OrganizationDomainOutput {
	return i.ToOrganizationDomainOutputWithContext(context.Background())
}

func (i *OrganizationDomain) ToOrganizationDomainOutputWithContext(ctx context.Context) OrganizationDomainOutput {
	return pulumi.ToOutputWithContext(ctx, i).(OrganizationDomainOutput)
}

type OrganizationDomainOutput struct{ *pulumi.OutputState }

func (OrganizationDomainOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**OrganizationDomain)(nil)).Elem()
}

func (o OrganizationDomainOutput) ToOrganizationDomainOutput() OrganizationDomainOutput {
	return o
}

func (o OrganizationDomainOutput) ToOrganizationDomainOutputWithContext(ctx context.Context) OrganizationDomainOutput {
	return o
}

// Domain name to be added to the organization
func (o OrganizationDomainOutput) Domain() pulumi.StringOutput {
	return o.ApplyT(func(v *OrganizationDomain) pulumi.StringOutput { return v.Domain }).(pulumi.StringOutput)
}

// Whether this is the primary domain of the organization
func (o OrganizationDomainOutput) IsPrimary() pulumi.BoolOutput {
	return o.ApplyT(func(v *OrganizationDomain) pulumi.BoolOutput { return v.IsPrimary }).(pulumi.BoolOutput)
}

// Whether the domain has been verified
func (o OrganizationDomainOutput) IsVerified() pulumi.BoolOutput {
	return o.ApplyT(func(v *OrganizationDomain) pulumi.BoolOutput { return v.IsVerified }).(pulumi.BoolOutput)
}

// ID of the organization
func (o OrganizationDomainOutput) OrganizationId() pulumi.StringOutput {
	return o.ApplyT(func(v *OrganizationDomain) pulumi.StringOutput { return v.OrganizationId }).(pulumi.StringOutput)
}

// Validation token for domain verification
func (o OrganizationDomainOutput) ValidationToken() pulumi.StringOutput {
	return o.ApplyT(func(v *OrganizationDomain) pulumi.StringOutput { return v.ValidationToken }).(pulumi.StringOutput)
}

// Type of domain validation, supported values: DOMAIN*VALIDATION*TYPE*UNSPECIFIED, DOMAIN*VALIDATION*TYPE*HTTP, DOMAIN*VALIDATION*TYPE_DNS
func (o OrganizationDomainOutput) ValidationType() pulumi.StringOutput {
	return o.ApplyT(func(v *OrganizationDomain) pulumi.StringOutput { return v.ValidationType }).(pulumi.StringOutput)
}

// URL where validation file should be hosted for HTTP verification
func (o OrganizationDomainOutput) ValidationUrl() pulumi.StringOutput {
	return o.ApplyT(func(v *OrganizationDomain) pulumi.StringOutput { return v.ValidationUrl }).(pulumi.StringOutput)
}

// Trigger domain verification. Set to true after adding DNS/HTTP validation.
func (o OrganizationDomainOutput) Verify() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *OrganizationDomain) pulumi.BoolPtrOutput { return v.Verify }).(pulumi.BoolPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*OrganizationDomainInput)(nil)).Elem(), &OrganizationDomain{})
	pulumi.RegisterOutputType(OrganizationDomainOutput{})
}
