// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package zitadel

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/truvity/pulumi-zitadel/sdk/go/zitadel/internal"
)

// Custom key-value metadata on an organization. **Deprecated:** use `OrganizationMetadata` which uses the metadata/v2 API (requires ZITADEL 4.x).
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/truvity/pulumi-zitadel/sdk/go/zitadel"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := zitadel.NewOrgMetadata(ctx, "default", &zitadel.OrgMetadataArgs{
//				OrgId: pulumi.Any(defaultZitadelOrg.Id),
//				Key:   pulumi.String("a_key"),
//				Value: pulumi.String("a_value"),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Import
//
// The resource can be imported using the ID format `<key[:org_id]>`, e.g.
//
// ```sh
// $ pulumi import zitadel:index/orgMetadata:OrgMetadata imported 'a_key:123456789012345678'
// ```
type OrgMetadata struct {
	pulumi.CustomResourceState

	// The key of a metadata entry
	Key pulumi.StringOutput `pulumi:"key"`
	// ID of the organization. If not provided, the organization of the authenticated user/service account is used.
	OrgId pulumi.StringPtrOutput `pulumi:"orgId"`
	// The string representation of a metadata entry value. For binary data, use the base64encode function.
	Value pulumi.StringOutput `pulumi:"value"`
}

// NewOrgMetadata registers a new resource with the given unique name, arguments, and options.
func NewOrgMetadata(ctx *pulumi.Context,
	name string, args *OrgMetadataArgs, opts ...pulumi.ResourceOption) (*OrgMetadata, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Key == nil {
		return nil, errors.New("invalid value for required argument 'Key'")
	}
	if args.Value == nil {
		return nil, errors.New("invalid value for required argument 'Value'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource OrgMetadata
	err := ctx.RegisterResource("zitadel:index/orgMetadata:OrgMetadata", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetOrgMetadata gets an existing OrgMetadata resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetOrgMetadata(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *OrgMetadataState, opts ...pulumi.ResourceOption) (*OrgMetadata, error) {
	var resource OrgMetadata
	err := ctx.ReadResource("zitadel:index/orgMetadata:OrgMetadata", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering OrgMetadata resources.
type orgMetadataState struct {
	// The key of a metadata entry
	Key *string `pulumi:"key"`
	// ID of the organization. If not provided, the organization of the authenticated user/service account is used.
	OrgId *string `pulumi:"orgId"`
	// The string representation of a metadata entry value. For binary data, use the base64encode function.
	Value *string `pulumi:"value"`
}

type OrgMetadataState struct {
	// The key of a metadata entry
	Key pulumi.StringPtrInput
	// ID of the organization. If not provided, the organization of the authenticated user/service account is used.
	OrgId pulumi.StringPtrInput
	// The string representation of a metadata entry value. For binary data, use the base64encode function.
	Value pulumi.StringPtrInput
}

func (OrgMetadataState) ElementType() reflect.Type {
	return reflect.TypeOf((*orgMetadataState)(nil)).Elem()
}

type orgMetadataArgs struct {
	// The key of a metadata entry
	Key string `pulumi:"key"`
	// ID of the organization. If not provided, the organization of the authenticated user/service account is used.
	OrgId *string `pulumi:"orgId"`
	// The string representation of a metadata entry value. For binary data, use the base64encode function.
	Value string `pulumi:"value"`
}

// The set of arguments for constructing a OrgMetadata resource.
type OrgMetadataArgs struct {
	// The key of a metadata entry
	Key pulumi.StringInput
	// ID of the organization. If not provided, the organization of the authenticated user/service account is used.
	OrgId pulumi.StringPtrInput
	// The string representation of a metadata entry value. For binary data, use the base64encode function.
	Value pulumi.StringInput
}

func (OrgMetadataArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*orgMetadataArgs)(nil)).Elem()
}

type OrgMetadataInput interface {
	pulumi.Input

	ToOrgMetadataOutput() OrgMetadataOutput
	ToOrgMetadataOutputWithContext(ctx context.Context) OrgMetadataOutput
}

func (*OrgMetadata) ElementType() reflect.Type {
	return reflect.TypeOf((**OrgMetadata)(nil)).Elem()
}

func (i *OrgMetadata) ToOrgMetadataOutput() OrgMetadataOutput {
	return i.ToOrgMetadataOutputWithContext(context.Background())
}

func (i *OrgMetadata) ToOrgMetadataOutputWithContext(ctx context.Context) OrgMetadataOutput {
	return pulumi.ToOutputWithContext(ctx, i).(OrgMetadataOutput)
}

type OrgMetadataOutput struct{ *pulumi.OutputState }

func (OrgMetadataOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**OrgMetadata)(nil)).Elem()
}

func (o OrgMetadataOutput) ToOrgMetadataOutput() OrgMetadataOutput {
	return o
}

func (o OrgMetadataOutput) ToOrgMetadataOutputWithContext(ctx context.Context) OrgMetadataOutput {
	return o
}

// The key of a metadata entry
func (o OrgMetadataOutput) Key() pulumi.StringOutput {
	return o.ApplyT(func(v *OrgMetadata) pulumi.StringOutput { return v.Key }).(pulumi.StringOutput)
}

// ID of the organization. If not provided, the organization of the authenticated user/service account is used.
func (o OrgMetadataOutput) OrgId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *OrgMetadata) pulumi.StringPtrOutput { return v.OrgId }).(pulumi.StringPtrOutput)
}

// The string representation of a metadata entry value. For binary data, use the base64encode function.
func (o OrgMetadataOutput) Value() pulumi.StringOutput {
	return o.ApplyT(func(v *OrgMetadata) pulumi.StringOutput { return v.Value }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*OrgMetadataInput)(nil)).Elem(), &OrgMetadata{})
	pulumi.RegisterOutputType(OrgMetadataOutput{})
}
