// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package zitadel

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/truvity/pulumi-zitadel/sdk/go/zitadel/internal"
)

// Resource representing the grant of a project to a different organization, also containing the available roles which can be given to the members of the projectgrant.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/truvity/pulumi-zitadel/sdk/go/zitadel"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := zitadel.NewProjectGrant(ctx, "default", &zitadel.ProjectGrantArgs{
//				OrgId:        pulumi.Any(defaultZitadelOrg.Id),
//				ProjectId:    pulumi.Any(defaultZitadelProject.Id),
//				GrantedOrgId: pulumi.Any(grantedOrg.Id),
//				RoleKeys: pulumi.StringArray{
//					pulumi.String("super-user"),
//				},
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Import
//
// The resource can be imported using the ID format `<id:project_id[:org_id]>`, e.g.
//
// ```sh
// $ pulumi import zitadel:index/projectGrant:ProjectGrant imported '123456789012345678:123456789012345678:123456789012345678'
// ```
type ProjectGrant struct {
	pulumi.CustomResourceState

	// ID of the organization granted the project
	GrantedOrgId pulumi.StringOutput `pulumi:"grantedOrgId"`
	// ID of the organization. If not provided, the organization of the authenticated user/service account is used.
	OrgId pulumi.StringPtrOutput `pulumi:"orgId"`
	// ID of the project
	ProjectId pulumi.StringOutput `pulumi:"projectId"`
	// List of roles granted
	RoleKeys pulumi.StringArrayOutput `pulumi:"roleKeys"`
}

// NewProjectGrant registers a new resource with the given unique name, arguments, and options.
func NewProjectGrant(ctx *pulumi.Context,
	name string, args *ProjectGrantArgs, opts ...pulumi.ResourceOption) (*ProjectGrant, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.GrantedOrgId == nil {
		return nil, errors.New("invalid value for required argument 'GrantedOrgId'")
	}
	if args.ProjectId == nil {
		return nil, errors.New("invalid value for required argument 'ProjectId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource ProjectGrant
	err := ctx.RegisterResource("zitadel:index/projectGrant:ProjectGrant", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetProjectGrant gets an existing ProjectGrant resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetProjectGrant(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ProjectGrantState, opts ...pulumi.ResourceOption) (*ProjectGrant, error) {
	var resource ProjectGrant
	err := ctx.ReadResource("zitadel:index/projectGrant:ProjectGrant", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ProjectGrant resources.
type projectGrantState struct {
	// ID of the organization granted the project
	GrantedOrgId *string `pulumi:"grantedOrgId"`
	// ID of the organization. If not provided, the organization of the authenticated user/service account is used.
	OrgId *string `pulumi:"orgId"`
	// ID of the project
	ProjectId *string `pulumi:"projectId"`
	// List of roles granted
	RoleKeys []string `pulumi:"roleKeys"`
}

type ProjectGrantState struct {
	// ID of the organization granted the project
	GrantedOrgId pulumi.StringPtrInput
	// ID of the organization. If not provided, the organization of the authenticated user/service account is used.
	OrgId pulumi.StringPtrInput
	// ID of the project
	ProjectId pulumi.StringPtrInput
	// List of roles granted
	RoleKeys pulumi.StringArrayInput
}

func (ProjectGrantState) ElementType() reflect.Type {
	return reflect.TypeOf((*projectGrantState)(nil)).Elem()
}

type projectGrantArgs struct {
	// ID of the organization granted the project
	GrantedOrgId string `pulumi:"grantedOrgId"`
	// ID of the organization. If not provided, the organization of the authenticated user/service account is used.
	OrgId *string `pulumi:"orgId"`
	// ID of the project
	ProjectId string `pulumi:"projectId"`
	// List of roles granted
	RoleKeys []string `pulumi:"roleKeys"`
}

// The set of arguments for constructing a ProjectGrant resource.
type ProjectGrantArgs struct {
	// ID of the organization granted the project
	GrantedOrgId pulumi.StringInput
	// ID of the organization. If not provided, the organization of the authenticated user/service account is used.
	OrgId pulumi.StringPtrInput
	// ID of the project
	ProjectId pulumi.StringInput
	// List of roles granted
	RoleKeys pulumi.StringArrayInput
}

func (ProjectGrantArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*projectGrantArgs)(nil)).Elem()
}

type ProjectGrantInput interface {
	pulumi.Input

	ToProjectGrantOutput() ProjectGrantOutput
	ToProjectGrantOutputWithContext(ctx context.Context) ProjectGrantOutput
}

func (*ProjectGrant) ElementType() reflect.Type {
	return reflect.TypeOf((**ProjectGrant)(nil)).Elem()
}

func (i *ProjectGrant) ToProjectGrantOutput() ProjectGrantOutput {
	return i.ToProjectGrantOutputWithContext(context.Background())
}

func (i *ProjectGrant) ToProjectGrantOutputWithContext(ctx context.Context) ProjectGrantOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProjectGrantOutput)
}

type ProjectGrantOutput struct{ *pulumi.OutputState }

func (ProjectGrantOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ProjectGrant)(nil)).Elem()
}

func (o ProjectGrantOutput) ToProjectGrantOutput() ProjectGrantOutput {
	return o
}

func (o ProjectGrantOutput) ToProjectGrantOutputWithContext(ctx context.Context) ProjectGrantOutput {
	return o
}

// ID of the organization granted the project
func (o ProjectGrantOutput) GrantedOrgId() pulumi.StringOutput {
	return o.ApplyT(func(v *ProjectGrant) pulumi.StringOutput { return v.GrantedOrgId }).(pulumi.StringOutput)
}

// ID of the organization. If not provided, the organization of the authenticated user/service account is used.
func (o ProjectGrantOutput) OrgId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ProjectGrant) pulumi.StringPtrOutput { return v.OrgId }).(pulumi.StringPtrOutput)
}

// ID of the project
func (o ProjectGrantOutput) ProjectId() pulumi.StringOutput {
	return o.ApplyT(func(v *ProjectGrant) pulumi.StringOutput { return v.ProjectId }).(pulumi.StringOutput)
}

// List of roles granted
func (o ProjectGrantOutput) RoleKeys() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *ProjectGrant) pulumi.StringArrayOutput { return v.RoleKeys }).(pulumi.StringArrayOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ProjectGrantInput)(nil)).Elem(), &ProjectGrant{})
	pulumi.RegisterOutputType(ProjectGrantOutput{})
}
