// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package zitadel

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/truvity/pulumi-zitadel/sdk/go/zitadel/internal"
)

// Resource representing the SMS provider Twilio configuration of an instance.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/truvity/pulumi-zitadel/sdk/go/zitadel"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := zitadel.NewSmsProviderTwilio(ctx, "default", &zitadel.SmsProviderTwilioArgs{
//				Sid:              pulumi.String("sid"),
//				SenderNumber:     pulumi.String("019920892"),
//				Token:            pulumi.String("twilio_token"),
//				SetActive:        pulumi.Bool(false),
//				VerifyServiceSid: pulumi.String(""),
//				Description:      pulumi.String("My Twilio SMS Provider"),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Import
//
// The resource can be imported using the ID format `<id[:token]>`, e.g.
//
// ```sh
// $ pulumi import zitadel:index/smsProviderTwilio:SmsProviderTwilio imported '123456789012345678:12345678901234567890123456abcdef'
// ```
type SmsProviderTwilio struct {
	pulumi.CustomResourceState

	// Description of the SMS provider.
	Description pulumi.StringPtrOutput `pulumi:"description"`
	// Sender number which is used to send the SMS.
	SenderNumber pulumi.StringOutput `pulumi:"senderNumber"`
	// Set the SMS provider as active after creating/updating.
	SetActive pulumi.BoolPtrOutput `pulumi:"setActive"`
	// SID used to communicate with Twilio.
	Sid pulumi.StringOutput `pulumi:"sid"`
	// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
	// Token used to communicate with Twilio. This value is write-only and is never stored in Terraform state; it cannot be read back.
	Token pulumi.StringOutput `pulumi:"token"`
	// A non-reversible hash of the write-only token, used to detect when it changes. It does not contain the secret itself.
	TokenHash pulumi.StringOutput `pulumi:"tokenHash"`
	// Twilio Verify Service SID used for phone verification.
	VerifyServiceSid pulumi.StringPtrOutput `pulumi:"verifyServiceSid"`
}

// NewSmsProviderTwilio registers a new resource with the given unique name, arguments, and options.
func NewSmsProviderTwilio(ctx *pulumi.Context,
	name string, args *SmsProviderTwilioArgs, opts ...pulumi.ResourceOption) (*SmsProviderTwilio, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.SenderNumber == nil {
		return nil, errors.New("invalid value for required argument 'SenderNumber'")
	}
	if args.Sid == nil {
		return nil, errors.New("invalid value for required argument 'Sid'")
	}
	if args.Token == nil {
		return nil, errors.New("invalid value for required argument 'Token'")
	}
	if args.Token != nil {
		args.Token = pulumi.ToSecret(args.Token).(pulumi.StringInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"token",
		"tokenHash",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource SmsProviderTwilio
	err := ctx.RegisterResource("zitadel:index/smsProviderTwilio:SmsProviderTwilio", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetSmsProviderTwilio gets an existing SmsProviderTwilio resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetSmsProviderTwilio(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *SmsProviderTwilioState, opts ...pulumi.ResourceOption) (*SmsProviderTwilio, error) {
	var resource SmsProviderTwilio
	err := ctx.ReadResource("zitadel:index/smsProviderTwilio:SmsProviderTwilio", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering SmsProviderTwilio resources.
type smsProviderTwilioState struct {
	// Description of the SMS provider.
	Description *string `pulumi:"description"`
	// Sender number which is used to send the SMS.
	SenderNumber *string `pulumi:"senderNumber"`
	// Set the SMS provider as active after creating/updating.
	SetActive *bool `pulumi:"setActive"`
	// SID used to communicate with Twilio.
	Sid *string `pulumi:"sid"`
	// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
	// Token used to communicate with Twilio. This value is write-only and is never stored in Terraform state; it cannot be read back.
	Token *string `pulumi:"token"`
	// A non-reversible hash of the write-only token, used to detect when it changes. It does not contain the secret itself.
	TokenHash *string `pulumi:"tokenHash"`
	// Twilio Verify Service SID used for phone verification.
	VerifyServiceSid *string `pulumi:"verifyServiceSid"`
}

type SmsProviderTwilioState struct {
	// Description of the SMS provider.
	Description pulumi.StringPtrInput
	// Sender number which is used to send the SMS.
	SenderNumber pulumi.StringPtrInput
	// Set the SMS provider as active after creating/updating.
	SetActive pulumi.BoolPtrInput
	// SID used to communicate with Twilio.
	Sid pulumi.StringPtrInput
	// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
	// Token used to communicate with Twilio. This value is write-only and is never stored in Terraform state; it cannot be read back.
	Token pulumi.StringPtrInput
	// A non-reversible hash of the write-only token, used to detect when it changes. It does not contain the secret itself.
	TokenHash pulumi.StringPtrInput
	// Twilio Verify Service SID used for phone verification.
	VerifyServiceSid pulumi.StringPtrInput
}

func (SmsProviderTwilioState) ElementType() reflect.Type {
	return reflect.TypeOf((*smsProviderTwilioState)(nil)).Elem()
}

type smsProviderTwilioArgs struct {
	// Description of the SMS provider.
	Description *string `pulumi:"description"`
	// Sender number which is used to send the SMS.
	SenderNumber string `pulumi:"senderNumber"`
	// Set the SMS provider as active after creating/updating.
	SetActive *bool `pulumi:"setActive"`
	// SID used to communicate with Twilio.
	Sid string `pulumi:"sid"`
	// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
	// Token used to communicate with Twilio. This value is write-only and is never stored in Terraform state; it cannot be read back.
	Token string `pulumi:"token"`
	// Twilio Verify Service SID used for phone verification.
	VerifyServiceSid *string `pulumi:"verifyServiceSid"`
}

// The set of arguments for constructing a SmsProviderTwilio resource.
type SmsProviderTwilioArgs struct {
	// Description of the SMS provider.
	Description pulumi.StringPtrInput
	// Sender number which is used to send the SMS.
	SenderNumber pulumi.StringInput
	// Set the SMS provider as active after creating/updating.
	SetActive pulumi.BoolPtrInput
	// SID used to communicate with Twilio.
	Sid pulumi.StringInput
	// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
	// Token used to communicate with Twilio. This value is write-only and is never stored in Terraform state; it cannot be read back.
	Token pulumi.StringInput
	// Twilio Verify Service SID used for phone verification.
	VerifyServiceSid pulumi.StringPtrInput
}

func (SmsProviderTwilioArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*smsProviderTwilioArgs)(nil)).Elem()
}

type SmsProviderTwilioInput interface {
	pulumi.Input

	ToSmsProviderTwilioOutput() SmsProviderTwilioOutput
	ToSmsProviderTwilioOutputWithContext(ctx context.Context) SmsProviderTwilioOutput
}

func (*SmsProviderTwilio) ElementType() reflect.Type {
	return reflect.TypeOf((**SmsProviderTwilio)(nil)).Elem()
}

func (i *SmsProviderTwilio) ToSmsProviderTwilioOutput() SmsProviderTwilioOutput {
	return i.ToSmsProviderTwilioOutputWithContext(context.Background())
}

func (i *SmsProviderTwilio) ToSmsProviderTwilioOutputWithContext(ctx context.Context) SmsProviderTwilioOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SmsProviderTwilioOutput)
}

type SmsProviderTwilioOutput struct{ *pulumi.OutputState }

func (SmsProviderTwilioOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**SmsProviderTwilio)(nil)).Elem()
}

func (o SmsProviderTwilioOutput) ToSmsProviderTwilioOutput() SmsProviderTwilioOutput {
	return o
}

func (o SmsProviderTwilioOutput) ToSmsProviderTwilioOutputWithContext(ctx context.Context) SmsProviderTwilioOutput {
	return o
}

// Description of the SMS provider.
func (o SmsProviderTwilioOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *SmsProviderTwilio) pulumi.StringPtrOutput { return v.Description }).(pulumi.StringPtrOutput)
}

// Sender number which is used to send the SMS.
func (o SmsProviderTwilioOutput) SenderNumber() pulumi.StringOutput {
	return o.ApplyT(func(v *SmsProviderTwilio) pulumi.StringOutput { return v.SenderNumber }).(pulumi.StringOutput)
}

// Set the SMS provider as active after creating/updating.
func (o SmsProviderTwilioOutput) SetActive() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *SmsProviderTwilio) pulumi.BoolPtrOutput { return v.SetActive }).(pulumi.BoolPtrOutput)
}

// SID used to communicate with Twilio.
func (o SmsProviderTwilioOutput) Sid() pulumi.StringOutput {
	return o.ApplyT(func(v *SmsProviderTwilio) pulumi.StringOutput { return v.Sid }).(pulumi.StringOutput)
}

// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
// Token used to communicate with Twilio. This value is write-only and is never stored in Terraform state; it cannot be read back.
func (o SmsProviderTwilioOutput) Token() pulumi.StringOutput {
	return o.ApplyT(func(v *SmsProviderTwilio) pulumi.StringOutput { return v.Token }).(pulumi.StringOutput)
}

// A non-reversible hash of the write-only token, used to detect when it changes. It does not contain the secret itself.
func (o SmsProviderTwilioOutput) TokenHash() pulumi.StringOutput {
	return o.ApplyT(func(v *SmsProviderTwilio) pulumi.StringOutput { return v.TokenHash }).(pulumi.StringOutput)
}

// Twilio Verify Service SID used for phone verification.
func (o SmsProviderTwilioOutput) VerifyServiceSid() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *SmsProviderTwilio) pulumi.StringPtrOutput { return v.VerifyServiceSid }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*SmsProviderTwilioInput)(nil)).Elem(), &SmsProviderTwilio{})
	pulumi.RegisterOutputType(SmsProviderTwilioOutput{})
}
