// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package zitadel

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/truvity/pulumi-zitadel/sdk/go/zitadel/internal"
)

// Resource representing the feature flags configuration for the system.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/truvity/pulumi-zitadel/sdk/go/zitadel"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := zitadel.NewSystemFeatures(ctx, "default", &zitadel.SystemFeaturesArgs{
//				LoginDefaultOrg:   pulumi.Bool(true),
//				OidcTokenExchange: pulumi.Bool(true),
//				UserSchema:        pulumi.Bool(false),
//				ImprovedPerformances: pulumi.StringArray{
//					pulumi.String("IMPROVED_PERFORMANCE_PROJECT_GRANT"),
//					pulumi.String("IMPROVED_PERFORMANCE_ORG_DOMAIN_VERIFIED"),
//				},
//				OidcSingleV1SessionTermination: pulumi.Bool(true),
//				EnableBackChannelLogout:        pulumi.Bool(true),
//				LoginV2: map[string]interface{}{
//					"required": true,
//					"baseUri":  "https://login.example.com",
//				}[0],
//				PermissionCheckV2: pulumi.Bool(true),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Import
//
// The resource can be imported using the constant ID "system"
//
// ```sh
// $ pulumi import zitadel:index/systemFeatures:SystemFeatures imported 'system'
// ```
type SystemFeatures struct {
	pulumi.CustomResourceState

	// If the flag is enabled, you'll be able to use the OIDC Back-Channel Logout to be notified in your application about terminated user sessions.
	EnableBackChannelLogout pulumi.BoolOutput `pulumi:"enableBackChannelLogout"`
	// Improves performance of specified execution paths. Possible values: IMPROVED*PERFORMANCE*PROJECT*GRANT, IMPROVED*PERFORMANCE*PROJECT, IMPROVED*PERFORMANCE*USER*GRANT, IMPROVED*PERFORMANCE*ORG*DOMAIN*VERIFIED
	ImprovedPerformances pulumi.StringArrayOutput `pulumi:"improvedPerformances"`
	// The login UI will use the settings of the default org (and not from the instance) if no organization context is set
	LoginDefaultOrg pulumi.BoolOutput `pulumi:"loginDefaultOrg"`
	// Specify the login UI for all users and applications regardless of their preference.
	LoginV2 SystemFeaturesLoginV2Output `pulumi:"loginV2"`
	// If the flag is enabled, you'll be able to terminate a single session from the login UI by providing an id*token with a `sid` claim as id*token*hint on the end*session endpoint. Note that currently all sessions from the same user agent (browser) are terminated in the login UI. Sessions managed through the Session API already allow the termination of single sessions.
	OidcSingleV1SessionTermination pulumi.BoolOutput `pulumi:"oidcSingleV1SessionTermination"`
	// Enable the experimental `urn:ietf:params:oauth:grant-type:token-exchange` grant type for the OIDC token endpoint. Token exchange can be used to request tokens with a lesser scope or impersonate other users. See the security policy to allow impersonation on an instance.
	OidcTokenExchange pulumi.BoolOutput `pulumi:"oidcTokenExchange"`
	// Enable a newer, more performant, permission check used for v2 and v3 resource based APIs.
	PermissionCheckV2 pulumi.BoolOutput `pulumi:"permissionCheckV2"`
	// User Schemas allow to manage data schemas of user. If the flag is enabled, you'll be able to use the new API and its features. Note that it is still in an early stage.
	UserSchema pulumi.BoolOutput `pulumi:"userSchema"`
}

// NewSystemFeatures registers a new resource with the given unique name, arguments, and options.
func NewSystemFeatures(ctx *pulumi.Context,
	name string, args *SystemFeaturesArgs, opts ...pulumi.ResourceOption) (*SystemFeatures, error) {
	if args == nil {
		args = &SystemFeaturesArgs{}
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	var resource SystemFeatures
	err := ctx.RegisterResource("zitadel:index/systemFeatures:SystemFeatures", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetSystemFeatures gets an existing SystemFeatures resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetSystemFeatures(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *SystemFeaturesState, opts ...pulumi.ResourceOption) (*SystemFeatures, error) {
	var resource SystemFeatures
	err := ctx.ReadResource("zitadel:index/systemFeatures:SystemFeatures", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering SystemFeatures resources.
type systemFeaturesState struct {
	// If the flag is enabled, you'll be able to use the OIDC Back-Channel Logout to be notified in your application about terminated user sessions.
	EnableBackChannelLogout *bool `pulumi:"enableBackChannelLogout"`
	// Improves performance of specified execution paths. Possible values: IMPROVED*PERFORMANCE*PROJECT*GRANT, IMPROVED*PERFORMANCE*PROJECT, IMPROVED*PERFORMANCE*USER*GRANT, IMPROVED*PERFORMANCE*ORG*DOMAIN*VERIFIED
	ImprovedPerformances []string `pulumi:"improvedPerformances"`
	// The login UI will use the settings of the default org (and not from the instance) if no organization context is set
	LoginDefaultOrg *bool `pulumi:"loginDefaultOrg"`
	// Specify the login UI for all users and applications regardless of their preference.
	LoginV2 *SystemFeaturesLoginV2 `pulumi:"loginV2"`
	// If the flag is enabled, you'll be able to terminate a single session from the login UI by providing an id*token with a `sid` claim as id*token*hint on the end*session endpoint. Note that currently all sessions from the same user agent (browser) are terminated in the login UI. Sessions managed through the Session API already allow the termination of single sessions.
	OidcSingleV1SessionTermination *bool `pulumi:"oidcSingleV1SessionTermination"`
	// Enable the experimental `urn:ietf:params:oauth:grant-type:token-exchange` grant type for the OIDC token endpoint. Token exchange can be used to request tokens with a lesser scope or impersonate other users. See the security policy to allow impersonation on an instance.
	OidcTokenExchange *bool `pulumi:"oidcTokenExchange"`
	// Enable a newer, more performant, permission check used for v2 and v3 resource based APIs.
	PermissionCheckV2 *bool `pulumi:"permissionCheckV2"`
	// User Schemas allow to manage data schemas of user. If the flag is enabled, you'll be able to use the new API and its features. Note that it is still in an early stage.
	UserSchema *bool `pulumi:"userSchema"`
}

type SystemFeaturesState struct {
	// If the flag is enabled, you'll be able to use the OIDC Back-Channel Logout to be notified in your application about terminated user sessions.
	EnableBackChannelLogout pulumi.BoolPtrInput
	// Improves performance of specified execution paths. Possible values: IMPROVED*PERFORMANCE*PROJECT*GRANT, IMPROVED*PERFORMANCE*PROJECT, IMPROVED*PERFORMANCE*USER*GRANT, IMPROVED*PERFORMANCE*ORG*DOMAIN*VERIFIED
	ImprovedPerformances pulumi.StringArrayInput
	// The login UI will use the settings of the default org (and not from the instance) if no organization context is set
	LoginDefaultOrg pulumi.BoolPtrInput
	// Specify the login UI for all users and applications regardless of their preference.
	LoginV2 SystemFeaturesLoginV2PtrInput
	// If the flag is enabled, you'll be able to terminate a single session from the login UI by providing an id*token with a `sid` claim as id*token*hint on the end*session endpoint. Note that currently all sessions from the same user agent (browser) are terminated in the login UI. Sessions managed through the Session API already allow the termination of single sessions.
	OidcSingleV1SessionTermination pulumi.BoolPtrInput
	// Enable the experimental `urn:ietf:params:oauth:grant-type:token-exchange` grant type for the OIDC token endpoint. Token exchange can be used to request tokens with a lesser scope or impersonate other users. See the security policy to allow impersonation on an instance.
	OidcTokenExchange pulumi.BoolPtrInput
	// Enable a newer, more performant, permission check used for v2 and v3 resource based APIs.
	PermissionCheckV2 pulumi.BoolPtrInput
	// User Schemas allow to manage data schemas of user. If the flag is enabled, you'll be able to use the new API and its features. Note that it is still in an early stage.
	UserSchema pulumi.BoolPtrInput
}

func (SystemFeaturesState) ElementType() reflect.Type {
	return reflect.TypeOf((*systemFeaturesState)(nil)).Elem()
}

type systemFeaturesArgs struct {
	// If the flag is enabled, you'll be able to use the OIDC Back-Channel Logout to be notified in your application about terminated user sessions.
	EnableBackChannelLogout *bool `pulumi:"enableBackChannelLogout"`
	// Improves performance of specified execution paths. Possible values: IMPROVED*PERFORMANCE*PROJECT*GRANT, IMPROVED*PERFORMANCE*PROJECT, IMPROVED*PERFORMANCE*USER*GRANT, IMPROVED*PERFORMANCE*ORG*DOMAIN*VERIFIED
	ImprovedPerformances []string `pulumi:"improvedPerformances"`
	// The login UI will use the settings of the default org (and not from the instance) if no organization context is set
	LoginDefaultOrg *bool `pulumi:"loginDefaultOrg"`
	// Specify the login UI for all users and applications regardless of their preference.
	LoginV2 *SystemFeaturesLoginV2 `pulumi:"loginV2"`
	// If the flag is enabled, you'll be able to terminate a single session from the login UI by providing an id*token with a `sid` claim as id*token*hint on the end*session endpoint. Note that currently all sessions from the same user agent (browser) are terminated in the login UI. Sessions managed through the Session API already allow the termination of single sessions.
	OidcSingleV1SessionTermination *bool `pulumi:"oidcSingleV1SessionTermination"`
	// Enable the experimental `urn:ietf:params:oauth:grant-type:token-exchange` grant type for the OIDC token endpoint. Token exchange can be used to request tokens with a lesser scope or impersonate other users. See the security policy to allow impersonation on an instance.
	OidcTokenExchange *bool `pulumi:"oidcTokenExchange"`
	// Enable a newer, more performant, permission check used for v2 and v3 resource based APIs.
	PermissionCheckV2 *bool `pulumi:"permissionCheckV2"`
	// User Schemas allow to manage data schemas of user. If the flag is enabled, you'll be able to use the new API and its features. Note that it is still in an early stage.
	UserSchema *bool `pulumi:"userSchema"`
}

// The set of arguments for constructing a SystemFeatures resource.
type SystemFeaturesArgs struct {
	// If the flag is enabled, you'll be able to use the OIDC Back-Channel Logout to be notified in your application about terminated user sessions.
	EnableBackChannelLogout pulumi.BoolPtrInput
	// Improves performance of specified execution paths. Possible values: IMPROVED*PERFORMANCE*PROJECT*GRANT, IMPROVED*PERFORMANCE*PROJECT, IMPROVED*PERFORMANCE*USER*GRANT, IMPROVED*PERFORMANCE*ORG*DOMAIN*VERIFIED
	ImprovedPerformances pulumi.StringArrayInput
	// The login UI will use the settings of the default org (and not from the instance) if no organization context is set
	LoginDefaultOrg pulumi.BoolPtrInput
	// Specify the login UI for all users and applications regardless of their preference.
	LoginV2 SystemFeaturesLoginV2PtrInput
	// If the flag is enabled, you'll be able to terminate a single session from the login UI by providing an id*token with a `sid` claim as id*token*hint on the end*session endpoint. Note that currently all sessions from the same user agent (browser) are terminated in the login UI. Sessions managed through the Session API already allow the termination of single sessions.
	OidcSingleV1SessionTermination pulumi.BoolPtrInput
	// Enable the experimental `urn:ietf:params:oauth:grant-type:token-exchange` grant type for the OIDC token endpoint. Token exchange can be used to request tokens with a lesser scope or impersonate other users. See the security policy to allow impersonation on an instance.
	OidcTokenExchange pulumi.BoolPtrInput
	// Enable a newer, more performant, permission check used for v2 and v3 resource based APIs.
	PermissionCheckV2 pulumi.BoolPtrInput
	// User Schemas allow to manage data schemas of user. If the flag is enabled, you'll be able to use the new API and its features. Note that it is still in an early stage.
	UserSchema pulumi.BoolPtrInput
}

func (SystemFeaturesArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*systemFeaturesArgs)(nil)).Elem()
}

type SystemFeaturesInput interface {
	pulumi.Input

	ToSystemFeaturesOutput() SystemFeaturesOutput
	ToSystemFeaturesOutputWithContext(ctx context.Context) SystemFeaturesOutput
}

func (*SystemFeatures) ElementType() reflect.Type {
	return reflect.TypeOf((**SystemFeatures)(nil)).Elem()
}

func (i *SystemFeatures) ToSystemFeaturesOutput() SystemFeaturesOutput {
	return i.ToSystemFeaturesOutputWithContext(context.Background())
}

func (i *SystemFeatures) ToSystemFeaturesOutputWithContext(ctx context.Context) SystemFeaturesOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SystemFeaturesOutput)
}

type SystemFeaturesOutput struct{ *pulumi.OutputState }

func (SystemFeaturesOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**SystemFeatures)(nil)).Elem()
}

func (o SystemFeaturesOutput) ToSystemFeaturesOutput() SystemFeaturesOutput {
	return o
}

func (o SystemFeaturesOutput) ToSystemFeaturesOutputWithContext(ctx context.Context) SystemFeaturesOutput {
	return o
}

// If the flag is enabled, you'll be able to use the OIDC Back-Channel Logout to be notified in your application about terminated user sessions.
func (o SystemFeaturesOutput) EnableBackChannelLogout() pulumi.BoolOutput {
	return o.ApplyT(func(v *SystemFeatures) pulumi.BoolOutput { return v.EnableBackChannelLogout }).(pulumi.BoolOutput)
}

// Improves performance of specified execution paths. Possible values: IMPROVED*PERFORMANCE*PROJECT*GRANT, IMPROVED*PERFORMANCE*PROJECT, IMPROVED*PERFORMANCE*USER*GRANT, IMPROVED*PERFORMANCE*ORG*DOMAIN*VERIFIED
func (o SystemFeaturesOutput) ImprovedPerformances() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *SystemFeatures) pulumi.StringArrayOutput { return v.ImprovedPerformances }).(pulumi.StringArrayOutput)
}

// The login UI will use the settings of the default org (and not from the instance) if no organization context is set
func (o SystemFeaturesOutput) LoginDefaultOrg() pulumi.BoolOutput {
	return o.ApplyT(func(v *SystemFeatures) pulumi.BoolOutput { return v.LoginDefaultOrg }).(pulumi.BoolOutput)
}

// Specify the login UI for all users and applications regardless of their preference.
func (o SystemFeaturesOutput) LoginV2() SystemFeaturesLoginV2Output {
	return o.ApplyT(func(v *SystemFeatures) SystemFeaturesLoginV2Output { return v.LoginV2 }).(SystemFeaturesLoginV2Output)
}

// If the flag is enabled, you'll be able to terminate a single session from the login UI by providing an id*token with a `sid` claim as id*token*hint on the end*session endpoint. Note that currently all sessions from the same user agent (browser) are terminated in the login UI. Sessions managed through the Session API already allow the termination of single sessions.
func (o SystemFeaturesOutput) OidcSingleV1SessionTermination() pulumi.BoolOutput {
	return o.ApplyT(func(v *SystemFeatures) pulumi.BoolOutput { return v.OidcSingleV1SessionTermination }).(pulumi.BoolOutput)
}

// Enable the experimental `urn:ietf:params:oauth:grant-type:token-exchange` grant type for the OIDC token endpoint. Token exchange can be used to request tokens with a lesser scope or impersonate other users. See the security policy to allow impersonation on an instance.
func (o SystemFeaturesOutput) OidcTokenExchange() pulumi.BoolOutput {
	return o.ApplyT(func(v *SystemFeatures) pulumi.BoolOutput { return v.OidcTokenExchange }).(pulumi.BoolOutput)
}

// Enable a newer, more performant, permission check used for v2 and v3 resource based APIs.
func (o SystemFeaturesOutput) PermissionCheckV2() pulumi.BoolOutput {
	return o.ApplyT(func(v *SystemFeatures) pulumi.BoolOutput { return v.PermissionCheckV2 }).(pulumi.BoolOutput)
}

// User Schemas allow to manage data schemas of user. If the flag is enabled, you'll be able to use the new API and its features. Note that it is still in an early stage.
func (o SystemFeaturesOutput) UserSchema() pulumi.BoolOutput {
	return o.ApplyT(func(v *SystemFeatures) pulumi.BoolOutput { return v.UserSchema }).(pulumi.BoolOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*SystemFeaturesInput)(nil)).Elem(), &SystemFeatures{})
	pulumi.RegisterOutputType(SystemFeaturesOutput{})
}
