// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package zitadel

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/truvity/pulumi-zitadel/sdk/go/zitadel/internal"
)

// Customizes the phone number verification SMS sent to users (org-scoped). Instance-level defaults are managed by `DefaultVerifyPhoneMessageText`.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/truvity/pulumi-zitadel/sdk/go/zitadel"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := zitadel.NewVerifyPhoneMessageText(ctx, "default", &zitadel.VerifyPhoneMessageTextArgs{
//				OrgId:    pulumi.Any(defaultZitadelOrg.Id),
//				Language: pulumi.String("en"),
//				Text:     pulumi.String("text example"),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
type VerifyPhoneMessageText struct {
	pulumi.CustomResourceState

	ButtonText pulumi.StringPtrOutput `pulumi:"buttonText"`
	FooterText pulumi.StringPtrOutput `pulumi:"footerText"`
	Greeting   pulumi.StringPtrOutput `pulumi:"greeting"`
	Language   pulumi.StringOutput    `pulumi:"language"`
	OrgId      pulumi.StringOutput    `pulumi:"orgId"`
	PreHeader  pulumi.StringPtrOutput `pulumi:"preHeader"`
	Subject    pulumi.StringPtrOutput `pulumi:"subject"`
	Text       pulumi.StringPtrOutput `pulumi:"text"`
	Title      pulumi.StringPtrOutput `pulumi:"title"`
}

// NewVerifyPhoneMessageText registers a new resource with the given unique name, arguments, and options.
func NewVerifyPhoneMessageText(ctx *pulumi.Context,
	name string, args *VerifyPhoneMessageTextArgs, opts ...pulumi.ResourceOption) (*VerifyPhoneMessageText, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Language == nil {
		return nil, errors.New("invalid value for required argument 'Language'")
	}
	if args.OrgId == nil {
		return nil, errors.New("invalid value for required argument 'OrgId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource VerifyPhoneMessageText
	err := ctx.RegisterResource("zitadel:index/verifyPhoneMessageText:VerifyPhoneMessageText", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetVerifyPhoneMessageText gets an existing VerifyPhoneMessageText resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetVerifyPhoneMessageText(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *VerifyPhoneMessageTextState, opts ...pulumi.ResourceOption) (*VerifyPhoneMessageText, error) {
	var resource VerifyPhoneMessageText
	err := ctx.ReadResource("zitadel:index/verifyPhoneMessageText:VerifyPhoneMessageText", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering VerifyPhoneMessageText resources.
type verifyPhoneMessageTextState struct {
	ButtonText *string `pulumi:"buttonText"`
	FooterText *string `pulumi:"footerText"`
	Greeting   *string `pulumi:"greeting"`
	Language   *string `pulumi:"language"`
	OrgId      *string `pulumi:"orgId"`
	PreHeader  *string `pulumi:"preHeader"`
	Subject    *string `pulumi:"subject"`
	Text       *string `pulumi:"text"`
	Title      *string `pulumi:"title"`
}

type VerifyPhoneMessageTextState struct {
	ButtonText pulumi.StringPtrInput
	FooterText pulumi.StringPtrInput
	Greeting   pulumi.StringPtrInput
	Language   pulumi.StringPtrInput
	OrgId      pulumi.StringPtrInput
	PreHeader  pulumi.StringPtrInput
	Subject    pulumi.StringPtrInput
	Text       pulumi.StringPtrInput
	Title      pulumi.StringPtrInput
}

func (VerifyPhoneMessageTextState) ElementType() reflect.Type {
	return reflect.TypeOf((*verifyPhoneMessageTextState)(nil)).Elem()
}

type verifyPhoneMessageTextArgs struct {
	ButtonText *string `pulumi:"buttonText"`
	FooterText *string `pulumi:"footerText"`
	Greeting   *string `pulumi:"greeting"`
	Language   string  `pulumi:"language"`
	OrgId      string  `pulumi:"orgId"`
	PreHeader  *string `pulumi:"preHeader"`
	Subject    *string `pulumi:"subject"`
	Text       *string `pulumi:"text"`
	Title      *string `pulumi:"title"`
}

// The set of arguments for constructing a VerifyPhoneMessageText resource.
type VerifyPhoneMessageTextArgs struct {
	ButtonText pulumi.StringPtrInput
	FooterText pulumi.StringPtrInput
	Greeting   pulumi.StringPtrInput
	Language   pulumi.StringInput
	OrgId      pulumi.StringInput
	PreHeader  pulumi.StringPtrInput
	Subject    pulumi.StringPtrInput
	Text       pulumi.StringPtrInput
	Title      pulumi.StringPtrInput
}

func (VerifyPhoneMessageTextArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*verifyPhoneMessageTextArgs)(nil)).Elem()
}

type VerifyPhoneMessageTextInput interface {
	pulumi.Input

	ToVerifyPhoneMessageTextOutput() VerifyPhoneMessageTextOutput
	ToVerifyPhoneMessageTextOutputWithContext(ctx context.Context) VerifyPhoneMessageTextOutput
}

func (*VerifyPhoneMessageText) ElementType() reflect.Type {
	return reflect.TypeOf((**VerifyPhoneMessageText)(nil)).Elem()
}

func (i *VerifyPhoneMessageText) ToVerifyPhoneMessageTextOutput() VerifyPhoneMessageTextOutput {
	return i.ToVerifyPhoneMessageTextOutputWithContext(context.Background())
}

func (i *VerifyPhoneMessageText) ToVerifyPhoneMessageTextOutputWithContext(ctx context.Context) VerifyPhoneMessageTextOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VerifyPhoneMessageTextOutput)
}

type VerifyPhoneMessageTextOutput struct{ *pulumi.OutputState }

func (VerifyPhoneMessageTextOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**VerifyPhoneMessageText)(nil)).Elem()
}

func (o VerifyPhoneMessageTextOutput) ToVerifyPhoneMessageTextOutput() VerifyPhoneMessageTextOutput {
	return o
}

func (o VerifyPhoneMessageTextOutput) ToVerifyPhoneMessageTextOutputWithContext(ctx context.Context) VerifyPhoneMessageTextOutput {
	return o
}

func (o VerifyPhoneMessageTextOutput) ButtonText() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *VerifyPhoneMessageText) pulumi.StringPtrOutput { return v.ButtonText }).(pulumi.StringPtrOutput)
}

func (o VerifyPhoneMessageTextOutput) FooterText() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *VerifyPhoneMessageText) pulumi.StringPtrOutput { return v.FooterText }).(pulumi.StringPtrOutput)
}

func (o VerifyPhoneMessageTextOutput) Greeting() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *VerifyPhoneMessageText) pulumi.StringPtrOutput { return v.Greeting }).(pulumi.StringPtrOutput)
}

func (o VerifyPhoneMessageTextOutput) Language() pulumi.StringOutput {
	return o.ApplyT(func(v *VerifyPhoneMessageText) pulumi.StringOutput { return v.Language }).(pulumi.StringOutput)
}

func (o VerifyPhoneMessageTextOutput) OrgId() pulumi.StringOutput {
	return o.ApplyT(func(v *VerifyPhoneMessageText) pulumi.StringOutput { return v.OrgId }).(pulumi.StringOutput)
}

func (o VerifyPhoneMessageTextOutput) PreHeader() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *VerifyPhoneMessageText) pulumi.StringPtrOutput { return v.PreHeader }).(pulumi.StringPtrOutput)
}

func (o VerifyPhoneMessageTextOutput) Subject() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *VerifyPhoneMessageText) pulumi.StringPtrOutput { return v.Subject }).(pulumi.StringPtrOutput)
}

func (o VerifyPhoneMessageTextOutput) Text() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *VerifyPhoneMessageText) pulumi.StringPtrOutput { return v.Text }).(pulumi.StringPtrOutput)
}

func (o VerifyPhoneMessageTextOutput) Title() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *VerifyPhoneMessageText) pulumi.StringPtrOutput { return v.Title }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*VerifyPhoneMessageTextInput)(nil)).Elem(), &VerifyPhoneMessageText{})
	pulumi.RegisterOutputType(VerifyPhoneMessageTextOutput{})
}
