// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package internal

import (
	"github.com/blang/semver"
)

var SdkVersion semver.Version = semver.MustParse("3.3.7")
var pluginDownloadURL string = "github://api.github.com/truvity/pulumi-zitadel"
