name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.14.0

      - name: Build provider
        run: devbox run -- just provider

      - name: Build SDK
        run: devbox run -- just build-sdk

      - name: Lint provider
        run: devbox run -- just lint

      - name: Vulnerability check
        run: devbox run -- just vuln
